### ISSUE TITLE
ERROR: Could not save configuration

### ISSUE THREAD

**Issue by redbaron-gt** [nrlquaker/winbox-mac#1]
I got this error when saving connection. No save folder is changed.

**Comment by nrlquaker** [comment]
Please provide more information.
And steps to reproduce.

**Comment by redbaron-gt** [comment]
I have MacOS HighSierra 10.13.3
Installed as specified:
brew tap nrlquaker/personal
brew cask install winbox-mac in readme
After starting winbox-mac I add some connection and push Add/Set and receive error in bottom part of windows, after restarting program connection list is empty. 
<img width="1012" alt="screen shot 2018-02-11 at 14 04 31" src="https://user-images.githubusercontent.com/10510599/36072180-acb20d8e-0f34-11e8-8f78-7d252bb001e9.png">

**Comment by nrlquaker** [comment]
I was able to reproduce this. Will think how can it be fixed.

**Comment by nrlquaker** [comment]
@redbaron-gt can you please download version [3.11](https://github.com/nrlquaker/winbox-mac/releases/download/v3.11/Winbox-mac-3.11.zip) and check if error is present?

**Comment by redbaron-gt** [comment]
Same problem

**Comment by nrlquaker** [comment]
Issue is fixed in the latest release.
You can download it from [Releases](https://github.com/nrlquaker/winbox-mac/releases).
Or install using `brew cask`:
```
brew update
brew uninstall winbox-mac
brew install winbox-mac
```

**Comment by FrankGiesecke** [comment]
Sadly to say that the problem seems to be back in v3.37
