### ISSUE TITLE
Doesn't work on 10.15 Catalina Beta

### ISSUE THREAD

**Issue by kirush0280** [nrlquaker/winbox-mac#10]
% brew cask reinstall nrlquaker-winbox
==> Satisfying dependencies
==> Downloading https://github.com/nrlquaker/winbox-mac/releases/download/v3.19/Winbox-mac-3.19.zip
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/7b3b61873ce116c4beacf74690421e80a5187264654f931c390701c090b4fe6f--Winbox-mac-3.19.zip
==> Verifying SHA-256 checksum for Cask 'nrlquaker-winbox'.
==> Uninstalling Cask nrlquaker-winbox
==> Backing App 'Winbox-mac.app' up to '/usr/local/Caskroom/nrlquaker-winbox/3.19/Winbox-mac.app'.
==> Removing App '/Applications/Winbox-mac.app'.
==> Purging files for version 3.19 of Cask nrlquaker-winbox
==> Installing Cask nrlquaker-winbox
==> Moving App 'Winbox-mac.app' to '/Applications/Winbox-mac.app'.
🍺  nrlquaker-winbox was successfully installed!

Screenshot says:
File .... can't be opened, because can't confirm integrity.
Need to updat. Please contact developer for details.

![2019-09-18_22-39-08](https://user-images.githubusercontent.com/13412942/65180301-3ce98600-da65-11e9-9cfb-8c950972c282.png)

**Comment by nrlquaker** [comment]
@kirush0280 I think its because of lack of 32-bit apps support in Catalina.
Will post test build later today.

**Comment by kirush0280** [comment]
thank you for such fast answer.

**Comment by nrlquaker** [comment]
I've created [test app](http://www.mediafire.com/file/k00moo587xvsvlf/Winbox-3.19-Catalina-devel.app.zip/file) for Catalina. Just press `Cancel` when asked about mono.
But its far from final version and just to check if it works on Catalina.
Please tell if it opens correctly.
Will create version for Catalina after it will be released.

**Comment by kirush0280** [comment]
![2019-09-18_23-41-19](https://user-images.githubusercontent.com/13412942/65184303-e5034d00-da6d-11e9-8bb2-a6d50d1234cd.png)
The same

**Comment by nrlquaker** [comment]
Seems like its due to new [Apple's requirement](https://help.apple.com/xcode/mac/current/#/dev033e997ca) that all apps should be notarized. 
You have completely disable Gatekeeper to run the app.

**Comment by kirush0280** [comment]
1. I disabled it.
2. Allow to run software downloaded from third-party source
Now when i run it, its shows in dock about 5 sec, and disappeared.

**Comment by nrlquaker** [comment]
I see. I will investigate it and release proper version when Catalina will be released.
