### ISSUE TITLE
Mouse is locked in a left top square & window cannot be resized

### ISSUE THREAD

**Issue by kiler129** [nrlquaker/winbox-mac#105]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Running on M1 Max MBP the winbox is behaving strangely. When opened it always defaults to a very small, almost unusable, window size. After connecting the window cannot be resized and the mouse cursor is "jailed" in left top ~1/4 of the screen. Sometime (1/10 times) using Cmd+Tab to another window and back fixes it. This bug does not occur 100% of the time, which makes it even more annoying.
I attempted to clear `~/.wine` which didn't fix the problem.

**To Reproduce**
1. Open winbox
2. Connect to a device
3. Attempt to resize window

**Expected behavior**
Window should react like a normal macOS window.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macOS version: `12.4 (21F79)`
 - macOS language: English (US locale)
 - Winbox-mac version: `3.37.0`
 - Winbox version:  `3.37`

**Additional context**
No sidecar is being used. However, I have multiple mixed-DPI screens. The issue also happens with just the MBP screen only.

**Comment by Trunkzeh** [comment]
I had this same exact issue on an Intel MBP (Late 2018 i7) so I do not believe it to be related to architecture. I had updated to 3.37.0 and could not resize the screen and the best way to describe it the screen size is 'halved' where the mouse is unable to proceed past half.

What resolved it for me was downgrading back down to 3.36.0 (not 3.36.1 or any other point release); and then upgrading back up to 3.37.0. 

I dont have any multi-screen setup; sidecar etc..

**Comment by daryll-swer** [comment]
The work-around is to “enter full screen” mode, the window size will be full again. It's weird.

**Comment by lilarcor** [comment]
I got same issue , intel mac book

**Comment by Trunkzeh** [comment]
Perhaps it pertains to the bundled wine-7.0 release @Gcenx

**Comment by haiz85** [comment]
> I had this same exact issue on an Intel MBP (Late 2018 i7) so I do not believe it to be related to architecture. I had updated to 3.37.0 and could not resize the screen and the best way to describe it the screen size is 'halved' where the mouse is unable to proceed past half.
> 
> What resolved it for me was downgrading back down to 3.36.0 (not 3.36.1 or any other point release); and then upgrading back up to 3.37.0.
> 
> I dont have any multi-screen setup; sidecar etc..

sorry I'm new to this, can you share to downgrade to previous version?

**Comment by archer-github** [comment]
> can you share to downgrade to previous version?

Hey there, I got the same issue on my Intel Mac, so the solution is pretty easy:

1. Uninstall the current version by executing: `brew uninstall nrlquaker-winbox`
2. Download version 3.36.0 using this [link](https://github.com/nrlquaker/winbox-mac/releases/download/v3.36.0/Winbox-mac-3.36.0.zip). 
3. Unzip a file, and move it to Applications folder as you usually do with any other apps.

**Comment by godzillante** [comment]
Can confirm on MBP M1 Pro & MacOS 12.5.1 (still couldn't update to 12.6)
@daryll-swer 's workaround saved my life temporarily

**Comment by randyoo** [comment]
Thanks, @archer-github !

**Comment by godzillante** [comment]
Couldn't test @archer-github solution. However another good workaround seems to be opening a new Winbox from the current window, like this:

![Schermata 2022-10-17 alle 09 23 31](https://user-images.githubusercontent.com/781092/196114322-99ac4d29-7869-43b3-8147-e8085a3ab923.png)

**Comment by nrlquaker** [comment]
Seems like a `wine` issue. Please report it on [their forum](https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=STAGED&product=Wine&columnlist=bug_severity,priority,bug_status,cf_regression_sha1sum,short_desc,changeddate&keywords=regression&keywords_type=anywords).

**Comment by kiler129** [comment]
@nrlquaker This doesn't seem to be happening with any other app I run on wine.. so maybe it's a winbox issue? Seems like a combo of wine-winbox-winbox on mac issue and not an isolated wine problem.

**Comment by nrlquaker** [comment]
@kiler129 For me its working fine for MBP M1 without other displays connected. There was an issue with resize problems with external display or sidecar. My suggestion is to try different wine versions without external displays and compare results. According to comments to this issue its a problem with `wine stable 7.0`.

**Comment by kiler129** [comment]
This may actually be a bug in macOS WindowServer as this doesn't seem to affect any of my Ventura (macOS 13.0) machines.

**Comment by daryll-swer** [comment]
I am using MacBook Air M1 with no external displays. The issue with the Windowing/Sizing is even worse on macOS Ventura.

Installing Wine latest stable and xquartz via brew of course did not resolve the issue at all on Ventura.

@nrlquaker

**Comment by Gcenx** [comment]
> I am using MacBook Air M1 with no external displays. The issue with the Windowing/Sizing is even worse on macOS Ventura.

This sounds like an upstream issue.

> Installing Wine latest stable and xquartz via brew of course did not resolve the issue at all on Ventura.

If your install the wine-stable cask there’s no need to install XQuartz that’s not been a requirement since I’d taken over the Winehq macOS packages, try again against the wine-devel cask.

**Comment by daryll-swer** [comment]
@Gcenx 

Here's what I did:
1. Remove/Cleanup XQuartz
2. Install wine-stable
3. Remove winbox-mac
4. Download official Winbox from MikroTik
5. Load it up via Wine
6. Viola no display/sizing issues at all!

I'll stick with official Winbox exe file going forward - It just works with wine.

**Comment by Gcenx** [comment]
@daryll-swer interesting….

I know there’s some weird bug with terminal on macOS Ventura I wonder if that’s related.

Outside of that being a factor I could possibly be related to the reverts required to support macOS High Sierra and prior, upstream started to use a private API to grabbing the mouse without additional permissions.
