### ISSUE TITLE
Unable to detect neighbors through usb nic on M2 devices

### ISSUE THREAD

**Issue by TigerHuang** [nrlquaker/winbox-mac#106]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Unable to detect neighbors through USB NIC on M2 Macbook Air, it works fine via WiFi.

Tested on Belkin USB-C LAN、AX88179、RTL8156B Type-C USB NIC - None of them work.
Tested manually setting the IP on the USB NIC - Not working
Tried to connect via IP - Worked fine

**To Reproduce**
1. Connect the USB NIC to the M2 Macbook
2. Open Winbox-mac
3. Click the Neighbors tab 
4. No devices were found

**Desktop (please complete the following information):**
 - macOS version: 12.5.1
 - macOS language: English
 - Winbox-mac version: 3.37.0
 - Winbox version: 3.37

**Comment by nrlquaker** [comment]
Please check related issues: #68 #53 #26 #3.
Working fine for me via Wi-Fi.
If you know how to fix it please create PR.
