### ISSUE TITLE
Problem with opening connections with the "Open in New Window" option.

### ISSUE THREAD

**Issue by WojRep** [nrlquaker/winbox-mac#107]
If I select the "Open in New Window" option, it does not open the connection properly.

There is an inscription in the window about establishing a connection to MikroTik, but the new winbox window does not appear immediately. Only after a few seconds (5-10s) a new window pops up with the connection.

Video attached,

![2022-08-24_09-44](https://user-images.githubusercontent.com/38716214/186360782-bd307db7-381a-45bb-8fa7-80c0437e8de9.png)

https://user-images.githubusercontent.com/38716214/186362642-18074510-bf53-43a6-81d4-76eafb74feec.mp4

**Comment by unps** [comment]
I have this problem too.

**Comment by WojRep** [comment]
This problem has occurred from version: v3.36.1 (update Wine to stable 7.0)

I went back to version v3.36.0 and everything works fine. 
Upgrading only WinBox to version 3.37 can be done via Winbox itself.

**Comment by nrlquaker** [comment]
@Gcenx any ideas what can be the isue in the new wine?

**Comment by Gcenx** [comment]
> @Gcenx any ideas what can be the issue in the new wine?

No clue possibly an upstream regression I’m not aware of (or just not reported)

**Comment by alexanderek** [comment]
How can I downgrade to 3.36?

**Comment by WojRep** [comment]
Uninstall package with brew.
Download manually from github release 3.36, unpack and use.

**Comment by nrlquaker** [comment]
Seems like a `wine` issue. Please report it on [their forum](https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=STAGED&product=Wine&columnlist=bug_severity,priority,bug_status,cf_regression_sha1sum,short_desc,changeddate&keywords=regression&keywords_type=anywords).

**Comment by hunter-nl** [comment]
This doesn't seems like a wine issue. When starting winbox64.exe directly from wine-stable 8.0.1 terminal, it is working just fine and fast. When starting it with winbox-mac then this issue is happening.

**Comment by alexanderek** [comment]
same issue

**Comment by patriciomartinns** [comment]
I've been having the same problem for a while, it only works if I go back to version 3.36
