### ISSUE TITLE
Comment 能否支持中文？

### ISSUE THREAD

**Issue by cmmchina** [nrlquaker/winbox-mac#108]
windwos环境下可以显示的中文，在mac下只能显示乱码。

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
<img width="490" alt="QQ20220924-115920@2x" src="https://user-images.githubusercontent.com/29941503/192079103-b5b5fde9-92a8-4be2-9a86-71712c482694.png">

**Additional context**

**Comment by nrlquaker** [comment]
Please check https://github.com/nrlquaker/winbox-mac/pull/103
If it fixes your issue give it 👍.  
I don't have time to support non-english locales.
