### ISSUE TITLE
Catalina support

### ISSUE THREAD

**Issue by Atroc-0625** [nrlquaker/winbox-mac#11]
10.15 Catalina 无法正常打开

**Comment by xh116** [comment]
![image](https://user-images.githubusercontent.com/37950502/66506790-93942e00-eb00-11e9-9aa7-23add563a202.png)

**Comment by Vovanys** [comment]
+ one option
https://github.com/AndreRH/hangover/issues/35

**Comment by kirush0280** [comment]
winbox 64 bit released 
Version: 3.20 (winbox)

**Comment by rasperepodvipodvert** [comment]
https://mt.lv/winbox64

**Comment by nrlquaker** [comment]
Latest Winebottler (4.0.1.1) has an issue. When creating app it invokes `wine`, not `wine64`.
I've mailed the author and waiting for response.
Temporary solution is to launch it from CLI or create Apple Script:
- install `Winebottler` `brew cask install nrlquaker/personal/winebottler`;
- install `xquartz` `brew cask install xquartz`;
- open `Wine.app` with right click -> open, allow to launch;
- launch `wine64` from CLI: `/Applications/Wine.app/Contents/Resources/bin/wine64 winbox64.exe`

**Comment by rasperepodvipodvert** [comment]
> * install `Winebottler` `brew cask install nrlquaker/personal/winebottler`;
> * install `xquartz` `brew cask install xquartz`;
> * open `Wine.app` with right click -> open, allow to launch;
> * launch `wine64` from CLI: `/Applications/Wine.app/Contents/Resources/bin/wine64 ```
winbox64.exe`

ivanfilatov@MacBook-Air-Ivan Downloads % /Applications/Wine.app/Contents/Resources/bin/wine64 winbox64.exe
0009:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
creating Window Class routeros_null
creating Window Class routeros_connect
creating Window Class routeros_dbl_canvas
0009:fixme:seh:RtlCaptureStackBackTrace (0, 32, 0x32bc00, 0x0) stub!

ACCESS VIOLATION EXCEPTION at address: _______________0

rip=_______________0 eflags=__ 10287
rdi=_______________2 rsi=_________ 32dad8 rbp=_________ 32d790 rsp=_________ 32d678
rax=_______ 6b6fcacb rbx=_________ 62f980 rcx=_______ 6b71d080 rdx=_____________ 61
 r8=_____________ 41  r9=3f80000000000000 r10=_________ 32dafc r11=ffffffffffd2406c
r12=_________ 62ff20 r13=_________ 62f980 r14=____________ 22e r15=_________ 32dea8

winbox version: 3.20

backtrace:


stack:
_______ 6b6c43b0 ffffffff00000000 _______________0 _________ 32d790 
_______ 6b6a2bba 7900414981560219 4b902f11ce2ee314 791f98d2a742a05d 
______ 100000000 ______ 100000000 _________ 32dad8 _______________0 
______ 16b71d4f0 6cce44484b902f11 6003a6fd00000000 _______________0 

linked to KERNEL32!
0009:err:virtual:map_file_into_view failed to set PROT_EXEC on file map, noexec filesystem?
0009:err:virtual:virtual_map_section mapping 0x380000 8000 000000000 failed
0009:err:virtual:map_file_into_view failed to set PROT_EXEC on file map, noexec filesystem?
0009:err:virtual:virtual_map_section mapping 0x380000 8000 000000000 failed
moduleFirst failed 5
0009:fixme:seh:RtlCaptureStackBackTrace (0, 32, 0x32a140, 0x0) stub!


code:
ACCESS VIOLATION EXCEPTION at address: _________ 421508

rip=_________ 421508 eflags=__ 10202
rdi=_________ 5d5200 rsi=_________ 523aa0 rbp=_________ 523aa0 rsp=_________ 32bbb0
rax=_________ 5d5200 rbx=_______________0 rcx=_______________0 rdx=_________ 523b45
 r8=_______________7  r9=_________ 5d5200 r10=_______________0 r11=____________ 216
r12=_______________0 r13=_____________ 98 r14=_________ 32bd00 r15=_________ 5d6940

winbox version: 3.20

backtrace:


stack:
_________ 62ff20 _______________5 ______ f00000000 _________ 32bd50 
_________ 32bc00 _____________ 28 _________ 32ca08 _________ 62f980 
_________ 32bd50 _________ 32c910 _________ 32c5f0 _______ 7bcadc37 
_______________0 _______________0 _______________0 _______________0 

linked to KERNEL32!
0009:err:virtual:map_file_into_view failed to set PROT_EXEC on file map, noexec filesystem?
0009:err:virtual:virtual_map_section mapping 0x380000 8000 000000000 failed
0009:err:virtual:map_file_into_view failed to set PROT_EXEC on file map, noexec filesystem?
0009:err:virtual:virtual_map_section mapping 0x380000 8000 000000000 failed
moduleFirst failed 5

code:
41 0f b6 0c 1c 45 31 c9 4c 89 f2 48 ff c3 41 b8 
```

**Comment by rasperepodvipodvert** [comment]
i install winehq-staging-4.17.pkg
rm -rf ~/.wine/
/Applications/Wine\ Staging.app/Contents/Resources/wine/bin/wine64 winbox64.exe

and winbox start!!!

**Comment by nrlquaker** [comment]
Forgot to mansion, you should remove old wine config/prefix:
`rm -rf ~/.wine/`.

**Comment by nrlquaker** [comment]
Exporting/importing is broken in latest winbox (at least on macOS), so just copy saved connections:
```
cp ~/Library/Application\ Support/com.mikrotik.winbox_156313927421589/drive_c/users/winbox/Application\ Data/Mikrotik/Winbox/Addresses.cdb ~/.wine/drive_c/users/`id -un`/Application\ Data/Mikrotik/Winbox/`
```

**Comment by Atroc-0625** [comment]
> Exporting/importing is broken in latest winbox (at least on macOS), so just copy saved connections:
> 
> ```
> cp ~/Library/Application\ Support/com.mikrotik.winbox_156313927421589/drive_c/users/winbox/Application\ Data/Mikrotik/Winbox/Addresses.cdb ~/.wine/drive_c/users/`id -un`/Application\ Data/Mikrotik/Winbox/`
> ```

When do you release winbox? I need it, I want to use the version you released.

**Comment by rasperepodvipodvert** [comment]
It is Work!!!

**Comment by nrlquaker** [comment]
> When do you release winbox? I need it, I want to use the version you released.
When author of Winebottler will fix the issue I described.

**Comment by nrlquaker** [comment]
I've published [3.20 test version](https://github.com/nrlquaker/winbox-mac/releases/download/3.20-test/Winbox-mac-3.20-test.zip). Can someone test it? It works fine on my setup, but got issues on VM. Not sure if those issues are related to VM or app.

**Comment by luccaccine** [comment]
> I've published [3.20 test version](https://github.com/nrlquaker/winbox-mac/releases/download/3.20-test/Winbox-mac-3.20-test.zip). Can someone test it? It works fine on my setup, but got issues on VM. Not sure if those issues are related to VM or app.

didn't work:
<img width="2560" alt="Screen Shot 2019-10-17 at 20 09 07" src="https://user-images.githubusercontent.com/8313551/67054527-3e1cda00-f11b-11e9-847d-d9f73d6c1b7f.png">

after `rm -rf ~/.wine/`:
<img width="2560" alt="Screen Shot 2019-10-17 at 20 17 31" src="https://user-images.githubusercontent.com/8313551/67054554-54c33100-f11b-11e9-9466-11f6cc940227.png">

i don't have wine/winebootler installed.

**Comment by xh116** [comment]
Not work here also...

**Comment by korotkov13** [comment]
I got the same picture as @luccaccine

**Comment by Atroc-0625** [comment]
> I've published [3.20 test version](https://github.com/nrlquaker/winbox-mac/releases/download/3.20-test/Winbox-mac-3.20-test.zip). Can someone test it? It works fine on my setup, but got issues on VM. Not sure if those issues are related to VM or app.

didn't work

**Comment by juanpedrojose** [comment]
<img width="1061" alt="Screenshot 2019-10-20 at 12 58 04" src="https://user-images.githubusercontent.com/341330/67157761-7f8ad080-f339-11e9-8721-7ae2a3f3bcc8.png">
Works fine on Catalina.

**Comment by 1o1o1** [comment]
> <img alt="Screenshot 2019-10-20 at 12 58 04" width="1061" src="https://user-images.githubusercontent.com/341330/67157761-7f8ad080-f339-11e9-8721-7ae2a3f3bcc8.png">
> 
> Works fine on Catalina.

HOW??  tell us everything!

**Comment by luccaccine** [comment]
> Latest Winebottler (4.0.1.1) has an issue. When creating app it invokes `wine`, not `wine64`.
> I've mailed the author and waiting for response.
> Temporary solution is to launch it from CLI or create Apple Script:
> 
> * install `Winebottler` `brew cask install nrlquaker/personal/winebottler`;
> * install `xquartz` `brew cask install xquartz`;
> * open `Wine.app` with right click -> open, allow to launch;
> * remove old wine config/prefix `rm -rf ~/.wine/`;
> * launch `wine64` from CLI: `/Applications/Wine.app/Contents/Resources/bin/wine64 winbox64.exe`.

i tried this, i got some errors related to `freetype` don't found.
then i run `brew install freetype`, `rm -rf ~/.wine/`, and it looked like it was going to work, but gets stucked on a wine windows that says something like "updating library".

i tried to open the bundle 3.20 provided by @nrlquaker, and it doesn't open anymore.
when i run `brew uninstall freetype`, it opens and again looks like the pics of my [previous post](https://github.com/nrlquaker/winbox-mac/issues/11#issuecomment-543404678).

i wonder if there's something related to `freetype`.

**Comment by luccaccine** [comment]
i got it working! 🎊🎉🎊🥳

<img width="929" alt="Screen Shot 2019-10-20 at 08 44 47" src="https://user-images.githubusercontent.com/8313551/67159049-e4ccca80-f315-11e9-86cb-40f601b0b915.png">

follow the steps:

1. install freetype: `brew install freetype`;
2. install xquarts: `brew cask install xquartz`;
3. open the file `/Winbox-mac.app/Contents/MacOS/startwine` in your favorite editor;
4. add the line `DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"` before the last one. save the file;
5. open the bundle `Winbox-mac.app` again. it will work.

[reference, item 13](https://wiki.winehq.org/MacOS_FAQ#head-710421bc5cde765adfb9b551853970013f2458c5)

my startwine file:
``` shell
#!/bin/bash

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

if [ -f "$BUNDLERESOURCEPATH/Wine.app/Contents/Resources/bin/wine64" ]; then
    export WINEUSRPATH="$BUNDLERESOURCEPATH/Wine.app/Contents/Resources"
fi

export WINEPREFIX="$HOME/Library/Application Support/$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleIdentifier)"
if [ ! -d "$WINEPREFIX" ]; then
    "$BUNDLERESOURCEPATH/Winetricks.app/Contents/MacOS/./Winetricks" "$BUNDLERESOURCEPATH/wineprefix" "$WINEPREFIX" "$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleName)" "WINEARCH=win64"
fi

#some default windows vars that might be missing ( http://ss64.com/nt/syntax-variables.html )
[ -z "$COMPUTERNAME" ] && export COMPUTERNAME="$(/usr/sbin/scutil --get ComputerName)"

# start wine and program, if possible in the programs root directory, change to forwardslashes
BIN_FILE="$(sed 's|\\|/|g' <<< "C:/winebottler/winbox64.exe")"
BIN_PATH="$BUNDLERESOURCEPATH/wineprefix/drive_c$(sed 's|C:||' <<< "$(dirname "$BIN_FILE")")"
if [ -d "$BIN_PATH" ]; then
    cd "$BIN_PATH"
fi

### This is the magic line <-------------------------------------
DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"

"$WINEUSRPATH/bin/wine64" "$BIN_FILE"
```

**Comment by nrlquaker** [comment]
Thanks a lot, @luccaccine.
I didn't have time to investigate it.
Will do some testing and publish 3.20 release later today.

**Comment by luccaccine** [comment]
> Thanks a lot, @luccaccine.
> I didn't have time to investigate it.
> Will do some testing and publish 3.20 release later today.

it's a great pleasure to contribute.
i made this icon like macOS style, you can use it, if you want.


![Icon1024](https://user-images.githubusercontent.com/8313551/67159556-80f9d000-f31c-11e9-8b85-ba376b092ae1.png)

**Comment by nrlquaker** [comment]
Thanks, will use it.

**Comment by 1o1o1** [comment]
$ brew install freetype
==> Installing dependencies for freetype: libpng
==> Installing freetype dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.37.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c8/c8e74da602c21f978cd7ee3d489979b4fc6681e71f678a1d99012943ee3a909f?__gda__=exp=1571580404~hmac=615db7
######################################################################## 100.0%
==> Pouring libpng-1.6.37.catalina.bottle.tar.gz

could not say what libpng-1.6.37.catalina.bottle.tar.gz is installed there ???  %))

**Comment by juanpedrojose** [comment]
> HOW?? tell us everything!

Just downloaded the app from releases, nothing in addition. Maybe I already had all the necessary libs installed previously ¯\_(ツ)_/¯

**Comment by soffchen** [comment]
> I've published [3.20 test version](https://github.com/nrlquaker/winbox-mac/releases/download/3.20-test/Winbox-mac-3.20-test.zip). Can someone test it? It works fine on my setup, but got issues on VM. Not sure if those issues are related to VM or app.

it works well directly.

**Comment by Atroc-0625** [comment]
> Thanks a lot, @luccaccine.
> I didn't have time to investigate it.
> Will do some testing and publish 3.20 release later today.
Hello, is the 3.20 release released?

**Comment by Atroc-0625** [comment]
> Thanks a lot, @luccaccine.
> I didn't have time to investigate it.
> Will do some testing and publish 3.20 release later today.

Hello, is the 3.20 release released?

**Comment by nrlquaker** [comment]
> Hello, is the 3.20 release released?
Not yet. But will be today.

**Comment by Atroc-0625** [comment]
> > Hello, is the 3.20 release released?
> 
> Not yet. But will be today.

Thank you, very much looking forward to

**Comment by darkpal** [comment]
3.20 works but when I try to use File-->Open or any other file browsing modal windows it just freezes

**Comment by nrlquaker** [comment]
It seems like wine issue. [Source](https://forum.mikrotik.com/viewtopic.php?f=2&t=152795&p=754827#p755159).

**Comment by nrlquaker** [comment]
Fixed in [latest release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20).
Wait till this [PR](https://github.com/Homebrew/homebrew-cask/pull/71250) will be merged before installing/updating using `brew cask`.

**Comment by Anonim-tech** [comment]
Nont work winbox force close.
