### ISSUE TITLE
Run multiple copy of app

### ISSUE THREAD

**Issue by mocart2** [nrlquaker/winbox-mac#111]
Hi!
Can i run multiple copy of app (many connections to many mikrotiks )?
Thanks.

**Comment by nrlquaker** [comment]
Its possible. Please check https://github.com/nrlquaker/winbox-mac/issues/75#issuecomment-909233897

**Comment by simitsis** [comment]
On macbook air M2 the "open in new window" does not work as expected. First nothing happens and then, minutes later a new winbox instance pops up saying the router has disconnected. Only then you can use the new window to log in a different router.
