### ISSUE TITLE
Problem with window size change on Apple M2

### ISSUE THREAD

**Issue by janky69** [nrlquaker/winbox-mac#112]
When I start the app, everything looks good, bud it is some issue with window resizing, mouse movement and maybe also with focusing.

**Desktop (please complete the following information):**
 - macOS version: 13.1
 - macOS language Czech
 - Winbox-mac version 3.37.0
 - Winbox version 3.37

**Comment by dario-pilori** [comment]
See my comment on a previous issue for a workaround: https://github.com/nrlquaker/winbox-mac/issues/109#issuecomment-1345305663

**Comment by nrlquaker** [comment]
Closed in favour of #109
