### ISSUE TITLE
Copy and Paste not working as expected.

### ISSUE THREAD

**Issue by lanhampr** [nrlquaker/winbox-mac#114]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**

With at least 2 winbox-mac windows open the ability to copy and paste stops working.  Each time I try and paste new content the previous content is pasted instead.  

**To Reproduce**

Copy some text, attempt a paste into winbox-mac terminal.

**Expected behavior**

Copy and Paste too work as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5]
 - macOS language [e.g. English, Russian, Chinese]
 - Winbox-mac version [e.g. 3.18]
 - Winbox version [e.g. 3.18]

Winbox-mac version 3.37

**Additional context**

The issue is temporarily resolved by closing all winbox-mac sessions and re-opening.

**Comment by nrlquaker** [comment]
@lanhampr please provide steps to reproduce.
