### ISSUE TITLE
Winbox Version Update

### ISSUE THREAD

**Issue by gkl1368** [nrlquaker/winbox-mac#119]
Please update winbox version to 3.38. Thanks.

**Comment by nrlquaker** [comment]
Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.28.0).
Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/146365) will be merged if you use `brew cask`.

**Comment by gkl1368** [comment]
> Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.28.0). Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/146365) will be merged if you use `brew cask`.
Can you update wine version to 8.0.1 stable?

**Comment by nrlquaker** [comment]
Waiting for @Gcenx to build it.

**Comment by gkl1368** [comment]
> Waiting for @Gcenx to build it.

Thanks.

**Comment by gkl1368** [comment]
> Waiting for @Gcenx to build it.

Please help to update new wine version. Thanks.
