### ISSUE TITLE
3.20 Not working properly

### ISSUE THREAD

**Issue by Atroc-0625** [nrlquaker/winbox-mac#12]
<img width="661" alt="WX20191022-092649@2x" src="https://user-images.githubusercontent.com/37469514/67254178-46c03800-f4ae-11e9-8fca-910421451046.png">

**Comment by Atroc-0625** [comment]
<img width="661" alt="WX20191022-093244@2x" src="https://user-images.githubusercontent.com/37469514/67254310-f1d0f180-f4ae-11e9-89eb-cf7209030f2d.png">

**Comment by nrlquaker** [comment]
Seems like you didn't install dependencies. Did you use `brew cask` to install?

**Comment by Atroc-0625** [comment]
> 好像您没有安装依赖项。您`brew cask`用来安装吗？

Which dependencies need to be installed

**Comment by nrlquaker** [comment]
Check [installation](https://github.com/nrlquaker/winbox-mac#installation) in readme.

**Comment by Atroc-0625** [comment]
> 在自述文件中检查[安装](https://github.com/nrlquaker/winbox-mac#installation)。

brew install Freetype and XQuartz ???

**Comment by nrlquaker** [comment]
```
brew install freetype
brew cask install xquartz
```
or
`brew cask install nrlquaker-winbox`

**Comment by Atroc-0625** [comment]
> ```
> brew install freetype
> brew cask install xquartz
> ```
> 
> or
> `brew cask install nrlquaker-winbox`
Already installed dependencies, can't open now

**Comment by Atroc-0625** [comment]
> > ```
> > brew install freetype
> > brew cask install xquartz
> > ```
> > 
> > 
> > or
> > `brew cask install nrlquaker-winbox`
> > Already installed dependencies, can't open now

atroc@Atroc-MacBook-Pro ~ % brew cask install nrlquaker-winbox
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Installing Cask dependencies: xquartz
==> Satisfying dependencies
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/atroc/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Verifying SHA-256 checksum for Cask 'xquartz'.
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
installer: Package name is XQuartz 2.7.11
installer: Installing at base path /
installer: The install was successful.
🍺  xquartz was successfully installed!
==> Downloading https://github.com/nrlquaker/winbox-mac/releases/download/v3.20/
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'nrlquaker-winbox'.
==> Installing Cask nrlquaker-winbox
==> Moving App 'Winbox-mac.app' to '/Applications/Winbox-mac.app'.
🍺  nrlquaker-winbox was successfully installed!
atroc@Atroc-MacBook-Pro ~ %

**Comment by 1o1o1** [comment]
brew install libpng
:)

**Comment by Atroc-0625** [comment]
> brew install libpng
> :)

atroc@Atroc-MacBook-Pro ~ % brew list
freetype	git		mtr		tcping
gettext		libpng		pcre2
atroc@Atroc-MacBook-Pro ~ %

**Comment by 1o1o1** [comment]
reinstall

**Comment by Atroc-0625** [comment]
> reinstall

atroc@Atroc-MacBook-Pro ~ % brew cask install nrlquaker-winbox
==> Satisfying dependencies
==> Installing Formula dependencies: freetype
==> Installing dependencies for freetype: libpng
==> Installing freetype dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.37.catalina.bott
Already downloaded: /Users/atroc/Library/Caches/Homebrew/downloads/c6068aecd9940e8c341aca2bfebe2b9ae0aa7e54c0b0cdd606b1b0d3c0d764eb--libpng-1.6.37.catalina.bottle.tar.gz
==> Pouring libpng-1.6.37.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.37: 27 files, 1.2MB
==> Installing freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.10.1.catalina.bo
Already downloaded: /Users/atroc/Library/Caches/Homebrew/downloads/95d06c9193535a90157efef36a78f373d2a1a697235d9a46f93d2d0cafe44643--freetype-2.10.1.catalina.bottle.tar.gz
==> Pouring freetype-2.10.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.10.1: 61 files, 2.2MB
==> Installing Cask dependencies: xquartz
==> Satisfying dependencies
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/atroc/Library/Caches/Homebrew/downloads/91b9d0c82398ac57be33a52922d5ed21ddf4b747516e70738f5ec6a2a9944d0c--XQuartz-2.7.11.dmg
==> Verifying SHA-256 checksum for Cask 'xquartz'.
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
installer: Package name is XQuartz 2.7.11
installer: Installing at base path /
installer: The install was successful.
🍺  xquartz was successfully installed!
==> Downloading https://github.com/nrlquaker/winbox-mac/releases/download/v3.20/
Already downloaded: /Users/atroc/Library/Caches/Homebrew/downloads/8f353638e794f30ee1fbdd51362e58a13f314c136fddc33fe9f880e56e2bf2bf--Winbox-mac-3.20.zip
==> Verifying SHA-256 checksum for Cask 'nrlquaker-winbox'.
==> Installing Cask nrlquaker-winbox
==> Moving App 'Winbox-mac.app' to '/Applications/Winbox-mac.app'.
🍺  nrlquaker-winbox was successfully installed!
atroc@Atroc-MacBook-Pro ~ % 
Launch immediately after opening

**Comment by nrlquaker** [comment]
Have you allowed winbox-mac and winbox64.exe to be opened?

**Comment by Atroc-0625** [comment]
> 您是否允许打开winbox-mac和winbox64.exe？

Allowed there？

**Comment by Atroc-0625** [comment]
> Have you allowed winbox-mac and winbox64.exe to be opened?

<img width="305" alt="WX20191022-165422@2x" src="https://user-images.githubusercontent.com/37469514/67271183-9faec100-f4ec-11e9-9365-912aadf0627c.png">

**Comment by nrlquaker** [comment]
Run from terminal `/Applications/Winbox-mac.app/Contents/MacOS/startwine` and paste output here.

**Comment by Atroc-0625** [comment]
> Run from terminal `/Applications/Winbox-mac.app/Contents/MacOS/startwine` and paste output here.

atroc@Atroc-MacBook-Pro ~ % /Applications/Winbox-mac.app/Contents/MacOS/startwine
wine: failed to update /Users/atroc/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"dbghelp.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/dbghelp.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library dbghelp.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"WININET.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/wininet.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library WININET.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:attach_dlls Importing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000135
0039:err:module:attach_dlls "comctl32.dll" failed to initialize, aborting
0039:err:module:attach_dlls Initializing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000005
atroc@Atroc-MacBook-Pro ~ %

**Comment by nrlquaker** [comment]
What macOS is it?

**Comment by Atroc-0625** [comment]
> What macOS is it?

atroc@Atroc-MacBook-Pro ~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A602
atroc@Atroc-MacBook-Pro ~ %

**Comment by 1o1o1** [comment]
And Wine version is 32 bits?

**Comment by Atroc-0625** [comment]
> 而且Wine版本是32位？

I did not install Wine

**Comment by Vovanys** [comment]
Try **brew cask reinstall nrlquaker-winbox**
It helped me

**Comment by nrlquaker** [comment]
Just tried installing it using brew on the VM with Catalina.
Works fine.

**Comment by Atroc-0625** [comment]
> Just tried installing it using brew on the VM with Catalina.
> Works fine.

What is your operation procedure?

**Comment by nrlquaker** [comment]
Install Homebrew:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
Install Winbox-mac:
`brew cask install nrlquaker-winbox`
Thats all.

**Comment by Atroc-0625** [comment]
> Install Homebrew:
> `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
> Install Winbox-mac:
> `brew cask install nrlquaker-winbox`
> Thats all.

Reload Homebrew  nrlquaker-winbox
Still can't use

**Comment by Atroc-0625** [comment]
> Install Homebrew:
> `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
> Install Winbox-mac:
> `brew cask install nrlquaker-winbox`
> Thats all.

Need to install Wine ？

**Comment by nrlquaker** [comment]
No, its bundled inside the app.

**Comment by Atroc-0625** [comment]
> No, its bundled inside the app.

Is there any way to deal with my problem?

**Comment by nrlquaker** [comment]
Sorry, but I don't understand the cause of the problem. I can only advice to try to run in the the newly created VM. If its runs ok then there is something in your system causing this issue (different version of freetype or smth).
You can use Parallels trial to test.

**Comment by Doublemine** [comment]
> Run from terminal `/Applications/Winbox-mac.app/Contents/MacOS/startwine` and paste output here.

```bash

```

**Comment by Doublemine** [comment]
Same problem to me.

------
#### Describe the bug
No windows out, it just disappears.

#### To Reproduce
Steps to reproduce the behavior:

 - Open it
 - Click on "allow anyway" in security and privacy
 - The icon bounce...
 - See no error, then disappear

#### Install Method
`brew cask install nrlquaker-winbox`

#### OS Version

```bash
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A602
```
------
> Run from terminal /Applications/Winbox-mac.app/Contents/MacOS/startwine and paste output here.

Output as follow: 
```bash
wine: failed to update /Users/xxxx/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"dbghelp.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/dbghelp.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library dbghelp.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"WININET.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/wininet.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library WININET.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:attach_dlls Importing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000135
002a:err:module:attach_dlls "comctl32.dll" failed to initialize, aborting
002a:err:module:attach_dlls Initializing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000005
```

**Comment by Atroc-0625** [comment]
> Same problem to me.
> 
> #### Describe the bug
> No windows out, it just disappears.
> 
> #### To Reproduce
> Steps to reproduce the behavior:
> 
> * Open it
> * Click on "allow anyway" in security and privacy
> * The icon bounce...
> * See no error, then disappear
> 
> #### Install Method
> `brew cask install nrlquaker-winbox`
> 
> #### OS Version
> ```shell
> ProductName:	Mac OS X
> ProductVersion:	10.15
> BuildVersion:	19A602
> ```
> 
> > Run from terminal /Applications/Winbox-mac.app/Contents/MacOS/startwine and paste output here.
> 
> Output as follow:
> 
> ```shell
> wine: failed to update /Users/xxxx/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
> 0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.
> 0009:err:module:load_builtin_dll failed to load .so lib for builtin L"dbghelp.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/dbghelp.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
>   Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
> 0009:err:module:import_dll Loading library dbghelp.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
> 0009:err:module:load_builtin_dll failed to load .so lib for builtin L"WININET.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/wininet.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
>   Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
> 0009:err:module:import_dll Loading library WININET.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
> 0009:err:module:attach_dlls Importing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000135
> 002a:err:module:attach_dlls "comctl32.dll" failed to initialize, aborting
> 002a:err:module:attach_dlls Initializing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000005
> ```

I am the same problem

**Comment by luccaccine** [comment]
i think these point problems just appears in system that already modified by other softwares, changing this kinds of libs, or paths, or something like this...

i run `brew cask install nrlquaker-winbox` on three macs, and had no problem. one of them, had a clean install.

**Comment by luccaccine** [comment]
oh, wait! 

mine have theses errors too, but works fine:

```
000b:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
000f:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
000d:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
0012:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
Fontconfig warning: ignoring UTF-8: not a valid region tag
001a:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
001f:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
Fontconfig warning: ignoring UTF-8: not a valid region tag
0024:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
Fontconfig warning: ignoring UTF-8: not a valid region tag
wine: failed to update /Users/lucasdelucca/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.
Fontconfig warning: ignoring UTF-8: not a valid region tag
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"dbghelp.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/dbghelp.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library dbghelp.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"WININET.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/wininet.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library WININET.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:attach_dlls Importing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000135
002a:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 17/02/2019, dlt (d/m/y): 31/12/2019
002a:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
creating Window Class routeros_null
creating Window Class routeros_connect
creating Window Class routeros_dbl_canvas
loadConfig C:\users\lucasdelucca\Application Data\Mikrotik\Winbox\Addresses.cdb
```

**Comment by nrlquaker** [comment]
Close in favour of #16. Both got the same problem.
