### ISSUE TITLE
resolution stuck on small window

### ISSUE THREAD

**Issue by markbza** [nrlquaker/winbox-mac#121]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Sometimes when I start the app on my Macbook pro M2 (arm64) the window starts up really small and cannot be resized I have to restarted it few times before it works

**To Reproduce**
Start of application

**Expected behavior**
Ability to be able to resize window

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5]    13.2.1 (22D68)
 - macOS language [e.g. English, Russian, Chinese]      English
 - Winbox-mac version [e.g. 3.18]      Winbox-mac-3.38.0
 - Winbox version [e.g. 3.18]    3.37

**Additional context**

**Comment by luqmanmahama** [comment]
Restart in an empty desktop i.e. where no other windows are open and it starts fine.

**Comment by nrlquaker** [comment]
Please use latest `winbox-mac`. It has wine updated.

**Comment by markbza** [comment]
Warning: Not upgrading nrlquaker-winbox, the latest version is already installed

Am using winbox 3.38 and Winbox-mac-3.38.0 .. I tried to reinstall but same result

**Comment by nrlquaker** [comment]
I don't understand what you are saying.
I'm waiting for the new wine build. Think it will fix it.
