### ISSUE TITLE
Doesn't work on M1 Mac

### ISSUE THREAD

**Issue by ErikThiart** [nrlquaker/winbox-mac#123]
```
==> Installing Cask nrlquaker-winbox
==> Moving App 'Winbox-mac.app' to '/Applications/Winbox-mac.app'
🍺  nrlquaker-winbox was successfully installed!
```

![CleanShot 2023-07-05 at 11  26 28@2x](https://github.com/nrlquaker/winbox-mac/assets/9626641/abbe7ede-4e33-44d4-b8ad-8b7aff1415c3)

**Comment by nrlquaker** [comment]
Try install using `--no-quarantine` flag. Or right click open, allow.

**Comment by ErikThiart** [comment]
Nope. same issue.
