### ISSUE TITLE
Virustotal report

### ISSUE THREAD

**Issue by InfinityMe** [nrlquaker/winbox-mac#125]
https://www.virustotal.com/gui/file/937b5ca3a76207b7ee58d7f02578e3915aa489c9bf906f6c69fcc92e1e6f4a70?nocache=1

 - Winbox-mac version 3.39
File Winbox-mac-3.39.0.zip
Latest archive downloaded from GitHub.

**Comment by nrlquaker** [comment]
Most likely its false positive.
