### ISSUE TITLE
Does not work in macOS Ventura 13.5.2

### ISSUE THREAD

**Issue by arispati** [nrlquaker/winbox-mac#127]
**Checklist**

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
I can open the App but can't click input & button in the app, can't close or quit

**To Reproduce**
1. Installing the latest winbox-mac according to the instructions in the documentation
2. Open the winbox-mac
3. The app opened but I can't do anything, can't input and click any button, and also can't quit the app

**Expected behavior**
The application runs normally, can input and click button and quit the app

**Desktop (please complete the following information):**
 - macOS version: Ventura 13.5.2
 - macOS language: English
 - Winbox-mac version: 3.39
 - Winbox version: 3.39

https://github.com/nrlquaker/winbox-mac/assets/13604647/b064b160-cdfa-446b-a3a8-90a04d65d33c

**Comment by belthesar** [comment]
This sounds pretty similar to #126. Have a look at the things tried / workaround provided in there, and see if it helps. Would be interesting to know if this is actually specific to 13.5.2, or a resurfacing of this bug.

**Comment by ipearx** [comment]
I do find force quit the app, then opening it again a few times it will eventually work as expected. When it doesn't work, it behaves exactly the same as the above, can't click on anything. On a m2 Macbook Pro 16" with Ventura 13.5
I also note the app keeps bounce loading in the dock.

**Comment by arispati** [comment]
> This sounds pretty similar to #126. Have a look at the things tried / workaround provided in there, and see if it helps. Would be interesting to know if this is actually specific to 13.5.2, or a resurfacing of this bug.

hi @belthesar , I have implemented the method you provided to change on line 19, and now it is working. thank you

**Comment by arispati** [comment]
I'll close this issue, thank you

**Comment by michaldejmek** [comment]
You need to delete the application completely (~/Library/Application Support/com.mikrotik.winbox)and reload the device list and everything works as it should :)
