### ISSUE TITLE
Interested in becoming a maintainer

### ISSUE THREAD

**Issue by belthesar** [nrlquaker/winbox-mac#128]
Hi there - I'm a somewhat seasoned WINE user, most recently when I was daily driving Linux as my primary OS, and before then a heavy user of Wineskin Winery to build self-contained wrappers. I'm back to using macOS for the time being ever since getting Apple Silicon hardware, and I also run Mikrotik hardware in my home and work networks. I wouldn't mind learning what it takes to maintain the wrapper, since it's a valuable piece of my network administration workflow, and I have a handful of other Win32 tools that I'd like to build streamlined wrappers for that would help me in my life, so I'd have reason to learn how to make things work from that aspect.

**Comment by nrlquaker** [comment]
@belthesar hi. Thanks for the interest in becoming a maintainer. Please check your email.
