### ISSUE TITLE
When clicking it, it just disappear. 

### ISSUE THREAD

**Issue by xh116** [nrlquaker/winbox-mac#13]
**Describe the bug**
No windows out, it just disappear. 

**To Reproduce**
1. Open it
2. Click on "allow anyway" in security and privacy
3. The icon bounce...
4. See no error, then disappear 

**Expected behavior**
it should show a winbox window

**Screenshots**
 
<img width="1313" alt="WX20191022-124034@2x" src="https://user-images.githubusercontent.com/37950502/67259699-da533200-f4c9-11e9-9df1-6c4bcc4bbf0b.png">

**Desktop (please complete the following information):**
 - macOS version:10.15 (19A602)
 - Winbox-mac version 3.20

**Comment by nrlquaker** [comment]
Did you install from `brew cask` or downloaded from releases?

**Comment by xh116** [comment]
> from

I download from the releases.
should I install from homebrew ?

**Comment by nrlquaker** [comment]
Installing from `brew cask` installs dependencies automatically. Check [readme](https://github.com/nrlquaker/winbox-mac#installation).

**Comment by xh116** [comment]
> Installing from `brew cask` installs dependencies automatically. Check [readme](https://github.com/nrlquaker/winbox-mac#installation).

![image](https://user-images.githubusercontent.com/37950502/67267672-5dce4c80-f4e5-11e9-9ace-d5faf43ffc05.png)
<img width="1125" alt="WX20191022-160330@2x" src="https://user-images.githubusercontent.com/37950502/67267736-81919280-f4e5-11e9-9227-255c3bb87d87.png">
Working like a charm! I missed xquartz. I thought it was the same as before...

**Comment by nrlquaker** [comment]
You are welcome @xh116.
