### ISSUE TITLE
Bigger font size

### ISSUE THREAD

**Issue by gavalierm** [nrlquaker/winbox-mac#132]
Hello there,

it is possible to change font size? On my Macbook is font so tiny that is very hard to read for me.

Thank you.

**Comment by ZPrimed** [comment]
You should be able to use ctrl + (or possibly ctrl =) to increase font size inside of Winbox...

But even at the max font size it can be pretty small if you are not using the "standard" resolution of the Mac and have it downscaled to get more screen space.  I have a 16" MBP and set it to "More Space" instead of Default under displays, and at the maximum size in Winbox, it's readable for me... as long as I'm not too tired 😛 

I'd love to know if there is any way to get Wine to upscale better/more myself.

**Comment by gavalierm** [comment]
I m using "1728x1117" resolution which is marked as "default"

I have zoom to max.

And my biggest issue is that font is "lightweight" and is very hard to see Terminal stuff. Is so small and so lightweigt that narrow text on the white background of terminal is useless...

ctrl+= not working.

**Comment by ZPrimed** [comment]
Sorry, ctrl+= is just the hotkey for Tools > Zoom In on Winbox, so if you already maxxed that out then it won't do anything.

I'm at 2056x1329... 

I agree with you that the terminal is the worst part, too. Sometimes I just SSH to the router instead if I know i'm going to do a lot of terminal work.

I don't know if it's possible to fix this. I'd be OK with some sort of scaling happening on the Mac side, and hopefully then I could actually turn *down* the "Zoom" in Winbox.

**Comment by belthesar** [comment]
It's possible adjusting the DPI scaling for the WINE prefix might work for you. Currently, this is unsupported, but you can customize the WINE prefix's DPI Scaling with the `winecfg` utility. 

You can try using this script inside of a terminal to open up `winecfg` and adjust the DPI under the graphics setting. Open up Winbox-mac first, then paste this script into your terminal. 

``` 
BUNDLE_ID="com.mikrotik.winbox"
BUNDLERESOURCEPATH="$(osascript -e 'tell application "System Events" to POSIX path of (file of process "Winbox-mac" as alias)')/Contents/Resources"

export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG="fixme-esync"

export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_ID}"

cd "$BUNDLERESOURCEPATH"
"$BUNDLERESOURCEPATH/wine/bin/wine64" winecfg
```
You're looking to adjust the "Screen Resolution (DPI Setting)" under the Graphics tab. Please note that adjusting this setting might cause things to not render right. We can't support this without more testing. In the future, we might see about making this easier if we can get some time to test what DPI settings work okay with Winbox.

**Comment by gavalierm** [comment]
It works: Almost.

Top bar: File, Tools are bigger, but inside the window - actualy winbox is still the same size.

**Comment by gavalierm** [comment]
<img width="171" alt="Snímka obrazovky 2023-10-25 o 20 55 37" src="https://github.com/nrlquaker/winbox-mac/assets/17672623/e9cbf3e6-7e70-4e7b-b671-ccf84275a7a5">

**Comment by belthesar** [comment]
Unfortunately there may not be anything we can do in this case. WinBox
is far from the most accessible application on the planet. I’ll look
around to see if there are better suggestions that we could implement.
If you find anyone who has success with getting it to display reasonably
on Linux with HiDPI, that’d definitely clue us into the right
direction.

**Comment by gavalierm** [comment]
Thank you guys. Is not that much important for me. I change resolution if will be problematic.

**Comment by belthesar** [comment]
I'm going to close this issue for now. If other folks have interest or desire to look into this, feel free to reopen the issue, and I can investigate.
