### ISSUE TITLE
Extension for Remote Desktop Manager

### ISSUE THREAD

**Issue by baxenko** [nrlquaker/winbox-mac#134]
Hi. Is it possible to integrate your winbox for macos program for Remote Desktop Manager? As it is done in Windows. 

I have created a thread on the forum and I am asked about the details of the program interaction, maybe you can help with this. Thanks.

https://forum.devolutions.net/topics/40290/no-winbox-extension-for-macos

**Comment by xfortin-devolutions** [comment]
Hi,

If I can add context. We mainly want to know if the winbox-mac client supports means of third party communication. The Winbox client for Windows supports being launched from the command line by passing username, password and other parameters.

We'd want to know if something like this is possible for winbox-mac. In which case, Devolutions would do the integration on our side.

**Comment by nrlquaker** [comment]
https://github.com/nrlquaker/winbox-mac?tab=readme-ov-file#command-line-argumentsv

**Comment by xfortin-devolutions** [comment]
Oh! Thanks for that! You can close the ticket.
