### ISSUE TITLE
Fresh Install Damaged and can't be opened

### ISSUE THREAD

**Issue by kubert96** [nrlquaker/winbox-mac#135]
**Describe the bug**
Instaled winbox with brew: 

**To Reproduce**

13:43:42:Rmihalik-MacPro:~$ brew install --cask nrlquaker-winbox
==> Downloading https://github.com/nrlquaker/winbox-mac/releases/download/v3.39.0/Winbox-mac-3.39.0.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/106710073/9d20b752-095d-4b64-8c9a-57460c0a1559?X-Amz-Algorith
######################################################################################################################################################## 100.0%
==> Installing Cask nrlquaker-winbox
==> Moving App 'Winbox-mac.app' to '/Applications/Winbox-mac.app'
🍺  nrlquaker-winbox was successfully installed!

**Expected behavior**
App Lunch :D 

**Screenshots**
<img width="264" alt="Screenshot 2023-11-08 at 13 44 24" src="https://github.com/nrlquaker/winbox-mac/assets/68554211/fe3df550-d6a1-46f0-9492-eea134b0e1ef">
]

**Desktop (please complete the following information):**
 - macOS version: Sonoma 14.1 (23B74)
 - macOS language  English

 - Winbox-mac version v3.39.0

**Comment by nrlquaker** [comment]
Either follow instructions [here](https://support.apple.com/en-us/HT202491)
or install with `--no-quarantine` like this: `brew install --no-quarantine nrlquaker-winbox`

**Comment by kubert96** [comment]
OK this works but cant click on anything like app is stucked. But i see that that problem is alredy worked on. So closing. 
Thanks.
