### ISSUE TITLE
Update to winbox 3.40

### ISSUE THREAD

**Issue by gkl1368** [nrlquaker/winbox-mac#136]
Please update winbox to 3.40. Thanks

**Comment by emeykey-git** [comment]
I join. Please update.

**Comment by benbgg** [comment]
Is there a way of accessing the 3.40 update via brew or do I have to do it via Git?

**Comment by nrlquaker** [comment]
Updated to v3.40. Get it from [Releases](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.40.0) or wait for this [PR](https://github.com/Homebrew/homebrew-cask/pull/160504) to be merge if you use `brew`.
