### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by chinaamerica** [nrlquaker/winbox-mac#14]
The font is ugly. How can I solve it?

<img width="666" alt="截屏2019-10-23上午2 40 15" src="https://user-images.githubusercontent.com/655135/67318818-90586380-f53e-11e9-85d3-573aa6757ae0.png">

**Comment by nrlquaker** [comment]
Do you mean font smoothing doesn't work? Or are you talking about bold "1"?

**Comment by luccaccine** [comment]
maybe your dependencies are outdated.
wine relies freetype and xquartz. maybe you already have it in your computer, and when you had run `brew cask install nrlquaker-winbox`, it just download the `Winbox-mac`, and doesn't updated the dependencies.

try
``` shell
brew cleanup
brew update
brew upgrade # WARN: this updates all your brew formulas
brew cask upgrade # WARN: this updates all your brew casks
```

you can upgrade brew formulas individually, but i don't know if it will update the dependencies that the formula relies.

no idea if the your problem will be solved by this.

**Comment by chinaamerica** [comment]
> Do you mean font smoothing doesn't work? Or are you talking about bold "1"?

Both of them. "1" is bold, other words are also very strange.

**Comment by chinaamerica** [comment]
> maybe your dependencies are outdated.
> wine relies freetype and xquartz. maybe you already have it in your computer, and when you had run `brew cask install nrlquaker-winbox`, it just download the `Winbox-mac`, and doesn't updated the dependencies.
> 
> try
> 
> ```shell
> brew cleanup
> brew update
> brew upgrade # WARN: this updates all your brew formulas
> brew cask upgrade # WARN: this updates all your brew casks
> ```
> 
> you can upgrade brew formulas individually, but i don't know if it will update the dependencies that the formula relies.
> 
> no idea if the your problem will be solved by this.

The commands are executed, and the problem seems to be still there.

version:
XQuartz-2.7.11
freetype-2.10.1

**Comment by chinaamerica** [comment]
> Do you mean font smoothing doesn't work? Or are you talking about bold "1"?

barryng@BarryNgdeMacBook-Pro ~ % /Applications/Winbox-mac.app/Contents/MacOS/startwine
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.
Fontconfig warning: ignoring UTF-8: not a valid region tag
Wine cannot find the ncurses library (libncurses.5.4.dylib).
Fontconfig warning: ignoring UTF-8: not a valid region tag
0009:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
creating Window Class routeros_null
creating Window Class routeros_connect
creating Window Class routeros_dbl_canvas
loadConfig C:\users\barryng\Application Data\Mikrotik\Winbox\Addresses.cdb

**Comment by luccaccine** [comment]
🤔

same erros here:
•`Fontconfig warning: ignoring UTF-8: not a valid region tag`
• `0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.`
• `002a:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption`

just don't have this error in mine:
• `Wine cannot find the ncurses library (libncurses.5.4.dylib).`

`libncurses.5.4.dylib` lives in `/usr/lib`.

please, run:
```
ls -la /usr/lib | grep libncurses
```

check your output.

mine is:

```
❯ l | grep libncurses
lrwxr-xr-x    1 root  wheel    20B Oct  9 17:52 libcurses.dylib -> libncurses.5.4.dylib
-rwxr-xr-x    1 root  wheel   262K Sep 29 17:28 libncurses.5.4.dylib
lrwxr-xr-x    1 root  wheel    20B Oct  9 17:52 libncurses.5.dylib -> libncurses.5.4.dylib
lrwxr-xr-x    1 root  wheel    20B Oct  9 17:52 libncurses.dylib -> libncurses.5.4.dylib
lrwxr-xr-x    1 root  wheel    20B Oct  9 17:52 libtermcap.dylib -> libncurses.5.4.dylib
```

i tried to remove `libncurses.5.4.dylib` from my computer to see if my winbox looks like yours, but i couldn't:
```
root in /usr/lib  
❯ mv libncurses.5.4.dylib libncurses.5.4.dylib.bak
mv: rename libncurses.5.4.dylib to libncurses.5.4.dylib.bak: Operation not permitted
```
maybe should i disable `System Integrity Protection`

**Comment by luccaccine** [comment]
looks a problem with env var `DYLD_FALLBACK_LIBRARY_PATH` or with the directories that this var points to.
this missing var was the responsible for winbox don't render any fonts at issue #11 

now, this var points to: `/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"`
have three paths, because it's a fallback. try first, don't found, try second, go on...

[source](https://superuser.com/questions/549331/mac-macports-wine-errors-ncurses-library-and-fontconfig?answertab=active#tab-top)

i opened the `/Applications/Winbox-mac.app/Contents/MacOS/startwine` on editor, changed the penultimate line to: `DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"` and i got my font almost like yours (aliased):

<img width="773" alt="Screen Shot 2019-10-23 at 16 38 14" src="https://user-images.githubusercontent.com/8313551/67428407-7194b400-f5b4-11e9-8427-a4e0e95256fb.png">

**Comment by luccaccine** [comment]
> > maybe your dependencies are outdated.
> > wine relies freetype and xquartz. maybe you already have it in your computer, and when you had run `brew cask install nrlquaker-winbox`, it just download the `Winbox-mac`, and doesn't updated the dependencies.
> > try
> > ```shell
> > brew cleanup
> > brew update
> > brew upgrade # WARN: this updates all your brew formulas
> > brew cask upgrade # WARN: this updates all your brew casks
> > ```
> > 
> > 
> > you can upgrade brew formulas individually, but i don't know if it will update the dependencies that the formula relies.
> > no idea if the your problem will be solved by this.
> 
> The commands are executed, and the problem seems to be still there.
> 
> version:
> XQuartz-2.7.11
> freetype-2.10.1

```
brew info libpng 
```

libpng: stable 1.6.37 ???

**Comment by chinaamerica** [comment]
> brew info libpng
libpng: stable 1.6.37 (bottled), HEAD

barryng@BarryNgdeMacBook-Pro ncurses % brew info libpng
libpng: stable 1.6.37 (bottled), HEAD
Library for manipulating PNG images
http://www.libpng.org/pub/png/libpng.html
/usr/local/Cellar/libpng/1.6.37 (27 files, 1.2MB) *
  Poured from bottle on 2019-10-23 at 02:09:54
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git/Formula/libpng.rb
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 159,158 (30 days), 456,982 (90 days), 2,175,994 (365 days)
install_on_request: 6,884 (30 days), 23,639 (90 days), 111,254 (365 days)
build_error: 0 (30 days)

**Comment by chinaamerica** [comment]
Edit startwine,add "export LC_CTYPE="en_US.UTF-8" 
<img width="402" alt="截屏2019-10-24下午12 26 05" src="https://user-images.githubusercontent.com/655135/67453512-76f80a00-f659-11e9-835e-93221c7a9bee.png">

There was a strange situation：winbox in one click open twice.(after first window close,auto open winbox again),but second winbox font is ok...

first:
<img width="672" alt="截屏2019-10-24下午12 28 24" src="https://user-images.githubusercontent.com/655135/67453624-cf2f0c00-f659-11e9-9310-b69b29a75c3c.png">

second(when close first, auto open ):
<img width="672" alt="截屏2019-10-24下午12 29 36" src="https://user-images.githubusercontent.com/655135/67453678-01406e00-f65a-11e9-90a4-4ef4e82560a9.png">

if dont add "export LC_CTYPE="en_US.UTF-8", Winbox is the same as before：
<img width="668" alt="截屏2019-10-24下午12 31 14" src="https://user-images.githubusercontent.com/655135/67453748-3baa0b00-f65a-11e9-9ff1-6bf66b692b47.png">

**Comment by luccaccine** [comment]
this a lot confusing!

after I add `export LC_CTYPE="en_US.UTF-8"`, the error `fontconfig warning: ignoring UTF-8: not a valid region tag` gone. but this error didn't cause any problem on winbox in my mac.

the only difference between your log and mine is the `ncurses` lib error.

your error `Wine cannot find the ncurses library (libncurses.5.4.dylib)` remains?

**Comment by chinaamerica** [comment]
> this a lot confusing!
> 
> after I add `export LC_CTYPE="en_US.UTF-8"`, the error `fontconfig warning: ignoring UTF-8: not a valid region tag` gone. but this error didn't cause any problem on winbox in my mac.
> 
> the only difference between your log and mine is the `ncurses` lib error.
> 
> your error `Wine cannot find the ncurses library (libncurses.5.4.dylib)` remains?

yes, still remains.

barryng@BarryNgdeMacBook-Pro ~ % /Applications/Winbox-mac.app/Contents/MacOS/startwine
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
wine: failed to update /Users/barryng/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.
Fontconfig warning: ignoring UTF-8: not a valid region tag
**Wine cannot find the ncurses library (libncurses.5.4.dylib).**
Fontconfig warning: ignoring UTF-8: not a valid region tag
0009:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
creating Window Class routeros_null
creating Window Class routeros_connect
creating Window Class routeros_dbl_canvas
loadConfig C:\users\barryng\Application Data\Mikrotik\Winbox\Addresses.cdb

**Comment by luccaccine** [comment]
i changed the `LC_CTYPE` to `export LC_CTYPE="whatever"`, and it keeps working, just change the error to: `Fontconfig warning: ignoring whatever: not a valid language tag`;

reading [this](https://superuser.com/questions/549331/mac-macports-wine-errors-ncurses-library-and-fontconfig?answertab=active#tab-top), have some ideas, but not sure if it'll work.

if you try this ideas, check after each one if it worked.

idea 1: download ncurses through homebrew:  `brew install ncurses`.

idea 2: create a symbolic link of `/usr/lib/libncurses.5.4.dylib` to `/usr/X11/lib`:
```
sudo zsh
ln -s /usr/lib/libncurses.5.4.dylib /usr/X11/lib/libncurses.5.4.dylib
```

idea 3: add a path to `libncurses.5.4.dylib` original home.
inside `/Applications/Winbox-mac.app/Contents/MacOS/startwine`, change the penultimate line to:
```
DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib:/usr/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"
```
and vice-versa:
```
DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"
```

idea 4: comment the line of idea 3.
```
# DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"
```

**Comment by luccaccine** [comment]
when i applied the idea 3 to mine, the behaviour is same yours.

first, it opens with ugly font. when closes, it auto opens, and looks normal.

**Comment by chinaamerica** [comment]
> when i applied the idea 3 to mine, the behaviour is same yours.
> 
> first, it opens with ugly font. when closes, it auto opens, and looks normal.

When I try idea 2 , no libncurses.5.4.dylib error, but the font still ugly.

barryng@BarryNgdeMacBook-Pro ~ % /Applications/Winbox-mac.app/Contents/MacOS/startwine
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
wine: failed to update /Users/barryng/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
0025:err:plugplay:runloop_thread Couldn't open IOHIDManager.
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
0009:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
creating Window Class routeros_null
creating Window Class routeros_connect
creating Window Class routeros_dbl_canvas
loadConfig C:\users\barryng\Application Data\Mikrotik\Winbox\Addresses.cdb

**Comment by luccaccine** [comment]
reading [this](https://forum.mikrotik.com/viewtopic.php?f=2&t=152795&p=754827#p754824)

can you change you `startwine` file as follow?

```
#!/bin/zsh

export FREETYPE_PROPERTIES="truetype:interpreter-version=35"
export DYLD_FALLBACK_LIBRARY_PATH="/usr/lib:/opt/X11/lib:$DYLD_FALLBACK_LIBRARY_PATH"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

if [ -f "$BUNDLERESOURCEPATH/Wine.app/Contents/Resources/bin/wine64" ]; then
    export WINEUSRPATH="$BUNDLERESOURCEPATH/Wine.app/Contents/Resources"
fi

export WINEPREFIX="$HOME/Library/Application Support/$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleIdentifier)"
if [ ! -d "$WINEPREFIX" ]; then
    "$BUNDLERESOURCEPATH/Winetricks.app/Contents/MacOS/./Winetricks" "$BUNDLERESOURCEPATH/wineprefix" "$WINEPREFIX" "$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleName)" "WINEARCH=win64"
fi

#some default windows vars that might be missing ( http://ss64.com/nt/syntax-variables.html )
[ -z "$COMPUTERNAME" ] && export COMPUTERNAME="$(/usr/sbin/scutil --get ComputerName)"

# start wine and program, if possible in the programs root directory, change to forwardslashes
BIN_FILE="$(sed 's|\\|/|g' <<< "C:/winebottler/winbox64.exe")"
BIN_PATH="$BUNDLERESOURCEPATH/wineprefix/drive_c$(sed 's|C:||' <<< "$(dirname "$BIN_FILE")")"
if [ -d "$BIN_PATH" ]; then
    cd "$BIN_PATH"
fi

# DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib:/usr/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"

"$WINEUSRPATH/bin/wine64" "$BIN_FILE"
```

this added `export FREETYPE_PROPERTIES="truetype:interpreter-version=35"` and changed the `DYLD_FALLBACK_LIBRARY_PATH` path.

what happened?

**Comment by chinaamerica** [comment]
wow，it work for me! thanks!
my `startwine` file：

```
#!/bin/bash
#export LC_CTYPE="en_US.UTF-8"
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

if [ -f "$BUNDLERESOURCEPATH/Wine.app/Contents/Resources/bin/wine64" ]; then
    export WINEUSRPATH="$BUNDLERESOURCEPATH/Wine.app/Contents/Resources"
fi

export WINEPREFIX="$HOME/Library/Application Support/$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleIdentifier)"
if [ ! -d "$WINEPREFIX" ]; then
    "$BUNDLERESOURCEPATH/Winetricks.app/Contents/MacOS/./Winetricks" "$BUNDLERESOURCEPATH/wineprefix" "$WINEPREFIX" "$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleName)" "WINEARCH=win64"
fi

#some default windows vars that might be missing ( http://ss64.com/nt/syntax-variables.html )
[ -z "$COMPUTERNAME" ] && export COMPUTERNAME="$(/usr/sbin/scutil --get ComputerName)"

BIN_FILE="C:/winebottler/winbox64.exe"
BIN_PATH="$BUNDLERESOURCEPATH/wineprefix/drive_c$(sed 's|C:||' <<< "$(dirname "$BIN_FILE")")"
if [ -d "$BIN_PATH" ]; then
    cd "$BIN_PATH"
fi

DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"
#DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:/usr/X11/lib "$WINEUSRPATH/bin/wine64" "$BIN_FILE"

"$WINEUSRPATH/bin/wine64" "$BIN_FILE"
```

![截屏2019-10-25上午10 08 19](https://user-images.githubusercontent.com/655135/67537769-6609d000-f70f-11e9-82bf-a46fb6b58f15.png)

**Comment by nrlquaker** [comment]
Please create PR for this.

**Comment by nrlquaker** [comment]
@chinaamerica does it fix the problem when you run app normally or only from terminal?

**Comment by chinaamerica** [comment]
> run app normally

Run app normally is ok.

**Comment by chinaamerica** [comment]
> @chinaamerica does it fix the problem when you run app normally or only from terminal?

Run app normally is ok.
