### ISSUE TITLE
Winbox-mac (Color-Shades of grey is now white)

### ISSUE THREAD

**Issue by s13mike91** [nrlquaker/winbox-mac#140]
**Checklist**

- [ *] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ *] I made sure this is not the original Winbox issue.

**Describe the bug**
A clear and concise description of what the bug is I have been running the "Winbox-mac" V3.38 back from when I was on my old Mac (mid 2014), which had the winbox with a grey shade (easy on the eyes). I've been on my new mac for about a year now, with the same winbox-mac v3.38 running the whole time with the traditional grey color that it's always been. Today I went to upgrade and now the winbox-mac app is now white I wouldn't mind it if it wasn't so harsh on the eyes, but I've wasted away 2-full workdays trying to figure this out. I tried rolling back to v3.38, and I even rolled back and installed the original V3.0 file I still have and still getting the same result. Much help would be extremely appreciated!

**To Reproduce**
1. Go to 'File Directory of where the "Wnbox-mac.app" file is located.
2. Click on Wnbox-mac.app
3. Scroll down to: when app opens, the app appears to be pretty white and no longer grey (refer to screen shots)

**Expected behavior**
A clear and concise description of what you expected to happen was the traditional windows grey of the winbox app

**Screenshots**
<img width="969" alt="Untitled" src="https://github.com/nrlquaker/winbox-mac/assets/155463255/fc3341f9-3d7b-4b51-b489-2a23f92d111a">
<img width="716" alt="Untitled-1" src="https://github.com/nrlquaker/winbox-mac/assets/155463255/a3ddb215-90cb-4d3a-9b8b-d54f7c3bf802">

**Desktop (please complete the following information):**
 - macOS version: 14.1.2 (23B92)
 - macOS language English
 - Winbox-mac version 3.40
 - Winbox version 3.40

**Additional context**

**Comment by belthesar** [comment]
This is a change upstream from Winbox and Mikrotik, and not a change that we have any control over unfortunately. Feedback should be upstreamed to Mikrotik if you preferred the old UI look.

**Comment by wmbin** [comment]
Disable the content in wine.inf
`HKCU,"Software\Microsoft\Windows\CurrentVersion\ThemeManager","DllName",2,"%10%\resources\themes\light\light.msstyles"`
