### ISSUE TITLE
Error: nrlquaker-winbox: It seems the App source

### ISSUE THREAD

**Issue by Delitants** [nrlquaker/winbox-mac#142]
brew upgrade --cask nrlquaker-winbox
==> Upgrading 1 outdated package:
nrlquaker-winbox 3.20.4 -> 3.40.0
==> Upgrading nrlquaker-winbox
==> Downloading https://github.com/nrlquaker/winbox-mac/releases/download/v3.40.0/Winbox-mac-3.40.0.zip
Already downloaded: /Users/neolo/Library/Caches/Homebrew/downloads/2b606d73dead260810b1c1e5fcdd597212283ad1b9a55679812a55fc1e3c9b73--Winbox-mac-3.40.0.zip
==> Purging files for version 3.40.0 of Cask nrlquaker-winbox
Error: nrlquaker-winbox: It seems the App source '/Applications/Winbox-mac.app' is not there.

**Comment by nrlquaker** [comment]
Not following [the template](https://github.com/nrlquaker/winbox-mac/issues/new?assignees=belthesar&labels=&projects=&template=bug_report.md&title=).
Not a `winbox-mac` issue.
Try [this](https://github.com/orgs/Homebrew/discussions/4232#discussioncomment-5015739) to fix it.
