### ISSUE TITLE
After third start Wine requested permission for full keystrokes collection / MacOS

### ISSUE THREAD

**Issue by f-dx** [nrlquaker/winbox-mac#146]
**Describe the bug**
Wine application requested extended permissions to collect keystrokes on MacOS (after third start).

**To Reproduce**
1. Start/Close the application 2 times
2. After the third run there's a standard request for extended permissions (macOS)

**Expected behavior**
The app should not collect key strokes. Possibly trojan/malware.

**Desktop:**
 - macOS version:  14.4 (23E214)
 - macOS language English
 - Winbox-mac version 3.40.1

**Comment by belthesar** [comment]
This is an artifact of Wine, and something outside of our control. Multiple Wine-wrapped applications that I use all request full keystroke collection. Nothing about our bundle specifically requests this permission. You are welcome to perform a more in-depth analysis if you so wish to see if there is any exfiltration, in which this should likely be reported to Wine upstream.
