### ISSUE TITLE
Upload/download files to/from device

### ISSUE THREAD

**Issue by Shev84** [nrlquaker/winbox-mac#15]
On MacOS Catalina I'm not able to upload any files to device via WinBox. I know that using 'Upload..." button cause freeze, but i thought that with 'paste' button it should be allowed to upload previously copied files. 
The same is for download. Are all options for transfering files via WinBox dropped for 64bit version?

**Comment by chinaamerica** [comment]
Just tested it, the upload function is ok. Sometime button freeze, try to restart winbox?

![upload_test](https://user-images.githubusercontent.com/655135/67498016-65425100-f6b1-11e9-8062-ec00cc289d8d.png)

**Comment by Shev84** [comment]
When I try to use 'copy' button I can see for a moment these new download window with transfer progress. But after it disappear, i can't paste file in Finder (there's no such option). Same with upload, if I copy file from Finder (CMD+C), using 'paste' button in 'file' window in WinBox does nothing. I start to think it's rather Wine problem, then Winbox itself. Where to get logs to debug it?
I've installed Winbox via brew (version 64bit 3.20).

**Comment by 1o1o1** [comment]
I confirm
same problem  :(

**Comment by nrlquaker** [comment]
Its [known issue](https://forum.mikrotik.com/viewtopic.php?f=2&t=152795&p=754827#p755159) and related to `Catalina` or `Wine64`. Don't think I am able to fix it.
