### ISSUE TITLE
MacOS Sonoma 14.6.1 (23G93), M1 chip. Winbox doesn't operate fluid

### ISSUE THREAD

**Issue by gabriel-gof** [nrlquaker/winbox-mac#150]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Sir, Winbox is extremely laggy. When I open a window inside it and try to move it, the interface becomes distorted. This doesn’t seem normal. If I use only Wine with the Winbox version from the MikroTik site, it works much better, but I lose the option to save Winbox to the dock. Something seems off.

**To Reproduce**
Install and open Winbox

**Expected behavior**
It should work fluid, at least the best that something emulated could be.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: 14.6.1
 - macOS language: English
 - Winbox-mac version: 3.40.1

**Additional context**
Maybe it is possible to give me an older version for me to test it?

**Comment by belthesar** [comment]
This sometimes happens when Winbox-mac starts up for the first time, and has happened for years. It also happens sometimes on Linux running through Wine. My best recommendation is to wait a little while after startup. This generally works for me.
