### ISSUE TITLE
Check for new winbox version with GitHub Actions workflow on a schedule

### ISSUE THREAD

**Issue by nrlquaker** [nrlquaker/winbox-mac#152]
**Is your feature request related to a problem? Please describe.**
Would be nice to check for new winbox version automatically not manually. 

**Describe the solution you'd like**
Check for new winbox version using cron on GitHub Actions. When new one is available create issue.

**Describe alternatives you've considered**
Do it manually.

**Additional context**
Run [cron job daily](https://jasonet.co/posts/scheduled-actions/) to check if new version is available.
We can use check_sha512 script for that.

**Comment by belthesar** [comment]
I've investigated this, and I've yet to come up with a good solution. Mikrotik does not offer an API, nor an RSS feed for Winbox updates. The only endpoints for automated update checking are centered around RouterOS channels. They don't even have support for SwOS (Lite). We could regularly download Winbox and check against a hash, but I wouldn't be surprised if with the recent changes to lock down their CDN they might detect regular download behavior from Azure as abuse and block it. Something I had considered however was to follow the redirects for https://mt.lv/winbox64, and wait until we hit a URL that contains `download.mikrotik.com`, which includes the latest version in the URL. Following the HTTP redirects would not trigger a full download unless we did a GET against that URL, so my hope is that it would have a much lower likelihood of getting blocked.

**Comment by nrlquaker** [comment]
Good idea.

**Comment by belthesar** [comment]
Feature: Create a Github Action to check for new Winbox versions 
 - Every day, check for new Winbox version
   - Parse `Info.plist` to extract Winbox version from Winbox-mac version (SemVer Major.Minor == Winbox version)
   - Use custom HTTP client to parse redirects from https://mt.lv/winbox64 to find the current version in the URL (eg: https://download.mikrotik.com/routeros/winbox/3.41/winbox64.exe == 3.41)
   - If version is different: 
     - Create an Issue for the version update
     - Create a branch for the version update
     - In the new branch, download the latest Winbox and run the version bump script
     - Update the issue that the branch is ready for manual Changelog updates. (Can't automate, as the only place that Mikrotik publishes Winbox changelogs seems to be on their forums)

**Comment by gkl1368** [comment]
Winbox has new 4.0 version with macos native support

**Comment by nrlquaker** [comment]
Just checked. All app is 82 mb bin file. Seems like they are using some kind of cross platform library.

**Comment by gkl1368** [comment]
> Just checked. All app is 82 mb bin file. Seems like they are using some kind of cross platform library.

The new version has nice UI.

**Comment by gkl1368** [comment]
> Just checked. All app is 82 mb bin file. Seems like they are using some kind of cross platform library.

it use QT

**Comment by gkl1368** [comment]
winbox has update to 4.0b3

**Comment by juanpedrojose** [comment]
> * Can't automate, as the only place that Mikrotik publishes Winbox changelogs seems to be on their forums

There is an rss feed for changelog: https://download.mikrotik.com/routeros/latest-stable.rss and the content looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>MikroTik RouterOS Stable releases</title>
    <link>https://mikrotik.com/download</link>
    <description>The newest MikroTik RouterOS releases.</description>
    <item>
      <title>RouterOS 7.15.3 [stable]</title>
      <link>https://mikrotik.com/download?v=7.15.3</link>
      <description></description>
      <content:encoded><![CDATA[What's new in 7.15.3 (2024-Jul-24 13:36):<br><br>*) lte - fixed possible crash when enabling/disabling config-less modem interface;<br>*) lte - fixed R11e-LTE no traffic flow when modem with older firmware version is used;<br>*) routerboard - improved Etherboot stability for CRS320-8P-8B-4S+ device ("/system routerboard upgrade" required); <br>*) ssh - fixed unsupported user SSH public key import (introduced in v7.15);]]></content:encoded>
      <guid isPermaLink="false">RouterOS 7.15.3 [stable]</guid>
      <pubDate>Thu, 25 Jul 2024 05:34:37 +0000</pubDate>
    </item>
  </channel>
</rss>
```

**Comment by belthesar** [comment]
Given that Winbox 4 is cross platform, and there are no indications of continued development on WInbox 3 going forward, I am going to close this issue. If Winbox 3 is going to be developed further, I will consider reopening this.
