### ISSUE TITLE
Multi sessione

### ISSUE THREAD

**Issue by cybersyx** [nrlquaker/winbox-mac#153]
Hi, it's possibile to add multisession ? Open more session of wine (winbox) ? Thanks !

**Comment by belthesar** [comment]
Hi @cybersyx - 

This is already possible, although the workflow is specific vs. how you might be used to doing it on Windows. With an active Winbox connection to a device running RouterOS, you should be able to click the New Winbox button to start another Winbox instance.

![image](https://github.com/user-attachments/assets/87ed358f-c1cb-4276-bce9-bcb6c60f7eb2)

All instances will live under the same Winbox-mac icon in your Dock. Window management is a bit of a bear (Winbox doesn't register Windows in a way that Wine on Mac detects) so unfortunately, using things like Command+` to cycle between Windows doesn't work. However, if you're accustom to using Mission Control / Exposé trackpad shortcuts, the individual windows will show up there and can be selected for easier navigation.
