### ISSUE TITLE
Official Native Client

### ISSUE THREAD

**Issue by septs** [nrlquaker/winbox-mac#154]
> Finally, the wait is over! Winbox 4 is here, now natively supporting Windows, MacOS, and Linux! 🎉​
>
> Windows: https://download.mikrotik.com/routeros/winbox/4.0beta1/WinBox_Windows.zip
> MacOS: https://download.mikrotik.com/routeros/winbox/4.0beta1/WinBox.dmg
> Linux: https://download.mikrotik.com/routeros/winbox/4.0beta1/WinBox_Linux.zip

from https://t.me/mikrotiksg/285

Suggent, Update to README

**Comment by amilus668** [comment]
Cool

**Comment by gkl1368** [comment]
wimbox has update to 4.0b3

**Comment by kubert96** [comment]
Ok sorry. But this is pointless now? I thinks. When it is native dng from Mikrotik.

I enjoy this project fo so long. But when winbox  4 come to production i think this is done project. 

Thanks creators and suporters. :)

**Comment by nrlquaker** [comment]
First of all the winbox 4 doesn't look native. It has 80 mb bin.
Second - the project will be supported as long as @belthesar will want to support it.
