### ISSUE TITLE
The neighbors are missing

### ISSUE THREAD

**Issue by posean** [nrlquaker/winbox-mac#156]
After update Mac OS upto 15 sequoia, neighbors are missing in main frame of winbox.
I can open only gateway mikrotik(i don't see him at neighbors in main frame before logging), but can't open any other in local network - IP\MAC - no. Other networks working good.
I try run winbox64.exe in wine - it works
I try run winbox 4beta for mac - it works(_but it request access to local network_) -- i think working new rules for privacy - i cant add same rule for this winbox-mac(no keys in privacy form)

<img width="1022" alt="Снимок экрана 2024-09-18 в 15 29 00" src="https://github.com/user-attachments/assets/110e6d84-3b86-4d56-997e-c8ab9ae1b800">

To Reproduce
You must run winbox-mac on macos 15.0(i found 4 devices with same trouble)

Expected behavior
Neighbors in main frame are visible and can be opened

Desktop:
 - macOS 15.0 Russian
 - Winbox-mac 3.41 (removed, cleaned and installed from "NULL" for repeat)
 - Winbox version 3.41(win64), 4.06beta(macos)

**Comment by belthesar** [comment]
I currently do not have a Sequoia system to test on yet, but based on your info, it sounds like we may need to update the entitlements we request. I'll have a look as soon as I get a system running with Sequoia (likely this weekend).

**Comment by posean** [comment]
links for thinks
https://developer.apple.com/forums/thread/663858
https://forums.developer.apple.com/forums/thread/760964

**Comment by thiagodamas** [comment]
Until fixes exist, try opening from the shell:
/Applications/Winbox-mac.app/Contents/MacOS/winbox-mac

**Comment by vseugene** [comment]
Unfortunately, I encountered the same problem. I will add a little to the author's problem. Among other things, when I normally launch WinBox, I can only connect to a remote Mikrotik with a white IP address. There is no way to connect to any router in the local network.
**Thiagodamas's** comment helped me launch WinBox correctly. But I hope this is a temporary solution. If someone figures out how to solve this problem, please write.

**Comment by posean** [comment]
> Until fixes exist, try opening from the shell: /Applications/Winbox-mac.app/Contents/MacOS/winbox-mac
So... on arm macos its not work...
Waiting for fix...

**Comment by thiagodamas** [comment]
> > Until fixes exist, try opening from the shell: /Applications/Winbox-mac.app/Contents/MacOS/winbox-mac
> 
> 
> 
> So... on arm macos its not work...
> 
> Waiting for fix...

I' using MacBook Air m3 here

**Comment by alexvamp** [comment]
I have the app located elsewhere.   
<img width="372" alt="Снимок экрана 2024-10-22 в 11 31 47" src="https://github.com/user-attachments/assets/a99b8e57-3ec0-4329-a29c-9f5b71e42661">

**Comment by belthesar** [comment]
@alexvamp I can look at trying to make the script execution path relative to account for different pathing. In the meantime, if you can provide feedback as to whether the application functions in the default `/Applications` path that would be great.

**Comment by posean** [comment]
@belthesar I try to replace winbox-app and YEP! It works!
![Снимок экрана 2024-10-25 в 12 05 44](https://github.com/user-attachments/assets/f9543ce2-21d4-416b-a8fd-851e7a13f3a3)
