### ISSUE TITLE
macOS Sequoia route to unreachable host

### ISSUE THREAD

**Issue by UncleVic** [nrlquaker/winbox-mac#157]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
The app can't connect to the host by particular IP address.

**To Reproduce**
1. Run the app
2. Click on 'Connect'
3. See error.

**Expected behavior**
It had connected before

**Desktop (please complete the following information):**
 - macOS version: macOS Sequoia 15.0 (24A335)
 - macOS language English
 - Winbox-mac version 3.41
 - Winbox version 3.41

**Comment by LightMoon** [comment]
Confirming facing the same issue.

**Comment by arsa-dev** [comment]
Same issue here with latest version, checked on macOS settings (as described here https://support.apple.com/en-au/guide/mac-help/mchla4f49138/mac) but there is no option to add app to the list, only it is possible to enable/disable apps appearing there.  So maybe the focus can be in the direction to request this permission from the app
![image](https://github.com/user-attachments/assets/3f5a521f-94e0-4d95-83d5-96b4121bddf0)

Just as a workaround: seems that the blocking is affecting only to macOS directly connected subnets, so if you connect to your mikrotik over another routable ip at other subnet where you are not connected it just works properly. Did not try if connecting by mac is working or not, maybe it is.

**Comment by iharosi** [comment]
I'm having the same issue on Sequoia. I think it has something to do with the Win64 binary and how it isn't requesting local network permissions through macOS's API.

**Comment by cswingler** [comment]
I'm seeing the same thing, but curiously I _can_ hit the Mikrotik box that's my default gateway--all of the others report "no route to host"

**Comment by Eretuk** [comment]
Guys, have found, if you go to package content and run it via terminal and execute via terminal, it works. bcz terminal have access to network.
Just a workaround

**Comment by Hellomik2002** [comment]
Don't work with terminal, from Sequoia 15.0.1

**Comment by ssamadgh** [comment]
> Guys, have found, if you go to package content and run it via terminal and execute via terminal, it works. bcz terminal have access to network. Just a workaround

This worked for me on mac OS 15.1 Beta (24B5055e) using ip address as session

**Comment by belthesar** [comment]
Hi folks - 

Please see https://github.com/nrlquaker/winbox-mac/issues/156#issuecomment-2397585005 re: Sequoia compatibility, and the difficulties around a fix.

**Comment by guorenxi** [comment]
Same issue. And I found a native winbox for macos at offical website
https://mikrotik.com/download

**Comment by belthesar** [comment]
Fixed by #159.
