### ISSUE TITLE
Cannot run in Chinese MacOS 10.15

### ISSUE THREAD

**Issue by ycsos** [nrlquaker/winbox-mac#16]
**Describe the bug**
I install the application by brew cask install nrlquaker-winbox and nothing wrong with it ,
But When I click the application icon and run it , nothing happened, but the icon jump and jump, at least no windows

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15]
 - Winbox-mac version [e.g. 3.20]

and Here is when I run /Applications/Winbox-mac.app/Contents/MacOS/startwine:
`nagato@nagatos-iMac ~ % /Applications/Winbox-mac.app/Contents/MacOS/startwine
wine: failed to update /Users/nagato/Library/Application Support/com.mikrotik.winbox_320 with /Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/../bin/../share/wine/wine.inf: No such file or directory
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0025:fixme:hid:parse_descriptor More than 10 individual usages defined
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"dbghelp.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/dbghelp.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library dbghelp.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:load_builtin_dll failed to load .so lib for builtin L"WININET.dll": dlopen(/Applications/Winbox-mac.app/Contents/Resources/Wine.app/Contents/Resources/lib64/wine/wininet.dll.so, 258): Library not loaded: /Users/reb/winebottler/usr/lib/libz.1.dylib
  Referenced from: /Applications/Winbox-mac.app/Contents/Resources/Wine.app
0009:err:module:import_dll Loading library WININET.dll (which is needed by L"C:\\winebottler\\winbox64.exe") failed (error c000007a).
0009:err:module:attach_dlls Importing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000135
0032:err:module:attach_dlls "comctl32.dll" failed to initialize, aborting
0032:err:module:attach_dlls Initializing dlls for L"C:\\winebottler\\winbox64.exe" failed, status c0000005`

**Comment by ycsos** [comment]
I don't know why this happened, but I find a solution!
if the main language of your system is Chinese, the application cannot run, 
But when I change to English and It is OK now.

I don't know why it happened may be related with character encoding?

**Comment by Doublemine** [comment]
> if the main language of your system is Chinese, the application cannot run,
But when I change to English and It is OK now.

It's works for me.

**Comment by ycsos** [comment]
> > if the main language of your system is Chinese, the application cannot run,
> > But when I change to English and It is OK now.
> 
> It's works for me.

what's your OS version and software version?

**Comment by Atroc-0625** [comment]
@nrlquaker Yes, the system Chinese cannot be used. Can I support the Chinese system? This problem does not occur in v3.19

**Comment by Ledax** [comment]
Maybe custom language settings for app can fix this problem?
![image](https://user-images.githubusercontent.com/34000540/67647006-96e64100-f96b-11e9-9a7e-23dfa9b082fb.png)
![image](https://user-images.githubusercontent.com/34000540/67647042-c39a5880-f96b-11e9-8dc6-fd68e80151c1.png)

**Comment by Doublemine** [comment]
> > > if the main language of your system is Chinese, the application cannot run,
> > > But when I change to English and It is OK now.
> > 
> > 
> > It's works for me.
> 
> what's your OS version and software version?

You can view details at here: https://github.com/nrlquaker/winbox-mac/issues/12#issuecomment-545247386

**Comment by Atroc-0625** [comment]
> > > > if the main language of your system is Chinese, the application cannot run,
> > > > But when I change to English and It is OK now.
> > > 
> > > 
> > > It's works for me.
> > 
> > 
> > what's your OS version and software version?
> 
> You can view details at here: [#12 (comment)](https://github.com/nrlquaker/winbox-mac/issues/12#issuecomment-545247386)

<img width="407" alt="WX20191028-105347@2x" src="https://user-images.githubusercontent.com/37469514/67648811-b8e2c200-f971-11e9-8832-82138ca26a2d.png">

**Comment by Atroc-0625** [comment]
If you want to use winbox, change my mac language to English, it is too inconvenient.

**Comment by nrlquaker** [comment]
> > > > > if the main language of your system is Chinese, the application cannot run,
> > > > > But when I change to English and It is OK now.
> > > > 
> > > > 
> > > > It's works for me.
> > > 
> > > 
> > > what's your OS version and software version?
> > 
> > 
> > You can view details at here: [#12 (comment)](https://github.com/nrlquaker/winbox-mac/issues/12#issuecomment-545247386)
> 
> <img alt="WX20191028-105347@2x" width="407" src="https://user-images.githubusercontent.com/37469514/67648811-b8e2c200-f971-11e9-8832-82138ca26a2d.png">

Where is this screenshot from?

**Comment by nrlquaker** [comment]
Just wandering if you manually install `wine` and run `wine64 winbox64.exe` will it work?
You can install wine from [official pkg](https://dl.winehq.org/wine-builds/macosx/pool/winehq-stable-4.0.2.pkg).

**Comment by nrlquaker** [comment]
Does adding `export LC_CTYPE="en_US.UTF-8"` to the top of `startwine` helps?

**Comment by Doublemine** [comment]
> Just wandering if you manually install `wine` and run `wine64 winbox64.exe` will it work?
> You can install wine from [official pkg](https://dl.winehq.org/wine-builds/macosx/pool/winehq-stable-4.0.2.pkg).

Yep, it's work fine via `wine64 winbox.exe`

**Comment by nrlquaker** [comment]
@Doublemine and what about `export LC_CTYPE="en_US.UTF-8"`?
