### ISSUE TITLE
App freezes

### ISSUE THREAD

**Issue by Sogl** [nrlquaker/winbox-mac#160]
Upgraded routerOS on Microtik to 7.16.1
Updated the application from 3.37.0 -> 3.41.0

After startup application does not show window and hangs, wine64-preloader eats 99.9% of resources. Only forced unloading is possible.

mac intel i9 2019
OS X Ventura 13.6
Winbox-mac 3.41.0

**Comment by Sogl** [comment]
It turned out that I had about 10 `wine64-preloader` processes. I killed them all and now app seemed to work.

**Comment by belthesar** [comment]
This is a known issue that happens where sometimes the Wine processes are not closed when App bundle is closed. It happens more frequently when you force close the app. It's unfortunately not something that can be corrected for.
