### ISSUE TITLE
Build Wine w/o dependencies

### ISSUE THREAD

**Issue by Atroc-0625** [nrlquaker/winbox-mac#19]
Can Quartz not be installed, or built in winbox for mac, this program will appear on the starter, very uncomfortable

**Comment by nrlquaker** [comment]
What do you mean by "this program will appear on the starter"? Please explain.

**Comment by Atroc-0625** [comment]
> What do you mean by "this program will appear on the starter"? Please explain.

Must Quartz need to be installed? Or can it be built in winbox

**Comment by nrlquaker** [comment]
I think `Wine` can be built without `XQuartz` and `Freetype` dependencies. But I don't have time to investigate how to do it. PR is welcome.
Please show screenshot of what you mean by "this program will appear on the starter".

**Comment by Atroc-0625** [comment]
> 我认为`Wine`可以建立没有`XQuartz`和`Freetype`依赖。但是我没有时间去研究如何做。欢迎公关。
> 请显示“此程序将出现在启动程序上”的含义的屏幕截图。



> I think `Wine` can be built without `XQuartz` and `Freetype` dependencies. But I don't have time to investigate how to do it. PR is welcome.
> Please show screenshot of what you mean by "this program will appear on the starter".
I just hope that these dependencies can be built in winbox

**Comment by Atroc-0625** [comment]
> I think `Wine` can be built without `XQuartz` and `Freetype` dependencies. But I don't have time to investigate how to do it. PR is welcome.
> Please show screenshot of what you mean by "this program will appear on the starter".

I just hope that these dependencies can be built in winbox

**Comment by nrlquaker** [comment]
Its is possible. Feel free to contribute.

**Comment by Atroc-0625** [comment]
> 这是可能的。随时贡献。

Thank you, I am looking forward to it.

**Comment by nrlquaker** [comment]
I've created #32 for this.
