### ISSUE TITLE
command-line args

### ISSUE THREAD

**Issue by mtnbrit** [nrlquaker/winbox-mac#2]
Hi would it be possible to open this winbox from a command line and include arguments for the IP address and optionally the username and password and have them pass to the app so it opens right up logged in?

**Comment by nrlquaker** [comment]
Hello.
Not sure if its possible.
Asked author of winbottler.
Waiting for response.

**Comment by nrlquaker** [comment]
Got no response from author of winbottler.
I think its not possible.
I can create script that will modify plist, adding cli arg to it:
```
<key>WineProgramArguments</key>
<string>one two three</string>
```
But I don't see a way to remove them after the program finishes.
And I don't think its secure store password in plain text.
Closing for now.
