### ISSUE TITLE
I can not import 

### ISSUE THREAD

**Issue by RuPHuSUA** [nrlquaker/winbox-mac#21]
Hi
Pls help me, I can import my Winbox Loader Addressrs. App is stop and all.

**Comment by nrlquaker** [comment]
Please read and fill template next time.
Its [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).
Workaround is too copy `Addresses.cdb` from the old version to
```
~/Library/Application\ Support/com.mikrotik.winbox_3.20.1/drive_c/users/`id -un`/Application Data/Mikrotik/Winbox
```
