### ISSUE TITLE
MACOS Catalina 10.15.1 - 3.20.3 Won't open

### ISSUE THREAD

**Issue by Tyzlor** [nrlquaker/winbox-mac#25]
**Checklist**

- [X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ X] I made sure this is not the original Winbox issue.
- [ X] I made sure this is not a [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).

**Describe the bug**
Opening Winbox-Max after updating to 3.20.3. The application will not open
Error in Syslog -> 
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000017.startwine[2693]): Service exited with abnormal code: 5
Downgrading also now fails to open.

**To Reproduce**
1. Brew cask upgrade nrlquaker-winbox
2. Open Application
3. Complete security (Gatekeeper)

**Expected behavior**
Application opens

**Screenshots**
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000017.startwine[2693]): Service exited with abnormal code: 5

**Desktop (please complete the following information):**
 - macOS version: [10.15.1]
 - macOS language [English]
 - Winbox-mac version [e.g. 3.20.3]
 - Winbox version [e.g. 3.20 ??]

**Additional context**
Downgrading using prebuilt DMG or Old git repo pulls produced same results..
I can only assume this is a new gatekeeper / macos protection error

**Comment by nrlquaker** [comment]
Have you allow allowed Winbox related files in Security & Privacy -> General?

**Comment by Tyzlor** [comment]
Yes - Don't think it is a Macos gatekeeper issue .. I did the full allow for the app etc.
searching for the error online doesn't yield any results either.

**Comment by nrlquaker** [comment]
Strange. I got this error when something is not allowed in "Security & Privacy -> General". Have you tried `3.20.2` or `3.20.1`?

**Comment by Tyzlor** [comment]
Tried both and uninstalling/reinstalling from brew.

Also using your Installer files for each version

Very very weird

**Comment by nrlquaker** [comment]
And? Nothing worked?

**Comment by Tyzlor** [comment]
Correct - i'm usually good at troubleshooting these things ;-)

So any other things I can try?

**Comment by nrlquaker** [comment]
You can try to remove `~/.wine`, `~/Library/Application Support/com.mikrotik.winbox_*`. But save `Addresses.cdb` first. Do `find / -name wine` and remove all wine related stuff.

**Comment by nrlquaker** [comment]
Also try to remove quarantine attr: `xattr -rd com.apple.quarantine /Applications/Winbox-mac.app`.

**Comment by Tyzlor** [comment]
Ok I’ll get to in about 24 hours or so - I’m away from my Mac for a day -  I did try the quarantine thing already with no luck.

**Comment by Tyzlor** [comment]
Ok

So status update - I removed all references to wine and winbox from command line.
I also used spctl to try and add /Applications/Winbox-mac to Gatekeeper.

I still get the same error.
The xattr -rd command also made no difference..

Thoughts ?

**Comment by nrlquaker** [comment]
The only idea is to try it on the fresh macOS 10.15.1. I have no idea about this error. I've tested on the fresh VM - works fine.

**Comment by Tyzlor** [comment]
So - made some progress.

I installed Wine Staging 4.18 and then ran wine64 /Downloads/winbox64.exe 
That seems to be working now..

Any ideas on your bundled version ?

**Comment by nrlquaker** [comment]
Have you tried in on fresh VM?

**Comment by nrlquaker** [comment]
Not sure what I can do here. And there is no response. So, closing.

**Comment by sobanakram** [comment]
Hi @nrlquaker 
I am having same error, 
before it was working, Then I clean install Mac os Catalina, and it is stop working.

**Comment by samm-git** [comment]
I have the same issue. Could you please reopen? 

```
$ open /Applications/Winbox-mac.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Winbox-mac.app
```
Will try to add some debugging here, but i expect that it does not like shell wrapper.

**Comment by nrlquaker** [comment]
Maybe I know what's wrong. They removed `bash` from  Catalina.
Can you post the output please: `command -v bash`?

**Comment by samm-git** [comment]
```
+ export LC_CTYPE=en_US.UTF-8
+ LC_CTYPE=en_US.UTF-8
+ export FREETYPE_PROPERTIES=truetype:interpreter-version=35
+ FREETYPE_PROPERTIES=truetype:interpreter-version=35
++ dirname startwine
+ BUNDLERESOURCEPATH=./../Resources
+ '[' -f ./../Resources/wine/bin/wine64 ']'
+ export WINEUSRPATH=./../Resources/wine
+ WINEUSRPATH=./../Resources/wine
++ defaults read ./../Resources/../Info CFBundleIdentifier
2019-12-18 23:27:07.159 defaults[32003:313759]
The domain/default pair of (./../Resources/../Info, CFBundleIdentifier) does not exist
+ export 'WINEPREFIX=/Users/oleksii_samorukov/Library/Application Support/'
+ WINEPREFIX='/Users/oleksii_samorukov/Library/Application Support/'
+ '[' '!' -d '/Users/oleksii_samorukov/Library/Application Support/' ']'
+ '[' -z '' ']'
++ /usr/sbin/scutil --get ComputerName
+ export COMPUTERNAME=PRG-160461-C02WC0N1HV2V
+ COMPUTERNAME=PRG-160461-C02WC0N1HV2V
+ BIN_FILE=C:/winbox/winbox64.exe
++ sed 's|C:||'
+++ dirname C:/winbox/winbox64.exe
+ BIN_PATH=./../Resources/wineprefix/drive_c/winbox
+ '[' -d ./../Resources/wineprefix/drive_c/winbox ']'
+ cd ./../Resources/wineprefix/drive_c/winbox
+ DYLD_FALLBACK_LIBRARY_PATH=/usr/X11/lib
+ ./../Resources/wine/bin/wine64 C:/winbox/winbox64.exe
startwine: line 26: ./../Resources/wine/bin/wine64: No such file or directory
+ ./../Resources/wine/bin/wine64 C:/winbox/winbox64.exe
startwine: line 28: ./../Resources/wine/bin/wine64: No such file or directory
```

**Comment by samm-git** [comment]
bash is not removed in catalina, it is just not a default shell anymore:

```
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by samm-git** [comment]
So looks like that line is causing issues: `export WINEPREFIX="$HOME/Library/Application Support/$(defaults read "$BUNDLERESOURCEPATH/../Info" CFBundleIdentifier)"`

**Comment by samm-git** [comment]
Ok, i finally been able to run it. Changes i done:

1. Did `export WINEPREFIX="$HOME/Library/Application Support/winbox-mac"` instead of original in the `startwine`.
2. After first run i had to do `xattr -rd com.apple.quarantine` on the "$HOME/Library/Application Support/winbox-mac" directory

**Comment by samm-git** [comment]
Will do a PR now

**Comment by samm-git** [comment]
https://github.com/flutter/flutter/issues/37701 related issue

**Comment by samm-git** [comment]
@nrlquaker done. At least proposed fix works for me

**Comment by nrlquaker** [comment]
@samm-git Thanks for finding issue with `defaults`. Will check it later today.
Why does Apple always like to break things...

**Comment by Tyzlor** [comment]
Hi @samm-git 

Thanks for finding the issue - appreciate it..

@nrlquaker Any chance we would be able to get a working compiled version with the new fix via brew ??

Cheers

**Comment by nrlquaker** [comment]
@Tyzlor will do it today.

**Comment by hunter-nl** [comment]
Is the fixed version already available through brew? I have still the issue.

**Comment by nrlquaker** [comment]
Issue fixed in the [latest release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20.4).
If you want to use `brew` please wait when [this PR](https://github.com/Homebrew/homebrew-cask/pull/74632) is merged.
