### ISSUE TITLE
Neighbors won't get listed

### ISSUE THREAD

**Issue by obinoob** [nrlquaker/winbox-mac#26]
The Winbox app release version 3.20.3 it's unable to list Neighbors.
Open Winbox, click Neighbors tab at the bottom and refresh.
I would expect the Mikrotik devices to get listed.

Running app under mac OS X HS 10.13.6 US English

**Comment by nrlquaker** [comment]
Why haven't you fill template?
Have you enabled discovery on the router?
Are you sure that is `Winbox-mac` specific problem?

**Comment by neg2led** [comment]
Neighbors show up just fine for me, but they only show up on whichever interface is at the top of the network service list in system preferences (ie currently used for internet connection).

**Version info as per template**
 - macOS version: 10.15.1
 - macOS language: English (Australia)
 - Winbox-mac version: 3.20.3
 - Winbox version: 3.20

Suspect @obinoob is trying to see neighbors on a USB ethernet interface while also connected to WiFi?

**Comment by nrlquaker** [comment]
No response and its not likely a `Winbox-mac` issue. Closing.
