### ISSUE TITLE
Unable to open 'winbox Mac' because the developer could not be verified.

### ISSUE THREAD

**Issue by zengzw81** [nrlquaker/winbox-mac#27]
**Checklist**

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ ] I made sure this is not the original Winbox issue.
- [ ] I made sure this is not a [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5]
 - macOS language [e.g. English, Russian, Chinese]
 - Winbox-mac version [e.g. 3.18]
 - Winbox version [e.g. 3.18]

**Additional context**

**Comment by nrlquaker** [comment]
Check [this document](https://github.com/nrlquaker/winbox-mac/blob/master/UNVERIFIED_DEVELOPER.md).

**Comment by rdif** [comment]
> Check [this document](https://github.com/nrlquaker/winbox-mac/blob/master/UNVERIFIED_DEVELOPER.md).

Hi, @nrlquaker. The link you posted are broken.

**Comment by nrlquaker** [comment]
Hi, @rdif. The document was mostly related to `dlls` and `exe`, on which Gatekeeper says "Unable to open because the developer could not be verified". Ifs not relevant anymore. If you have this message, just right click the `Winbox.app` in the `Application` folder and select open.

**Comment by nrlquaker** [comment]
@KrzaQ right click app, open, allow.
