### ISSUE TITLE
macOS Catalina 10.15.2 Chinese - 3.20.4 Won't open

### ISSUE THREAD

**Issue by marshal60** [nrlquaker/winbox-mac#29]
**Checklist**

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ ] I made sure this is not the original Winbox issue.
- [ ] I made sure this is not a [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).

**Describe the bug**
Opening Winbox-Mac after updating to 3.20.4. The application will not open
**syslog**:  Dec 27 23:54:13 MacBook-Pro com.apple.xpc.launchd[1] (com.mikrotik.winbox_3.20.4.6652[13786]): Service exited with abnormal code: 5

**To Reproduce**
1. Brew cask upgrade nrlquaker-winbox
2. Open Application
3. icon jump

**Expected behavior**
Application can run in 10.15.2

**Screenshots**
none

**Desktop (please complete the following information):**
 - macOS version: [ 10.15.2]
 - macOS language [ Chinese]
 - Winbox-mac version [3.20.4]
 - Winbox version [3.20]

**Additional context**
none

**Comment by WoLpH** [comment]
This might be related to the gatekeeper. This fixed it for me:
```bash
xattr -d com.apple.quarantine /Applications/Winbox-mac.app
```

**Comment by nrlquaker** [comment]
The [same issue](https://github.com/nrlquaker/winbox-mac/issues/25) was fixed in `3.20.4`.
Is the issue reproducible only on `3.20.4` or `3.20.3` has the same problem?

**Comment by satelitetv** [comment]
Hi,

i have of the same problem. I updated to the Catalina version and the application does not start, do you know what it could be or how to fix it?

I leave the log

thanks

<img width="1080" alt="Captura de pantalla 2020-01-04 a las 13 36 16" src="https://user-images.githubusercontent.com/36230328/71765866-ca0ff800-2ef9-11ea-8cbd-dd7a0b821a00.png">

**Comment by star8618** [comment]
10.15.2无法使用，打开一片空白！

**Comment by nrlquaker** [comment]
Closing as no response.
