### ISSUE TITLE
can not upload and download file

### ISSUE THREAD

**Issue by simonwanghub** [nrlquaker/winbox-mac#30]
**Checklist**

catalina 10.15.2

**Describe the bug**
 nrlquaker-winbox was up to date, but i can't upload and download in winbox.
can't choose file source.

![image](https://user-images.githubusercontent.com/30173054/71702750-18df6400-2e0c-11ea-85e1-9eca12f7b259.png)

**Comment by nrlquaker** [comment]
Its a [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).

**Comment by dade80vr** [comment]
You can simply bypass the problem (Wine interface limit) by import/export files in ssh by using sftp:

`sftp admin@10.0.2.1:20080304-25oak.rsc `

https://wiki.mikrotik.com/wiki/Using_SSH_for_system_backup

**Comment by nrlquaker** [comment]
`Wine 5` stable will be released in about a week. Will update `Wine` as soon as it will be released. As its known issue closing it for now.
