### ISSUE TITLE
The UI of 10.15.2 isn't normal

### ISSUE THREAD

**Issue by CaiJingLong** [nrlquaker/winbox-mac#31]
**Checklist**

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.
- [x] I made sure this is not a [known issue](https://github.com/nrlquaker/winbox-mac#known-issues).

Open the app in my macos, My mac os version is 10.15.2, Locale is Chinese.
![image](https://user-images.githubusercontent.com/14145407/72033054-1c6f6100-32cc-11ea-981c-e45b949bdd5f.png)

download link: dmg of https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20.4

**Comment by nrlquaker** [comment]
You have to install dependencies. Check [Installation](https://github.com/nrlquaker/winbox-mac#installation).
