### ISSUE TITLE
Winbox-mac 3.20.4 won't open on macOS Catalina

### ISSUE THREAD

**Issue by amartins** [nrlquaker/winbox-mac#34]
**Checklist**

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [X] I made sure this is not the original Winbox issue.

**Describe the bug**
Winbox is not opening on MacOS Catalina 10.15.2

**To Reproduce**
1. Go to 'iTerm'
2. Run the command: open /Applications/Winbox-mac.app

**Error Message**

LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Winbox-mac.app.

**Desktop (please complete the following information):**
 - macOS version: 10.15.2
 - macOS language: English
 - Winbox-mac version 3.20.4

**Comment by nrlquaker** [comment]
Any errors when you directly invoke `/Applications/Winbox-mac.app/Contents/MacOS/startwine`?

**Comment by amartins** [comment]
Yes. I removed the quarantine attr... 

Here is the error message when I invoke startwine directly: 

➜  ~ /Applications/Winbox-mac.app/Contents/MacOS/startwine
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000110000-0000000068000000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000110000-0000000068000000
[1]    25643 terminated  /Applications/Winbox-mac.app/Contents/MacOS/startwine

**Comment by nrlquaker** [comment]
Should be fixed in the latest [release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20.5).
