### ISSUE TITLE
v3.20.5-rc1 can't open or import the addresses.WBX in MacOS 10.15.3

### ISSUE THREAD

**Issue by coolchenK** [nrlquaker/winbox-mac#35]
RT.
v3.20.5-rc1 can't open or import the addresses.WBX in MacOS Catalina 10.15.3

**Comment by nrlquaker** [comment]
Should be fixed in the latest [release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.20.5). Also check [note](https://github.com/nrlquaker/winbox-mac#note).

**Comment by coolchenK** [comment]
Yes,it could import the config,but I found the other bug,if it can't recognize certain characters, it will not be able to import.

Screenshot below

<img width="739" alt="1" src="https://user-images.githubusercontent.com/13838753/73931340-1b554200-4913-11ea-9b1b-0e9c4437294f.png">
<img width="1060" alt="2" src="https://user-images.githubusercontent.com/13838753/73931494-5b1c2980-4913-11ea-8454-7757ff3de0ad.png">

**Comment by nrlquaker** [comment]
I think they are non UTF characters. You can edit `startwine` and change `LC_CTYPE="en_US.UTF-8"` to you language to fix it.

**Comment by coolchenK** [comment]
Yes,it's Chinese.Thanks for your great work!
