### ISSUE TITLE
Cannot move file at file menu

### ISSUE THREAD

**Issue by TwadaCZ** [nrlquaker/winbox-mac#36]
**Checklist**

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [X] I made sure this is not the original Winbox issue.

**Describe the bug**
Files at FILE menu is not possible to move between directories.

**To Reproduce**
1. Go to FILE menu.
2. Upload any .rsc file (if there is not)
3. Try to move to another directory...

**Expected behavior**
There is "flash" directory at new Mikrotik routers. Root directory is deleted after router reboot.
If I need to "save" configurations etc. I must to "move" to the "/flash" directory.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5]
 - macOS language [Czech]
 - Winbox-mac version [3.20.5]
 - Winbox version [3.20]

**Additional context**

**Comment by nrlquaker** [comment]
I can reproduce the issue. Files are always uploaded to the `/`. Selecting the file, pressing `copy` then selecting `/flash/pub` and pressing `paste`does nothing.
And drag and drop is [disabled](https://github.com/nrlquaker/winbox-mac/blob/master/CHANGELOG_WINBOX.md#320) on 64-bit Winbox in Wine in `3.20`.
Anyway, its not `Winbox-mac` issue. Please contact `winbox` developers.

**Comment by TwadaCZ** [comment]
Nice…thank you.

I never use Copy / Paste buttons at the Files :-) It is new for me :-)



--
Tvaruzek Vladislav

**Comment by nrlquaker** [comment]
I think you can [use](https://github.com/nrlquaker/winbox-mac/issues/30#issuecomment-573254629) `ssh` for this.

**Comment by nrlquaker** [comment]
Drag and drop was enabled again in `winbox 3.21`. It was added in the [latest](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.21.0) release.
