### ISSUE TITLE
Winbox does not start.

### ISSUE THREAD

**Issue by adrianmace** [nrlquaker/winbox-mac#37]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Winbox does not appear to start. Goes into "Force Quit" state. Looks like there are some wine64-preloader processes running but no window ever appears.

**To Reproduce**
1. brew cask install nrlquaker-winbox (3.20.4 originally)
2. Launch this and notice behavior where it does not start - appears in dock but does not open a window
3. brew cask update
4. brew cask upgrade nrlquaker-winbox (3.20.5)
5. Observe same behavior

**Expected behavior**
Winbox opens.

**Screenshots**
![image](https://user-images.githubusercontent.com/5071859/73919564-e4cdf600-4917-11ea-9f06-f06282c90d3f.png)

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.3]
 - macOS language [e.g. English]
 - Winbox-mac version [e.g. 3.20.5]
 - Winbox version [Don't know]

**Additional context**
Corporate-managed device.

**Comment by nrlquaker** [comment]
Can you start `/Applications/Winbox-mac.app/Contents/MacOS/startwine` from CLI and share the log?

**Comment by adrianmace** [comment]
```$ /Applications/Winbox-mac.app/Contents/MacOS/startwine
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000110000-0000000068000000
0015:fixme:esync:do_esync eventfd not supported on this platform.
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000110000-0000000068000000
0017:fixme:esync:do_esync eventfd not supported on this platform.
0017:err:module:__wine_process_init failed to load L"C:\\windows\\system32\\wineboot.exe", error c0000018
0015:err:environ:run_wineboot failed to start wineboot c0000018
```

**Comment by nrlquaker** [comment]
Maybe you have 32-bit default wineprefix?
Try removing it `rm -rf ~/.wine`.

**Comment by adrianmace** [comment]
No change, unfortunately.

**Comment by nrlquaker** [comment]
Can you try download [wine staging 5.1](https://dl.winehq.org/wine-builds/macosx/pool/portable-winehq-staging-5.1-osx64.tar.gz) and launch winbox: `wine64 winbox.exe`?
Is it working?

**Comment by adrianmace** [comment]
I get the same error as above, though I do concede that it's probably a gatekeeper issue on catalina.

**Comment by nrlquaker** [comment]
Well, then its not `winbox-mac` issue. Try asking for help on [wine forum](https://forum.winehq.org/viewforum.php?f=9).
