### ISSUE TITLE
Not able to find Addresses.cdb on iCloud drive

### ISSUE THREAD

**Issue by zokl** [nrlquaker/winbox-mac#38]
**Checklist**

- [*] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [*] I made sure this is not the original Winbox issue.

**Describe the bug**
I have the last version of winbox mac 3.20.5 and I am not able to use my Addresses.cdb file stored on iCloud drive. I am not able to find desired directories and file Addresses.cdb in Open or Import window. The same behavior is if I use a symlink to the directory.

**To Reproduce**
1. Open or Import Addresses.cdb from directory on iCloud or other symlinked directory.

**Expected behavior**
Use the file in window dialogue.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.3]
 - macOS language [e.g. English]
 - Winbox-mac version [e.g. 3.20.5]
 - Winbox version [e.g. 3.20]

**Additional context**
N/A

**Comment by nrlquaker** [comment]
Please fill in template.

**Comment by nrlquaker** [comment]
There are some restrictions in Catalina. Please check the [note](https://github.com/nrlquaker/winbox-mac#note). To be able to see hidden files in file choosing dialog press <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>.</kbd>.

**Comment by zokl** [comment]
> There are some restrictions in Catalina. Please check the [note](https://github.com/nrlquaker/winbox-mac#note). To be able to see hidden files in file choosing dialog press Cmd + Shift + ..

Thank you. Yes, both of the solutions work but I think that makes full access write permission for whole shell is not a good idea.

**Comment by nrlquaker** [comment]
I know. But I don't know of any other existing solution. There are a lot of similar [posts](https://emacs.stackexchange.com/questions/53026/how-to-restore-file-system-access-in-macos-catalina). If you know about it please share.

Also its a bit strange for me that launching app from CLI and double clicking it gives app different permissions (iTerm got Full Disk Access, but the app shouldn't be affected by it).

macOS keeps "improving" security that leads only to problems to real users and doesn't affect real threats. If can want you can read [here](https://lapcatsoftware.com/articles/notarization.html) about security problems in macOS.

Anyway, closing for now.

**Comment by nrlquaker** [comment]
Btw, you can remove access right for `bash` after you import the file.

**Comment by zokl** [comment]
Thank you very much for your help.

**Comment by nrlquaker** [comment]
You are welcome
