### ISSUE TITLE
About Chinese font display

### ISSUE THREAD

**Issue by angell8800** [nrlquaker/winbox-mac#39]
Chinese notes in winbox or garbled characters when using Chinese, hope to solve this problem, thank you!

**Comment by nrlquaker** [comment]
Please fill in template and add screenshot.

**Comment by angell8800** [comment]
![IMG_3969](https://user-images.githubusercontent.com/48166132/74597707-96022800-509e-11ea-804f-68e86e204700.JPG)

**Comment by nrlquaker** [comment]
To fix it you have to change `export LC_CTYPE="en_US.UTF-8"` in `Winbox-mac.app/Contents/MacOS/startwine` to `"export LC_CTYPE="zh_CN.UTF-8"`.

**Comment by angell8800** [comment]
What to do

**Comment by angell8800** [comment]
Can you elaborate on the operation steps? I only installed winbox-mac, not wine.

**Comment by angell8800** [comment]
Can I update winbox-mac that supports Chinese characters?

**Comment by nrlquaker** [comment]
Open `Winbox-mac.app/Contents/MacOS/startwine` in text editor.
Change `export LC_CTYPE="en_US.UTF-8"` to `"export LC_CTYPE="zh_CN.UTF-8"`.
I don't know the other way to fix it.

**Comment by angell8800** [comment]
After the change, the winbox-mac display becomes fuzzy and the display is unclear
![IMG_3970](https://user-images.githubusercontent.com/48166132/74598541-3ca1f500-50ae-11ea-867c-1b791c8b2f56.JPG)

**Comment by nrlquaker** [comment]
From what I can see on your photo only the font is different.

**Comment by angell8800** [comment]
Fonts are not clear

**Comment by nrlquaker** [comment]
They are not clear anyway, because retina mode is off. But you can [enable](https://github.com/nrlquaker/winbox-mac/blob/master/retina_mode/RETINA.md) it.

**Comment by angell8800** [comment]
How to enable the retina

**Comment by angell8800** [comment]
![IMG_3971](https://user-images.githubusercontent.com/48166132/74598782-bc31c300-50b2-11ea-853c-64289f93068c.JPG)

**Comment by nrlquaker** [comment]
Check linked documentation.
