### ISSUE TITLE
Russian characters display

### ISSUE THREAD

**Issue by darkpal** [nrlquaker/winbox-mac#4]
See the screenshot https://goo.gl/2hehZ1

**Comment by nrlquaker** [comment]
The only working solution I've found is to add `LC_ALL=ru_RU.UTF-8` to `.bash_profile`.
Or you can create wrapper/launch from CLI like this `export LC_ALL=ru_RU.UTF-8 & open /Applications/Winbox-mac.app/`

**Comment by darkpal** [comment]
I set up .bash_profile. When I run the app from terminal it's ok but when I run it from Launchpad the problem remains. Tried to create a wrapper with Platypus - the same.

**Comment by nrlquaker** [comment]
You are right. I've tested it only from CLI.
Anyway its more like wine problem. I suggest asking on [their forums](https://forum.winehq.org).

**Comment by nrlquaker** [comment]
@darkpal I've found solution for you if you still need it.
It seems applications in `macOS` don't have access to `.bash_profile` environment variables.
But you can set them using `launchctl`.
`launchctl setenv LC_ALL ru_RU.UTF-8` should fix your issue.
