### ISSUE TITLE
 The display remains the same when Retina mode is enabled.

### ISSUE THREAD

**Issue by angell8800** [nrlquaker/winbox-mac#40]
WINEPREFIX="~/Library/Application Support/com.mikrotik.winbox" /Applications/Winbox-mac.app/Contents/Resources/wine/bin/wine64 regedit retina.reg 

The display remains the same when Retina mode is enabled.

**Comment by angell8800** [comment]
？

**Comment by nrlquaker** [comment]
Check [Reporting bugs](https://github.com/nrlquaker/winbox-mac#reporting-bugs).

**Comment by angell8800** [comment]
![IMG_3972](https://user-images.githubusercontent.com/48166132/74599053-fbfaa980-50b6-11ea-8541-4603432093c3.JPG)
This is a screenshot of the situation after running wine64

**Comment by angell8800** [comment]
Does this picture work?

**Comment by angell8800** [comment]
Give up, no way
