### ISSUE TITLE
command line args?

### ISSUE THREAD

**Issue by mtnbrit** [nrlquaker/winbox-mac#41]
Hi, how do I pass command line arguments to the application? With the wine version, I was able to say wine winbox.exe <addr> <user> <pwd> and it would open with the fields populated, and connect.

Ive tried open /Applications/Winbox-mac.app --args <addr> <user> <pwd> but it doesnt work

**Comment by nrlquaker** [comment]
I will add this functionality in the next version. It will be released in 1-2 days.

**Comment by nrlquaker** [comment]
The issue is fixed in the [latest release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.21.1). If you want to use `Homebrew` please wait till this [PR](https://github.com/Homebrew/homebrew-cask/pull/77916) is merged.

**Comment by nrlquaker** [comment]
Check [Command line arguments](https://github.com/nrlquaker/winbox-mac#command-line-arguments) on how to use them.
