### ISSUE TITLE
Winbox Version

### ISSUE THREAD

**Issue by gkl1368** [nrlquaker/winbox-mac#43]
When release to Winbox 3.22?

**Comment by nrlquaker** [comment]
Was a bit busy. Will do it today.

**Comment by gkl1368** [comment]
> Was a bit busy. Will do it today.

Thanks.

**Comment by Artycoka** [comment]
today is that day? :D

**Comment by Artycoka** [comment]
> Was a bit busy. Will do it today.

today is that day? :)

**Comment by nrlquaker** [comment]
> > Was a bit busy. Will do it today.
> 
> today is that day? :)

Yes. Working on it right now.

**Comment by nrlquaker** [comment]
Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.22.0).
Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/80036) will be merged if you use `brew cask`.
