### ISSUE TITLE
The domain explained by cname can‘t be connected

### ISSUE THREAD

**Issue by kkxxxxxxx** [nrlquaker/winbox-mac#44]
**Desktop**
- macOS catalina 10.15.4
- macOS language English
- winbox-mac v3.21.1
- winbox v3.21

**Issues**
- if router address is domain, and explained by cname, that can't be connected.

**Comment by nrlquaker** [comment]
Please fill in template.

**Comment by kkxxxxxxx** [comment]
** Desktop**
- macOS catalina 10.15.4
- macOS language English
- winbox-mac v3.21.1
- winbox v3.21

**Issues**
if router address is domain, and explained by cname, that can't be connected.

**Comment by nrlquaker** [comment]
Its not a `Winbox-mac` issue. [Contact](https://forum.mikrotik.com/viewforum.php?f=2) original `Winbox` developers.
