### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by Artycoka** [nrlquaker/winbox-mac#45]
cant't open, file is damage or can't open afther upgrade
brew cask upgrade nrlquaker-winbox
download manualy, same error

ver. OS : 10.15.4

**Comment by nrlquaker** [comment]
Right click -> open.

**Comment by Artycoka** [comment]
> Right click -> open.

:)))
thx but the same

**Comment by Artycoka** [comment]
:)))
thx but the same
same with
open /Applications/Winbox-mac.app --args xxx.xxx.xxx.xxx name pass

 

 

Od: nrlquaker <notifications@github.com>
Príjemca odpovede: nrlquaker/winbox-mac <reply@reply.github.com>
Dátum: streda, 22. apríla 2020, 11:05
Komu: nrlquaker/winbox-mac <winbox-mac@noreply.github.com>
Kópia: Artycoka <meszaros@advice.sk>, Author <author@noreply.github.com>
Predmet: Re: [nrlquaker/winbox-mac] can't open (#45)

 

Right click -> open.

**Comment by Artycoka** [comment]
Need run
xattr -cr /Applications/Winbox-mac.app
to be able to open it

**Comment by nrlquaker** [comment]
Anyway its gatekeeper thing. Not an issue with the app.
