### ISSUE TITLE
downloading last version causes virus alarm!

### ISSUE THREAD

**Issue by tomnone** [nrlquaker/winbox-mac#46]
![Screenshot 2020-04-24 11 07 45](https://user-images.githubusercontent.com/62426690/80199440-9af4d200-8621-11ea-81cb-bed6d6ef1a76.png)
![Screenshot 2020-04-24 11 07 45](https://user-images.githubusercontent.com/62426690/80199516-b3fd8300-8621-11ea-923f-6d58b7e406d0.png)

**Comment by nrlquaker** [comment]
Please fill in the template.
Only `winbox64.exe` is changed compared to previous version.

**Comment by nrlquaker** [comment]
`iexplore.exe` is from [Wine package](https://dl.winehq.org/wine-builds/macosx/pool/portable-winehq-staging-5.1-osx64.tar.gz). 
According to [VirusTotal](https://www.virustotal.com/gui/file/28db27d547e45444a90f7bdceae3bb5ee36ad52569d8d034bd0b7e1b0149095f/detection) only 8/73 detected the virus. I think its false positive. So closing. You can report this to Wine developers.

**Comment by BalleClorin** [comment]
Latest Wine Staging was ok by Avast
