### ISSUE TITLE
Possible infection

### ISSUE THREAD

**Issue by BalleClorin** [nrlquaker/winbox-mac#47]
**Checklist**

- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ x] I made sure this is not the original Winbox issue.

**Describe the bug**
Avast scans the package and find iexplore.exe infected by Win64:CrypterX-gen[Trj]

**To Reproduce**
1.Dowload iexplore.exe from
https://github.com/nrlquaker/winbox-mac/blob/master/Winbox-mac.app/Contents/Resources/wine/lib64/wine/iexplore.exe
2. See error

**Expected behavior**
No anti-virus program actions taken.
[WInBox64_Possible_Infection.pdf](https://github.com/nrlquaker/winbox-mac/files/4553658/WInBox64_Possible_Infection.pdf)

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.3]
 - macOS language [Norwegian]
 - Winbox-mac version [3.23 according to the GitHub page]
 - Winbox version [e.g. 3.18]

**Additional context**

**Comment by nrlquaker** [comment]
Please see #46.
Also can you please download latest [Wine Staging](https://dl.winehq.org/wine-builds/macosx/pool/portable-winehq-staging-5.7-osx64.tar.gz) and check that file for viruses?
Ping @tomnone as well.

**Comment by BalleClorin** [comment]
Downloaded Wine staging. No infection found.

**Comment by nrlquaker** [comment]
Wine Stagin 5.7 [VirusTotal](https://www.virustotal.com/gui/file/906afb8a8947f2fe4cd2984fc58a5a87b7593cce43d696a3101e8feb20887441/detection) scan vs [5.1](https://www.virustotal.com/gui/file/28db27d547e45444a90f7bdceae3bb5ee36ad52569d8d034bd0b7e1b0149095f/detection). Pretty sure its false positive. But you never know.

**Comment by nrlquaker** [comment]
@BalleClorin thanks. Will update to Wine Staging 5.7 then soon.

**Comment by BalleClorin** [comment]
Its very likely a false positive, but those crypto's are scary stuff so I thought I'd better report it :-)

**Comment by nrlquaker** [comment]
@BalleClorin after testing `wine 5.7 staging` I've decided not to update. It starts much slower got some problems with saving session.

**Comment by nrlquaker** [comment]
Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.24.0).
Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/83546) will be merged if you use `brew cask`.
