### ISSUE TITLE
Unable to resize window

### ISSUE THREAD

**Issue by glipschitz** [nrlquaker/winbox-mac#48]
**Describe the bug**
Download Winbox using the brew cask install nrlquaker-winbox

**To Reproduce**
1. Open Winbox
2. Try to drag to resize from corner of window Unable to resize.
3. Cannot select File or Tools menu. Does not drop down.

**Expected behavior**
Expect to be able to resize window dragging from side or corner. 

**Desktop (please complete the following information):**
 - macOS version: 10.14.6
 - macOS language English
 - Winbox-mac version 3.23 x64

**Comment by nrlquaker** [comment]
Please check #42.
Does it fail to resize under the same setup?

**Comment by glipschitz** [comment]
@nrlquaker Yes. Sounds similar.
