### ISSUE TITLE
Please update winbox 3.24

### ISSUE THREAD

**Issue by Atroc-0625** [nrlquaker/winbox-mac#49]
Please update winbox 3.24,thanks

**Comment by nrlquaker** [comment]
Will do later today or tomorrow.

**Comment by Atroc-0625** [comment]
> Will do later today or tomorrow.
😕

**Comment by nrlquaker** [comment]
Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.24.0).
Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/83546) will be merged if you use `brew cask`.
