### ISSUE TITLE
Could not save configuration error

### ISSUE THREAD

**Issue by Casper87** [nrlquaker/winbox-mac#5]
![screenshot at aug 29 23-24-12](https://user-images.githubusercontent.com/1311833/44813543-ae4c6180-abe2-11e8-8fd6-a0433751b573.png)

macOS Mojave 10.14 18A377a x86_64

I have been "installed" winbox-mac by copy in Aplications folder... 
App is running fine but i can't save configuration...

**Comment by nrlquaker** [comment]
Can you please try on Hight Sierra?
Don't have access to Mojave.

**Comment by Casper87** [comment]
Unfortunately i'm running Mojave on my iMac... i can't test to High Sierra :(

**Comment by nrlquaker** [comment]
Tested on Sierra and Hight Sierra. Do not have such a problem.
Need some time to test it in on Mojave in vm.

**Comment by nrlquaker** [comment]
Just tested on Mojave `18A377a`. Works fine for me.
Since its beta, I can't guarantee it works fine.
But when it will be releases I will fix all issues is any.
