### ISSUE TITLE
v3.24.0 Can't open, it will crash after opening winbox

### ISSUE THREAD

**Issue by Atroc-0625** [nrlquaker/winbox-mac#50]
Can't open, it will crash after opening winbox

**Comment by Artycoka** [comment]
xattr -cr /Applications/Winbox-mac.app

**Comment by Atroc-0625** [comment]
> xattr -cr /Applications/Winbox-mac.app

Will still crash and become unusable

**Comment by gtimchenko** [comment]
Same.
Catalina 10.15.4 (19E287)
nrlquaker-winbox: 3.24.0

**Comment by nrlquaker** [comment]
I've found the issue.
Something changed in `wine` and it no longer loads `freetype` from `lib64` folder.
Can you add `export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"` in `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` after `BUNDLERESOURCEPATH=` and test if it fixes crash for you @Atroc-0625 @gtimchenko ?

**Comment by Atroc-0625** [comment]
> I've found the issue.
> Something changed in `wine` and it no longer loads `freetype` from `lib64` folder.
> Can you add `export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"` in `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` after `BUNDLERESOURCEPATH=` and test if it fixes crash for you @Atroc-0625 @gtimchenko ?

There is still a crash

**Comment by Atroc-0625** [comment]
> I've found the issue.
> Something changed in `wine` and it no longer loads `freetype` from `lib64` folder.
> Can you add `export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"` in `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` after `BUNDLERESOURCEPATH=` and test if it fixes crash for you @Atroc-0625 @gtimchenko ?

There is also a question, when you are using winbox, select new winbox, a wine64-preloader app will appear, his app icon is not the latest icon, can you fix it

**Comment by nrlquaker** [comment]
Please provide logs then.
By launching `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` from CLI.

**Comment by Atroc-0625** [comment]
> Please provide logs then.
> By launching `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` from CLI.

atroc@Atroc-MacBook-Pro ~ % /Applications/Winbox-mac.app/Contents/MacOS/winbox-mac ; exit;
000b:fixme:winediag:__wine_start_process Wine Staging 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
001d:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0014:err:display:macdrv_ChangeDisplaySettingsEx No matching mode found 1680x1050x32 @60!
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
000d:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng15.15.dylib
000d:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
000d:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng15.15.dylib
000d:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
000d:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng15.15.dylib
000d:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
000d:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng15.15.dylib
000d:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
000d:err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng15.15.dylib
000d:err:menubuilder:convert_to_native_icon error 0x80004005 getting frame 0
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0029:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0029:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
wine: configuration in L"/Users/atroc/Library/Application Support/com.mikrotik.winbox" has been updated.
0009:fixme:font:update_font_info there is no font defaults for codepages 0,0
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
creating Window Class routeros_null
creating Window Class routeros_connect
DPI=96
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
WARNING: DC::selectFont failed f=0x10050
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
WARNING: DC::selectFont failed f=0x10050
EMS=0
WARNING: DC::selectFont failed f=0x10050
EMS=0

**Comment by nrlquaker** [comment]
> There is also a question, when you are using winbox, select new winbox, a wine64-preloader app will appear, his app icon is not the latest icon, can you fix it

I don't think its possible.

**Comment by Atroc-0625** [comment]
> > There is also a question, when you are using winbox, select new winbox, a wine64-preloader app will appear, his app icon is not the latest icon, can you fix it
> 
> I don't think its possible.

Thanks, is it because it is not an app?

**Comment by nrlquaker** [comment]
> > > There is also a question, when you are using winbox, select new winbox, a wine64-preloader app will appear, his app icon is not the latest icon, can you fix it
> > 
> > 
> > I don't think its possible.
> 
> Thanks, is it because it is not an app?

Because wine opens exe and is not aware that it should use different icon. Next time please create different issue.

**Comment by Atroc-0625** [comment]
> > > > 还有一个问题，当您使用Winbox时，选择新的Winbox，将会出现wine64-preloader应用，他的应用图标不是最新的图标，您可以修复吗
> > > 
> > > 
> > > 我认为这不可能。
> > 
> > 
> > 谢谢，是因为它不是应用程序吗？
> 
> 因为wine打开exe，并且不知道它应该使用其他图标。下次，请创建其他问题。

OK, understand, do you know the cause of the crash?

**Comment by nrlquaker** [comment]
Yes. Provided fix fixed it for me on my other mac.
Please edit `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` to look like:
```
#!/bin/bash

export LC_CTYPE="en_US.UTF-8"
export FREETYPE_PROPERTIES="truetype:interpreter-version=35"
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG="fixme-esync"

BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"

export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"

PLUTIL_REGEX="s/.*<string>\(.*\)<\/string>.*/\1/p"
BUNDLE_ID="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "$PLUTIL_REGEX")"

export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_ID}"

cd "$BUNDLERESOURCEPATH"
"$BUNDLERESOURCEPATH/wine/bin/wine64" "winbox64.exe" "$@"

```

and check.

**Comment by Atroc-0625** [comment]
> Yes. Provided fix fixed it for me on my other mac.
> Please edit `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` to look like:
> 
> ```
> #!/bin/bash
> 
> export LC_CTYPE="en_US.UTF-8"
> export FREETYPE_PROPERTIES="truetype:interpreter-version=35"
> export WINEDLLOVERRIDES="mscoree,mshtml="
> export WINEDEBUG="fixme-esync"
> 
> BUNDLERESOURCEPATH="$(dirname "$0")/../Resources"
> 
> export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"
> 
> PLUTIL_REGEX="s/.*<string>\(.*\)<\/string>.*/\1/p"
> BUNDLE_ID="$(plutil -extract CFBundleIdentifier xml1 -o - "$BUNDLERESOURCEPATH/../Info.plist" | sed -n "$PLUTIL_REGEX")"
> 
> export WINEPREFIX="$HOME/Library/Application Support/${BUNDLE_ID}"
> 
> cd "$BUNDLERESOURCEPATH"
> "$BUNDLERESOURCEPATH/wine/bin/wine64" "winbox64.exe" "$@"
> ```
> 
> and check.

is ok

**Comment by nrlquaker** [comment]
Ok, will create a new release then.

**Comment by Gcenx** [comment]
The issue your having is [Bug 49199](https://bugs.winehq.org/show_bug.cgi?id=49199)

There’s actually more to this bug but tour current workaround should help for the time being

**Comment by nrlquaker** [comment]
@Gcenx thanks for info.

**Comment by biggless** [comment]
> I've found the issue.
> Something changed in `wine` and it no longer loads `freetype` from `lib64` folder.
> Can you add `export DYLD_FALLBACK_LIBRARY_PATH="$BUNDLERESOURCEPATH/wine/lib64"` in `Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` after `BUNDLERESOURCEPATH=` and test if it fixes crash for you @Atroc-0625 @gtimchenko ?

Worked for me

**Comment by nrlquaker** [comment]
Fixed. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.24.1).
Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/83558) will be merged if you use `brew cask`.
