### ISSUE TITLE
Winbox freezes and does not allow itself to be closed in any way

### ISSUE THREAD

**Issue by orokhovatskiy** [nrlquaker/winbox-mac#51]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Sometimes application freezes and I can't open it. I see icon app in my dock like it opened. If I caught this bug I can't close application:
- by Force quit;
- by activity monitor (I can't find it in activity monitor);
- by terminal ("ps aux").

With this state I can't open a new winbox window. Just one method help me - hard reset of my macbook otherwise I can't work with Mikrotiks. Also I can't reboot my macbook from system (Apple - Restart...) because system can't close this application.

**To Reproduce**
I can't tell how to reproduce. May be it connected with second monitor. For example if I connect iPad like second screen - winbox works incorrect and it appear with small Window that I can't resize. Resize works without second screen only.

**Expected behavior**
I expect that I can force quit app if it stuck

**Desktop (please complete the following information):**
 - macOS version: [10.15.4]
 - macOS language [English]
 - Winbox-mac version [How to check it?]
 - Winbox version [3.24]

**Additional context**
- I found only one way to open another windows while it stuck - by terminal:
`~ /Applications/Winbox-mac.app/Contents/MacOS/winbox-mac
000b:fixme:winediag:__wine_start_process Wine Staging 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
001d:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0020:err:plugplay:runloop_thread Couldn't open IOHIDManager.
0014:err:display:macdrv_ChangeDisplaySettingsEx No matching mode found 1792x1120x32 @59!
0009:fixme:font:update_font_info there is no font defaults for codepages 0,0
creating Window Class routeros_null
creating Window Class routeros_connect
DPI=96
EMS=13
ERROR: bad bmp format id=2329
biPlanes=1, biBitCount=1, biCompression=0
ERROR: bad bmp format id=3329
biPlanes=1, biBitCount=1, biCompression=0
creating Window Class routeros_dbl_canvas
 discovery started
rescaning
`
- I found that stuck icon different from original. App that I opened from terminal called wine64-preloader
<img width="192" alt="Screenshot 2020-06-03 at 18 22 06" src="https://user-images.githubusercontent.com/23494254/83655654-5452aa00-a5c7-11ea-9e68-7ec2a7532d47.png">
- After closing - I can't open it again

**Comment by nrlquaker** [comment]
According to resize please check #42. It seems its `wine` issue. Please report it to `wine`.
About the icon when you open app it uses bundled icon. When `wine` opens `exe` by itself (for example, you press disconnect in the active session and it opens new instance of `Winbox.exe`) or when launched from `Winbox-mac.app/Contents/MacOS/winbox-mac` its the same as you launch `wine64 winbox.exe`. In this case its not an app and has no knowledge about the icon and uses icon from `exe` file.
The crash pretty much related to second display bug in `wine`, so I am not able to fix it. So closing.

**Comment by orokhovatskiy** [comment]
Thx for quick response!
