### ISSUE TITLE
Possible infection

### ISSUE THREAD

**Issue by chinkung** [nrlquaker/winbox-mac#52]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
Microsoft Defender ATP scans the package and find termsv.exe infected by Trojan:GenericKD.34008928

**To Reproduce**
1. Download termsv.exe from last release
https://github.com/nrlquaker/winbox-mac/blob/4a41500/Winbox-mac.app/Contents/Resources/wine/lib64/wine/termsv.exe
2. Failed to download and AV alarm go off

**Expected behavior**
No anti-virus program actions taken.

**Screenshots**
![image](https://user-images.githubusercontent.com/2522806/86084482-3c3b5100-bac7-11ea-8b33-ade18fa51813.png)
![image](https://user-images.githubusercontent.com/2522806/86083010-53783f80-bac3-11ea-9e93-1f18ca27e0c7.png)
![image](https://user-images.githubusercontent.com/2522806/86083203-c8e41000-bac3-11ea-87fa-6d5ce14937c3.png)

**Desktop (please complete the following information):**
 - macOS version: 10.14.6
 - macOS language: English
 - Winbox-mac version: 3.24.1
 - Winbox version [e.g. 3.18]

**Additional context**

**Comment by nrlquaker** [comment]
The file is part of `Wine`. Pretty sure its false positive. `Wine` was updated to the latest version to fix [similar issue ](https://github.com/nrlquaker/winbox-mac/issues/47). Just whitelist it.

**Comment by mkostrikin** [comment]
`VMWare Carbon Black` block the same way:
/Applications/Winbox-mac.app/Contents/Resources/wine/lib64/wine/presentationfontcache.exe
/Applications/Winbox-mac.app/Contents/Resources/wine/lib64/wine/winmgmt.exe
/Applications/Winbox-mac.app/Contents/Resources/wine/lib64/wine/plugplay.exe
![image](https://user-images.githubusercontent.com/4443855/87904963-be48e500-ca89-11ea-8af3-4bc07a25b200.png)

**Comment by mkostrikin** [comment]
VMWare Carbon Black block the same way:
/Applications/Winbox-mac.app/Contents/Resources/wine/lib64/wine/presentationfontcache.exe
/Applications/Winbox-mac.app/Contents/Resources/wine/lib64/wine/winmgmt.exe
/Applications/Winbox-mac.app/Contents/Resources/wine/lib64/wine/plugplay.exe
![image](https://user-images.githubusercontent.com/4443855/88282973-c1a3d100-cd14-11ea-8a31-a7d759914425.png)
