### ISSUE TITLE
Neighbors

### ISSUE THREAD

**Issue by rumirabzalov** [nrlquaker/winbox-mac#53]
Hello, how do I make network detection(neighbors) work? Everything works on Windows, detection is enabled on mikrotik.

![Снимок экрана 2020-07-04 в 10 46 50](https://user-images.githubusercontent.com/50944597/86507786-bd565900-bde3-11ea-848b-d765b6e91a73.png)

**Comment by nrlquaker** [comment]
AFAIR opening neighbors tab for the first time macOS firewall asks for permission. Maybe you denied it?
Network discovery should work fine if properly setup on router.
