### ISSUE TITLE
wine client version mismatch, making app unable to open

### ISSUE THREAD

**Issue by si458** [nrlquaker/winbox-mac#54]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
unable to run application after right clicking and saying open, nothing happens

**To Reproduce**
1a. right click app and click open
**OR**
1b. run command below
```
Simon@SiMacBookPro ~ % /Applications/Winbox-mac.app/Contents/MacOS/winbox-mac ; exit;
wine client error:0: version mismatch 596/603.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
```

**Expected behavior**
app to open

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5] 10.15.6
 - macOS language [e.g. English, Russian, Chinese] English
 - Winbox-mac version [e.g. 3.18] latest from github repo
 - Winbox version [e.g. 3.18] latest from github repo

**Additional context**

**Comment by nrlquaker** [comment]
Have you launched other versions before? Or this is the first time you use the app?
Or maybe you got some other wineserver running?

**Comment by si458** [comment]
Hi @nrlquaker,
its the first time i have used your version,
but not the first time ive had wine on my laptop,
but i have removed all wines i could find, both via brew and app in Applications,
so abit lost why its not loading?
how would i find out if another wineserver is running?

**Comment by nrlquaker** [comment]
I think you can check with `ps aux | grep wineserver`.
You can try to kill wineserver with `wineserver -k`.
Never seen this issue before, but after googling it I've found that is mainly because of the other wineserver is running.

**Comment by nrlquaker** [comment]
Can you add `export WINESERVER=/Applications/Winbox-mac.app/Contents/Resources/wine/bin/wineserver
` in `/Applications/Winbox-mac.app/Contents/MacOS/winbox-mac` before `export WINEPREFIX` and try again?

**Comment by si458** [comment]
i feel so embarrassed, i have fixed it...

i ran the terminal and ran `ps aux | grep wine` and the was loads of OLD wineservers still running for some reason from the old Winbox4Mac from the other gent,

killed all the processes, and worked straight away!

also i am confused why it was still running as i had even deleted the apps?

i have also just released, if i had of just restarted my laptop, i probably wouldn't of had this problem!

keep up the amazing work tho! 👍
this version seems so much more stable than the other version!

**Comment by nrlquaker** [comment]
Maybe old wineservers wasn't stoped before deletion of the apps.
Yeap, I think restart will fix it as well.
