### ISSUE TITLE
Mal/Generic-S detected in Winbox_3.24.1.app/Contents/Resources/wine/lib64/wine/termsv.exe

### ISSUE THREAD

**Issue by 1o1o1** [nrlquaker/winbox-mac#55]
**Checklist**

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ ] I made sure this is not the original Winbox issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
https://ibb.co/7n1NTRf

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5]
 - macOS language [e.g. English, Russian, Chinese]
 - Winbox-mac version [e.g. 3.24.1.]
 - Winbox version [e.g. 3.18]

**Additional context**

Mal/Generic-S detected in Winbox_3.24.1.app/Contents/Resources/wine/lib64/wine/termsv.exe

Who is right? who's guilty?

**Comment by nrlquaker** [comment]
The file is part of `Wine`. Pretty sure its false positive. Wine was updated to the latest version to fix [similar issue](#47) . Just whitelist it.

**Comment by 1o1o1** [comment]
added to sophos whitelist :)
in mac 10.15 working the latest version wine 4.0.1.1 only

I dont see wine 5.xx for 10.15 ...

**Comment by nrlquaker** [comment]
`wine 5.7 staging` is bundled with `winbox-mac`. Its located under `/Winbox-mac.app/Contents/Resources/wine/`.
