### ISSUE TITLE
New version 3.27

### ISSUE THREAD

**Issue by gkl1368** [nrlquaker/winbox-mac#56]
Please help to upgrade to new version 3.27. Thanks

**Comment by nrlquaker** [comment]
Will do tomorrow.

**Comment by nrlquaker** [comment]
Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.27.0).
Or wait when this [PR](https://github.com/Homebrew/homebrew-cask/pull/88725) will be merged if you use `brew cask`.
