### ISSUE TITLE
Unable Resize Window With Dell Dock 3000 (DisplayLink)

### ISSUE THREAD

**Issue by H4K0N3** [nrlquaker/winbox-mac#57]
Describe the bug
Download Winbox using the brew cask install nrlquaker-winbox

To Reproduce

Open Winbox
Try to drag to resize from corner of window Unable to resize.
Cannot select File or Tools menu. Does not drop down.
Expected behavior
Expect to be able to resize window dragging from side or corner.

When I'm using Dell Dock 3000 (DisplayLink Drivers Updated for Catalina) Resize from corner of windows, file or tools won't work. After unplug Dell Dock, or using direct to HDMI Display working fine. 

Any suggests?! 

Thanks a lot. 

Desktop (please complete the following information):

macOS version: 10.15.6
macOS language English
Winbox-mac version 3.27 x64

**Comment by nrlquaker** [comment]
Its wine [issue](https://bugs.winehq.org/show_bug.cgi?id=48896). Please post int linked issue.
