### ISSUE TITLE
Not working on macOS Big Sur well....

### ISSUE THREAD

**Issue by TwadaCZ** [nrlquaker/winbox-mac#58]
**Checklist**

- [X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [X ] I made sure this is not the original Winbox issue.

**Describe the bug**
Winbox not working on MacOS Big Sur...Winbox started well...when I am connect to any router, app will crash the whole system.

If I try see Neigbour...and connect via mac address to the same router, It is working.

Not working only if connect via IP address...

**Comment by nrlquaker** [comment]
Strange. Works fine for me when I connect via ip.
Can you add log when you start app via CLI?

**Comment by nrlquaker** [comment]
And please try entering:
```
/Applications/Winbox-mac.app/Contents/Resources/wine/bin/wine64 /Applications/Winbox-mac.app/Contents/Resources/winbox64.exe/
```
And check if it works as expected.

**Comment by ivanblack19** [comment]
have same issue
here is 
`/Applications/Winbox-mac.app/Contents/Resources/wine/bin/wine64 /Applications/Winbox-mac.app/Contents/Resources/winbox64.exe/`

execution log

```
Applications/Winbox-mac.app/Contents/Resources/wine/bin/wine64 /Applications/Winbox-mac.app/Contents/Resources/winbox64.exe/
0009:fixme:esync:do_esync eventfd not supported on this platform.
000b:fixme:esync:do_esync eventfd not supported on this platform.
000b:fixme:winediag:__wine_start_process Wine Staging 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
000d:fixme:esync:do_esync eventfd not supported on this platform.
000f:fixme:esync:do_esync eventfd not supported on this platform.
0012:fixme:esync:do_esync eventfd not supported on this platform.
0019:fixme:esync:do_esync eventfd not supported on this platform.
0020:fixme:esync:do_esync eventfd not supported on this platform.
0026:fixme:esync:do_esync eventfd not supported on this platform.
0028:fixme:esync:do_esync eventfd not supported on this platform.
002a:fixme:esync:do_esync eventfd not supported on this platform.
000d:err:menubuilder:init_xdg error looking up the desktop directory
0009:fixme:font:update_font_info there is no font defaults for codepages 0,0
creating Window Class routeros_null
creating Window Class routeros_connect
DPI=96
EMS=13
ERROR: bad bmp format id=2329
biPlanes=1, biBitCount=1, biCompression=0
ERROR: bad bmp format id=3329
biPlanes=1, biBitCount=1, biCompression=0
creating Window Class routeros_dbl_canvas
rescaleDPI starting-dpi=96, zoom=0 result=96
 discovery started
rescaning
0009:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
connecting to 127.255.255.255
connecting to 192.168.10.255
0009:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv6 not supported in this platform
0009:fixme:winsock:WS_setsockopt Unknown IPPROTO_IPV6 optname 0x0000000c
IPV6_ADD_MEMBERSHIP: 1004
loadConfig C:\users\AleksandrSlobodanyuk\Application Data\Mikrotik\Winbox\Addresses.cdb
rescaning
connecting to 127.255.255.255
connecting to 192.168.10.255
0009:fixme:winsock:WS_setsockopt Unknown IPPROTO_IPV6 optname 0x0000000c
IPV6_ADD_MEMBERSHIP: 1004

```

but Still if I try to access MKT by IP MacOs BigSur is rebooted

**Comment by nrlquaker** [comment]
What device is it? Is it new M1 device?

**Comment by ivanblack19** [comment]
No , it is MBP pro 15 2017

**Comment by TwadaCZ** [comment]
I have MacBook Pro 15 - 2017 too...

I try to search in some Apple forums in Czech...and saw few more posts about same problem (not only with nrlquaker-winbox but with version from Joshaven and one more)...

there is link with "video" what I see on my screen with "full log"...

https://we.tl/t-4vZp35ud4L <https://we.tl/t-4vZp35ud4L>

Thank you for your "work" with "MacBox"...our "network admins" world is easier because of you...

--
Tvaruzek Vladislav

**Comment by TwadaCZ** [comment]
I recorded notebook screen on my phone...because there is "bigger" log on terminal before "system down" :-)

Because, when I click connect via IP...system will crash immediately...and after recovering terminal, some "log" informations are missing.

I wil try to upgrade to BigSur my second notebook today...It is MacBook 12"...and we will see, if will be happened on this hardware...

If I want to help you, please tell me...

Thank you,

**Comment by TwadaCZ** [comment]
I am upgraded my second notebook (MacBook 12") to macOS BigSur...and here WinBox working well...

May be there is problem at MacBook Pro for another HW configuration?

**Comment by TwadaCZ** [comment]
I upgraded my second MacBook 12"...

I was littlebit happy, because WinBox looks like working normal...

But not... After reboot my notebook, WinBox work OK and will connect via IP address to my any MikroTik router. But when I close connection and want to connect to another router...system will crash again...

Something is not good... :-(

Same situation is if I wait few minutes after rebooting my notebook and try to connect to any router...system will crash.

When I am reboot macOS BigSur to "safe mode"...WinBox working normal all the time...

My be it is crashed because any service or something will be started in "normal mode"...

**Comment by chriscareycode** [comment]
I also experience this app crashing the entire system with Big Sur

**Comment by tarakanof** [comment]
Same problem with Macbook pro 16

**Comment by MindaugasStankevicius** [comment]
The problem exist using MacBook Air 2015 - system crash.
But on MacBook Pro 2019 works well.

**Comment by nrlquaker** [comment]
Seems like its a `wine` issue. Please report it to their [bugtracker](https://bugs.winehq.org/describecomponents.cgi).

**Comment by TwadaCZ** [comment]
Yes, I am thinkg that the problem is with something in Wine...I will try to report there. Thx.

**Comment by TwadaCZ** [comment]
> Seems like its a `wine` issue. Please report it to their [bugtracker](https://bugs.winehq.org/describecomponents.cgi).

OK...I made some investigation...

I try different versions of Wine (Wine 5.0, Wine-Stagging 5.7)...Start WinBox from terminal...and result was the same. System Crashed.

Now I try to make "clean" installation of macOS BigSur on my MacBook Pro 15"...and this last version of WinBox working OK and there is not problem with crashing system.

I see, there is some problem after upgrade to Big Sur from Catalina. May be some "old" driver for any other app? I will try to install back all my apps...and we will see, what will happened. And will write here?

**Comment by TwadaCZ** [comment]
hmm...I have resolution of this problem...

I am using Little Snitch firewall...and this problem is only if Little Snitch is started. I try to recovery application one by one...and problem is after Little Snitch was installed. Because of it is firewall for macOS. And in new Big Sur is some new kernel network API (or what is the name)...and if I install Little Snitch, problem is here... If I uninstall from system, WinBox working OK.

I wrote ticket to Little Snitch support about this problem.

Thank you.

**Comment by nrlquaker** [comment]
@TwadaCZ thanks for investigation. Closing because its not a `Winbox-mac` issue.

**Comment by ivanblack19** [comment]
But I do not use Littlec snitch

**Comment by nrlquaker** [comment]
Thread on official forum: https://forum.mikrotik.com/viewtopic.php?f=2&t=168929

**Comment by binbash12** [comment]
Seems to work fine on Big Sur with Little Snitch installed so long as the Network Filter is disabled. I haven't taken the time to troubleshoot further, but will update this thread with anything I find.
