### ISSUE TITLE
Resizing and menus not working on M1-macs

### ISSUE THREAD

**Issue by ndit-dev** [nrlquaker/winbox-mac#59]
It starts up fine and seems to work at first look.

But resizing does not work, and the File/Tool-menu does not show up.
Using the arrow keys it's possible to for example open cbx-file. 

Is it a wine-error maybe?

screen shots: https://imgur.com/a/PpDjEGC

**Comment by nrlquaker** [comment]
Its wine [issue](https://bugs.winehq.org/show_bug.cgi?id=48896). Please post in the linked issue.

**Comment by fanvinga** [comment]
It seems to fixed in latest release 3.28.0
