### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by Gcenx** [nrlquaker/winbox-mac#60]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
It's really a wine issue due to Apple Silicon.

**To Reproduce**
Launch on Apple Silicon device and wine won't display anything.

**Expected behavior**
Winebox won't display on Apple Silicon as wine will be unable to find a usable GPU.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macOS version: 11.1
 - macOS language English
 - Winbox-mac version 3.27.0
 - Winbox version 3.27

**Additional context**
To make you aware that winebox-mac won't function on Apple Silicon devices, what versions of macOS are you intending to support as there is a patch to get this working but it might result in only supporting macOS High Sierra and above (need to confirm later but it seems to be the case)

**Comment by nrlquaker** [comment]
Thanks for the info @Gcenx. Can you please provide the link to the patch or info about it?

**Comment by Gcenx** [comment]
I can’t currently link to the patch, what it does is replaces the current GPU detection code with another method that requests the information from Metal. So wine needs to be compiled from source fo this to be usable.

I do have a prebuilt package of wine-6.0-rc3 that has the patch applied thats functional on macOS Mojave and Apple Silicon (macOS Bis Sur 11.1)

**Comment by gnattu** [comment]
@Gcenx Can you add that to your tap or release it somewhere? I cannot find the patch anywhere.

**Comment by Gcenx** [comment]
@gnattu it would be better having that conversation on [homebrew-wine](https://github.com/Gcenx/homebrew-wine)

**Comment by vidaren** [comment]
FWIW, I was able to get this working with a custom build of the latest Wine from git, where I replaced /dlls/winemac.drv/cocoa_display.m with [this version](https://github.com/Gcenx/winecx/blob/aa672f66aa23729f7a5379a7b12fb26bfd445c06/dlls/winemac.drv/cocoa_display.m) (had to comment out [the new ```#include```](https://github.com/Gcenx/winecx/blob/aa672f66aa23729f7a5379a7b12fb26bfd445c06/dlls/winemac.drv/cocoa_display.m#L28) for it to build). I also added [this block](https://github.com/Gcenx/winecx/blob/d9f33884e6a4634ffd8789c2b2a15770f568aa1b/loader/preloader_mac.c#L57-L66) to loader/preloader_mac.c -- not sure that was necessary.
I hope that narrows it down a little: it seems only the GPU detection must be updated.

**Comment by Gcenx** [comment]
@vidaren way ahead of you on that, I’ve instead turned the needed sections into patches that cleanly apply onto Upstream wine, the current remaining issue is getting DXVK running via the custom MoltenVK as it seems some other hacks are needed
![EE44299E-36F0-48C2-A774-D4F79989A8E4](https://user-images.githubusercontent.com/38226388/103033977-d5589b00-4531-11eb-98d8-b35d4d817b78.png)

**Comment by vidaren** [comment]
@Gcenx Right, you're doing it the proper way, while I just wanted Winbox to work on my M1 Mac Mini. 😃 
If anyone's interested in studying / testing what I did, or just getting Winbox working on their shiny new Mac, I have packaged my patch and the modified Winebox-mac app here: https://wine.vidartysse.net/winbox-mac-patched-for-m1.zip

**Comment by Gcenx** [comment]
@vidaren as there interest in have wine64 working on rosetra2 within the packages I provide it’s best I do this as correctly as possible and hopefully not conflict with my other patches.

I can tell you that during my own testing I’m unable to load wine-6.0-rc2 or 3 within a 10.9VM that I usually do testing on.

Not sure if that also applies to actual hardware or just a VM related quirk as without the patch a compile I’d created on Mojave does indeed run in the 10.9VM

This was the reason for the question in the first post of what macOS versions is the intended target(s)

**Comment by guorenxi** [comment]
It can be run on Apple Silicon by installing via homebrew, But can not resize the windows size.

**Comment by Gcenx** [comment]
> It can be run on Apple Silicon by installing via homebrew, But can not resize the window.

While it can technically function with the provided wine package that’s old and doesn’t included additional upstream fixes nor does it include Rosetta2 related fixes.

**Comment by Gcenx** [comment]
@nrlquaker wine-6.1 now contains the required changes, so the question is would what wine package would be preferable for winbox?, stable (with patches), devel or staging?

This will be compiled from source with a very minimal set of dependencies (libpng & libfreetype) with a builtin workaround for [Bug 49199](https://bugs.winehq.org/show_bug.cgi?id=49199)

Meaning the following export can be removed.
https://github.com/nrlquaker/winbox-mac/blob/ec75970b942a446985013b879f480260bd043494/Winbox-mac.app/Contents/MacOS/winbox-mac#L4

**Comment by nrlquaker** [comment]
@Gcenx thanks for the update. Was busy so couldn't response faster.
It seems like [macOS](https://dl.winehq.org/wine-builds/macosx/download.html) version has no maintainer and no builds since 5.0 stable.
I see you have [Wine builds for macOS](https://github.com/Gcenx/macOS_Wine_builds). Are these builds you are talking about or you want to make custom one?
About what build (stable, staging or dev) is preferable I didn't remember why I've chosen staging. So, I guess I go with staging for now.

**Comment by Gcenx** [comment]
@nrlquaker no problem life/time zone differences.

I was planning on building a custom package for winbox to reduce the dylib footprint as my packages include tons of dependency and is growing each release to Malachi upstream wine as much as possible.

Sure I’ll use wine-staging-6.1, I don’t see much reason to wait for wine-staging-6.2.

**Comment by Gcenx** [comment]
@nrlquaker this would be resolved with #65

**Comment by nrlquaker** [comment]
@Gcenx thanks for the contribution!
I've merged your PR. Got one question. Can this line be removed as you mentioned earlier?

> https://github.com/nrlquaker/winbox-mac/blob/ec75970b942a446985013b879f480260bd043494/Winbox-mac.app/Contents/MacOS/winbox-mac#L4

**Comment by nrlquaker** [comment]
@Gcenx one more question. There are `libwine.1.dylib` and `libwine.1.0.dylib` libraries in `lib64`. Are they needed? You said only `libpng` & `libfreetype` are needed.

**Comment by Gcenx** [comment]
@nrlquaker

Yes that line can be removed, but leaving it in would be useful incase someone else does a build in the future and doesn’t deal with dlopen()

libwine dylibs are part of wine so I didn’t mention those sorry for any confusion.

**Comment by nrlquaker** [comment]
Thanks for clarification.
