### ISSUE TITLE
Problem with Addresses.cdb

### ISSUE THREAD

**Issue by WojRep** [nrlquaker/winbox-mac#61]
**Checklist**

- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ x] I made sure this is not the original Winbox issue.

**Describe the bug**
The saved data file is created in $HOME/Download/Addresses.cdb
This is problematic due to directory cleaning. Deleting the file results in deleting the saved login data.

**To Reproduce**
Go to $ HOME / Download and delete the file Addresses.cdb

**Expected behavior**
The file with remembered connections should be saved in a more secure place. Folder that is not cleaned by various disk space management programs. Data is too easy to lose.
The location of this file should also be resistant to software updates.
**Screenshots**
---

**Desktop (please complete the following information):**
 - macOS version: [10.15.6]
 - macOS language [Polish]
 - Winbox-mac version [v3.27]
 - Winbox version [ - - - ]

**Additional context**

**Comment by nrlquaker** [comment]
The `Addresses.cdb` file is by default in `WINEPREFIX` which is located under `$HOME/Library/Application Support/com.mikrotik.winbox`.  But you can open the other one using `File->Open..`. In this case the open file will be used every time you launch `Winbox-mac`.

**Comment by WojRep** [comment]
Hello

 

 

You didn't understand my problem. I'm enclosing the movie. The file w / MaxOS HD / Users / username / Download creates itself at startup. ("Downloads" = "Downloads")

 

 

Wojciech Repiński 

 

Od: nrlquaker <notifications@github.com>
Odpowiedź do: nrlquaker/winbox-mac <reply@reply.github.com>
Data: czwartek, 24 grudnia 2020 22:47
Do: nrlquaker/winbox-mac <winbox-mac@noreply.github.com>
DW: WojRep <wrepinski@gmail.com>, Author <author@noreply.github.com>
Temat: Re: [nrlquaker/winbox-mac] Problem with Addresses.cdb (#61)

 

The Addresses.cdb file is by default in WINEPREFIX which is located under $HOME/Library/Application Support/com.mikrotik.winbox. But you can open the other one using File->Open... In this case the open file will be used every time you launch Winbox-mac.

**Comment by nrlquaker** [comment]
@WojRep there is no movie in your post.

**Comment by WojRep** [comment]
I can see the file has been rejected. I am sending a link to the dropbox.

 

https://www.dropbox.com/s/mp2mv99x6w5a37k/Nagranie%20ekranu%202020-12-25%20o%2013.56.32.mov?dl=0  

 

 

 

Wojciech Repiński 

 

Od: nrlquaker <notifications@github.com>
Odpowiedź do: nrlquaker/winbox-mac <reply@reply.github.com>
Data: piątek, 25 grudnia 2020 14:44
Do: nrlquaker/winbox-mac <winbox-mac@noreply.github.com>
DW: WojRep <wrepinski@gmail.com>, Mention <mention@noreply.github.com>
Temat: Re: [nrlquaker/winbox-mac] Problem with Addresses.cdb (#61)

 

@WojRep there is no movie in your post.

**Comment by nrlquaker** [comment]
Sorry for the delay, but Its working like I described. I think you just opened another file.
If you want to reset to default save you `Addresses.cdb`, run:
```
brew cask zap nrlquaker-winbox
brew install nrlquaker-winbox
```
then put you `Addresses.cdb` here `~/Library/Application Support/com.mikrotik.winbox/drive_c/users/$USER/Application Data/Mikrotik/Winbox`
