### ISSUE TITLE
Trojan detected by bitdefender

### ISSUE THREAD

**Issue by donatid** [nrlquaker/winbox-mac#64]
Hi,

I already download and extract your file but it's detected contains trojan.
Can you explain that?

Thank you

**Comment by nrlquaker** [comment]
Hello.
There [were](https://github.com/nrlquaker/winbox-mac/issues/46) [some](https://github.com/nrlquaker/winbox-mac/issues/47) [similar](https://github.com/nrlquaker/winbox-mac/issues/52) [issues](https://github.com/nrlquaker/winbox-mac/issues/55) before.
You can them for more details.
Its most likely false positive.
