### ISSUE TITLE
ERROR: RoMON Agent not found. Add it to Manage List

### ISSUE THREAD

**Issue by iNaiks** [nrlquaker/winbox-mac#66]
Hi, 
I've the problem with RoMON agent not found.

How can I solve it?

Thanks Nico

**Comment by nrlquaker** [comment]
Fill in template next time. Its not a `winbox-mac` issue.
Check official forums. For example [here](https://forum.mikrotik.com/viewtopic.php?t=110213).

**Comment by iNaiks** [comment]
![Captura de pantalla 2023-05-06 a las 10 50 35](https://user-images.githubusercontent.com/72868890/236613917-6f1d15bf-345c-485e-b737-734edf24c61d.png)
 
 In my Mac appear the error

**Comment by iNaiks** [comment]
![Captura de pantalla 2023-05-06 a las 10 51 45](https://user-images.githubusercontent.com/72868890/236613948-b5f87fe8-d759-4e42-93df-0826b72b810f.png)
In my mac appear the error
