### ISSUE TITLE
Neighbors tab won't find devices

### ISSUE THREAD

**Issue by adilinden** [nrlquaker/winbox-mac#68]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
The app will not discover any devices via the "Neighbors" tab.

**To Reproduce**
1. Go to 'Neighbors' tab
2. Click on 'Refresh'
3. Nothing is populated

**Expected behavior**
A list of Mikrotik devices on the same LAN segment

**Screenshots**
<img width="777" alt="Screen Shot 2021-05-18 at 10 42 07 PM" src="https://user-images.githubusercontent.com/1149715/118753307-52aae200-b82a-11eb-829b-a96b6994bab0.png">

**Desktop (please complete the following information):**
 - macOS version: 11.2.3
 - macOS language English
 - Winbox-mac version 3.27.1
 - Winbox version 3.27

**Additional context**
If I enter the MAC address in the "Connect to" field it connects just fine. If I enter the IP address in the "Connect to" field it connects just fine. Just the neighbor discovery fails. I can run Winbox in Windows and it does work as it should.

**Comment by nrlquaker** [comment]
Please check this [comment](https://github.com/nrlquaker/winbox-mac/issues/26#issuecomment-560074763).

**Comment by adilinden** [comment]
It works fine on Windows, but not on MacOS. It would argue that this wouldn’t make it a Winbox issue but related to how it is run on MacOS.

**Comment by helmarw** [comment]
nope, works perfectly on macOS 11.3 & winbox-mac 3.27
i would assume some problem with network configuration, firewall etc ?!

**Comment by nrlquaker** [comment]
Is the interface enabled in the "discovery settings" in IP -> Neighbors?
If yes I think its network configuration/firewall issue.
