### ISSUE TITLE
Window settings are not saved

### ISSUE THREAD

**Issue by hunter-nl** [nrlquaker/winbox-mac#7]
Start a session with a mikrotik device. Change the window size, set Dashboard (Time, CPU, etc) to display, set Settings - Inline comments.
Autosave on Close is enabled. (even done with explicit save). These settings are not stored and when I reconnect after close, I got the default window size and settings.
Inside the main session window the sub view windows "customisations" are also not saved. So I have to change the column width, window sizes, etc again and again.

Latest brew version in use, fresh install of winbox-mac. Running on Mojave 10.14.2

**Comment by Justintime50** [comment]
I haven't had this issue with Winbox on Mac. All of my settings save. Used MikroTik 3.18 and 3.19 on Mojave and High Sierra. Have you tried updating to the latest version of Winbox? @hunter-nl

**Comment by hunter-nl** [comment]
Even the upgrade to 3.19 will not be stored.

**Comment by nrlquaker** [comment]
@hunter-nl, sorry for a delay.
Issue is fixed in the latest release.
You can download it from [Releases](https://github.com/nrlquaker/winbox-mac/releases).
Or install using `brew cask` when https://github.com/Homebrew/homebrew-cask/pull/66239 will be merged:
```
brew update
brew cask upgrade winbox-mac
```
