### ISSUE TITLE
Since Wine 3.17 it's possible to map Command as Ctrl meaning CMD+C/CMD+V now functions like Native applications

### ISSUE THREAD

**Issue by yienzhu** [nrlquaker/winbox-mac#71]
I try is work

WINEPREFIX="/Users/$(whoami)/Library/Application Support/com.mikrotik.winbox" /Applications/Winbox-mac.app/Contents/Resources/wine/bin/wine64 reg add "HKEY_CURRENT_USER\Software\Wine\Mac Driver" /v "LeftCommandIsCtrl" /t REG_SZ /d "y"

https://wiki.winehq.org/MacOS_FAQ

**Comment by Gcenx** [comment]
To force this configuration it’s better to have this set directly within https://github.com/nrlquaker/winbox-mac/blob/master/Winbox-mac.app/Contents/Resources/wine/share/wine/wine.inf

You should change all the options listed under https://wiki.winehq.org/MacOS_FAQ#How_come_my_keyboard_shortcuts_don.27t_work_like_normal or you’ll have other issues.

**Comment by nrlquaker** [comment]
I'll give a look and add this as default behaviour.
Thanks for advice.

**Comment by vidaren** [comment]
I tested, adding this to [the [Misc] section of wine.inf](https://github.com/nrlquaker/winbox-mac/blob/master/Winbox-mac.app/Contents/Resources/wine/share/wine/wine.inf#L715):

```
; Keyboard mapping
HKCU,Software\Wine\Mac Driver,"LeftOptionIsAlt",2,"Y"
HKCU,Software\Wine\Mac Driver,"RightOptionIsAlt",2,"Y"
HKCU,Software\Wine\Mac Driver,"LeftCommandIsCtrl",2,"Y"
HKCU,Software\Wine\Mac Driver,"RightCommandIsCtrl",2,"Y"
```

I don't see any downside to adding all four mappings. The Option key lets me use Winbox menus without a mouse.

**Comment by nrlquaker** [comment]
Done. Will be in the next release.

**Comment by nrlquaker** [comment]
Done. You can grab the latest release [here](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.28.1).

**Comment by yienzhu** [comment]
Cool thank you
