### ISSUE TITLE
HiDPi font replacements

### ISSUE THREAD

**Issue by xandrman** [nrlquaker/winbox-mac#72]
In Linux wine I changed fonts in wine from Segoe UI to Roboto and from Courier New to Ubuntu Mono.
With that action winbox looks good in HiDPi, console too and logs too.
Would you try it on mac?
![2021-06-18_19-49](https://user-images.githubusercontent.com/24395753/122571687-cda42a00-d06e-11eb-80e6-d4c44653414b.png)

**Comment by nrlquaker** [comment]
Thanks for suggestion.
Please tell me how to change fonts in wine.

**Comment by xandrman** [comment]
Navigate to HKEY_CURRENT_USER\Software\Wine\Fonts\Replacements in the Wine registry editor.
Create a new string value called Segoe UI, and set its value to Roboto.
Create a new string value called Courier New, and set its value to Ubuntu Mono.

Naviagte to HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes.
Change string called MS Shell Dlg to Roboto. 
Change another string called MS Shell Dlg 2 to Roboto.

But I don't know is it works on MacOS.

**Comment by nrlquaker** [comment]
I've downloaded [Roboto](https://fonts.google.com/specimen/Roboto) and [JetBrains Mono](https://www.jetbrains.com/lp/mono/) (instead of Ubuntu) extracted and copied their Regular versions to  `Winbox-mac.app/Contents/Resources/wine/share/wine/fonts/`.
Added
```
HKCU,Software\Wine\Fonts\Replacements,"Segoe UI",,"Roboto"
HKCU,Software\Wine\Fonts\Replacements,"Courier New",,"JetBrains Mono"
HKLM,Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes,"MS Shell Dlg",,"Roboto"
HKLM,Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes,"MS Shell Dlg 2",,"Roboto"
```

to `wine.inf`.
But nothing have changed in the app.
@Gcenx maybe you can help?

**Comment by xandrman** [comment]
Maybe it will works when you enabled retina mode?

**Comment by nrlquaker** [comment]
Its enabled.

**Comment by Gcenx** [comment]
@nrlquaker font replacement work with already installed system fonts I don’t believe you can just drop custom fonts into wines font directory and have them work. You should be able to use a macOS provided font and that should work without issue.

@xandrman retina mode is not related to this.

**Comment by xandrman** [comment]
Deleted Courier New from system with disabled system protection on High Sierra, wine from brew. Fonts are thinner than on Linux
![Uploading macos.png…]()

**Comment by Gcenx** [comment]
@xandrman could you explain why you deleted a system font?

When you say you installed wine via brew did you use the ancients casks or my tap?

**Comment by nrlquaker** [comment]
Closing for now. There is no an easy way to implement it.
Feel free to open PR if you have a solution.
