### ISSUE TITLE
3.28.1 horrible screen style, mousepointer clicking different options, retina issue

### ISSUE THREAD

**Issue by si458** [nrlquaker/winbox-mac#73]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
updated to 3.28.1 on my laptop and noticed the whole styling changed,
connected to a site but then im not able to click menus etc because the window size is small,
so enlarged the window screen and then im still not able to click options?
open say interfaces and cant click the close button on them?
it also seems the mouse pointers is completely off when you full screen the app or try and make the app bigger
e.g: i click logs and it then clicks terminal?

**To Reproduce**
1. use 3.28.1 and get all these issues,
2. use 3.28.0, no issues at all...

**Expected behavior**
to use the app as its unusable now

**Screenshots**
![Screenshot 2021-06-26 at 21 54 57](https://user-images.githubusercontent.com/765314/123525591-c4980600-d6c9-11eb-892b-3b22214aa07f.png)
![Screenshot 2021-06-26 at 21 55 44](https://user-images.githubusercontent.com/765314/123525594-c6fa6000-d6c9-11eb-8766-7817b341ccfb.png)

**Desktop (please complete the following information):**
 - macOS version: 10.15.7
 - macOS language English
 - Winbox-mac version 3.28.1
 - Winbox version 3.28.0

**Additional context**

**Comment by nrlquaker** [comment]
Have you checked the note to [release](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.28.1)?

**Comment by si458** [comment]
@nrlquaker yes i have already tried empting the application support folder, still doesnt work
i believe its the retina issue (even tho i have a retina macbook pro) https://github.com/nrlquaker/winbox-mac/commit/9785f464fbb7e3fed2e6c8067c42018e69a40087

**Comment by si458** [comment]
OMG I FEEL SO EMBARASSED! PLEASE IGNORE ME AND IM SO SO SORRY!

**NOTE TO OTHER PEOPLE:**
**YOU MUST CLOSE AND RUN THE APP TWICE AFTER DELETING THE APPLICATION SUPPORT FOLDER!**
**FOR SOME REASON ON THE FIRST RUN, WHEN YOU RESIZE THE APPLICATION STUFF DOESNT WORK**
**BUT IF YOU THEN CLOSE THE APP FULLY AND RE-RUN IT, IT WORKS NO PROBLEM!**
