### ISSUE TITLE
Open multiple Sessions / Windows

### ISSUE THREAD

**Issue by Bambie07** [nrlquaker/winbox-mac#75]
When setting up tunnels I need to use winbox on both ends of this tunnel. Is it possible to open Winbox multiple times or with multiple windows? When clicking on session -> New nothing happens.

If I remember correctly on some point this worked. Opening another Session created a second icon in the dock with the "windows icon" instead of the mac windows icon.

**Comment by nrlquaker** [comment]
Not sure if its possible.
Maybe something changed in wine.
@Gcenx any ideas?

**Comment by Gcenx** [comment]
> Not sure if its possible.
> Maybe something changed in wine.
> @Gcenx any ideas?

Not sure, need to see if there’s any terminal output indicating and issue or if Winbox just opens itself again to accomplish this.

**Comment by nrlquaker** [comment]
No terminal output for me.

**Comment by Gcenx** [comment]
@nrlquaker you’d need to launch winbox windows binary outside of winbox-mac.app ether using the bundled custom build or alternative use one of my prebuilt packages from [macOS_Wine_builds](https://github.com/Gcenx/macOS_Wine_builds), wine-stable-6.0.1 would be close enough to the build I’d provided or grab the latest wine-devel package that’s uploaded (6.14 won’t be up until tomorrow at the earliest)

**Comment by si458** [comment]
@Bambie07 you need to tick the box saying 'Open in New Window' before connecting to your routers
this opens the session for one router in another process
but leaves the addresses list open for you to then open another session to another router
i have 4 open at once haha

**Comment by nrlquaker** [comment]
@si458 thanks for the info.
