### ISSUE TITLE
Errors with brackets (curly and square)

### ISSUE THREAD

**Issue by mirkoglisenti** [nrlquaker/winbox-mac#76]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
When you try to insert square or curly brackets from the keyboard, winbox does not insert them and the mac emits the classic error sound (which usually determines a command / character that cannot be inserted)

**To Reproduce**
1. Open winbox-mac
2. Try to insert curly or square brackets in any window of application

**Expected behavior**
I would expect the curly and square brackets to fit safely into any winbox screen

**Desktop (please complete the following information):**
 - macOS version: 11.4
 - macOS language: Italian
 - Winbox-mac version: 3.28.1
 - Winbox version: 3.28

**Comment by nrlquaker** [comment]
Working fine here. Can you provide more details how to reproduce the issue?

<img width="667" alt="Screenshot 2021-07-28 at 22 52 23" src="https://user-images.githubusercontent.com/2573638/127386888-bc43fc3a-401e-4591-a4de-2580c0f84b10.png">

**Comment by mirkoglisenti** [comment]
I think my problem is related to some sort of error with the keyboard layout (I use the Italian keyboard and when I click on the option key + è (the bracket [in the Italian keyboard layout) I hear the classic sound that MacOS makes when an incorrect or non-existent combination of keys is pressed, a bit as if the option key is not recognized as the windows altgr key in winbox).

However this is very strange because until the previous version of winbox-mac I didn't have any similar problems, only from the latest version these problems appeared.

Seeing the latest update released I saw that the option key has been mapped with the alt key, I think the problem may be due to this as on Italian keyboards the correct key to click is altgr and not alt to have the curly and square brackets.

Thank you for your support and your time.

Have a good day

**Comment by nrlquaker** [comment]
I don't have time to support non-English locales. If someone wants please make a PR.
