### ISSUE TITLE
The latest version of Chinese garbled code

### ISSUE THREAD

**Issue by wumingbin** [nrlquaker/winbox-mac#77]
The latest version of Chinese garbled code。
wine 5.2 normal

<img width="1076" alt="iShot2021-07-18 18 16 25" src="https://user-images.githubusercontent.com/11347453/126063615-5d078702-88c7-4c88-b8ae-5491aee9901b.png">

**Comment by wumingbin** [comment]
Began in v3.24.1(update Wine to staging 5.7)

**Comment by nrlquaker** [comment]
Its seems like executable file is modified.
https://github.com/nrlquaker/winbox-mac/blob/2b11af9a9ad1b584aa8466b0626586ad63258a18/Winbox-mac.app/Contents/MacOS/winbox-mac#L3

Why so?

**Comment by wumingbin** [comment]
It needs to be used in the Chinese system

**Comment by Gcenx** [comment]
Would have been nice to see a good and bad screenshot.

Also if that happened back around wine-5.7 that’s a regression from over a year ago within upstream wine.

It might be a good idea to test the latest wine-devel to see if that’s still an issue, you can grab the latest prebuilt from [macOS_Wine_builds](https://github.com/Gcenx/macOS_Wine_builds)

But I have a feeling that Chinese fonts just need to be installed into the wineprefix.

**Comment by nrlquaker** [comment]
I don't have time to support non-English locales. If someone wants please make a PR.
