### ISSUE TITLE
Can't run on MacOS 12 Monterey

### ISSUE THREAD

**Issue by FER00Z** [nrlquaker/winbox-mac#78]
**Checklist**

- [✔️] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ ✔️] I made sure this is not the original Winbox issue.

**Describe the bug**
Can't run on MacOS 12.0 Beta (21A5284e)

**To Reproduce**
1. Upgrade to MacOS 12 Monterey
2. Install Winbox-mac
3. Run
4. See an error in the screenshots below
![image](https://user-images.githubusercontent.com/49568574/126788470-22d9f54d-fb8e-4c61-b1b5-d30ddeb84e34.png)
![image](https://user-images.githubusercontent.com/49568574/126788636-783f08e1-4c32-4b07-a9a4-8d55850915ba.png)

**Expected behavior**
I've tried to upgrade the brew, reinstall the cask. But I understand that the issue is with the compatibility of Wine on Monterey. Even brew is not fully compatible with MacOS 12.
![image](https://user-images.githubusercontent.com/49568574/126789171-96f7f3fa-ca60-4464-a405-83d835060151.png)

**Desktop (please complete the following information):**
 - macOS version: Monterey 12.0 beta (21A5284e)
 - macOS language: English
 - Winbox-mac version: 3.28
 - Winbox version: 3.28.1

**Comment by nidr0x** [comment]
Same issue here.

**Comment by xyzroe** [comment]
I also have

**Comment by Gcenx** [comment]
I should have opened an issue ahead of time for this sigh…..

macOS Monterey changed how thread 0 functions, CodeWeavers are waiting on a fix from Apple alternatively a patch from CodeWeavers.

**Comment by tthoma24** [comment]
Not sure why this is closed if this is an active issue?

Interestingly, I don't have this issue if I install crossover-wine from MacPorts and run Winbox that way. Is there something different with the way this project runs Winbox?

**Comment by Gcenx** [comment]
@tthoma24 see #79 

Not sure how winbox could be working using Macports wine-crossover package on macOS Monterey when that won’t even build since macOS High Sierra and there Port is based on an ancient version of crossover.

**Comment by FER00Z** [comment]
> Not sure why this is closed if this is an active issue?
> 
> Interestingly, I don't have this issue if I install crossover-wine from MacPorts and run Winbox that way. Is there something different with the way this project runs Winbox?

Could you please give more details?
versions of macos, is it Intel based or M1?

**Comment by arduino43** [comment]
Same issues on M1 mini and M1 air
