### ISSUE TITLE
Is there a way to install Winbox on M1 without installing homebrew?

### ISSUE THREAD

**Issue by kaihendry** [nrlquaker/winbox-mac#80]
**Is your feature request related to a problem? Please describe.**
Install home brew takes a lot of time and Xcode install IIRC

**Describe the solution you'd like**
A binary

**Describe alternatives you've considered**
Buying a Windows machine

**Comment by nrlquaker** [comment]
Just download binary from [releases](https://github.com/nrlquaker/winbox-mac/releases).
There are no dependencies.
