### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by gkl1368** [nrlquaker/winbox-mac#81]
Pls help to upgrade to winbox v3.29. Thanks.

**Comment by nestyurkin** [comment]
works fine %)
<img width="923" alt="Снимок экрана 2021-09-03 в 16 22 02" src="https://user-images.githubusercontent.com/16364441/132012161-e46d69fc-5780-4c75-87be-5176f755c571.png">

**Comment by nrlquaker** [comment]
Will update on the weekend. Thanks for the info.

**Comment by MattKobayashi** [comment]
> works fine %)

It _kinda_ works on my machine, but it's pretty buggy. I don't recommend going down this path.

**Comment by Gcenx** [comment]
I really recommend avoiding using the builtin update function as the provided `wine64` compile wasn’t built with nor makes use of gnutls for secure connections as this would have increased the package size substantially. Also brew formula _can’t_ be used reliably for this, they would need be bundled along with all required dependencies.

**Comment by si458** [comment]
@nrlquaker did you have change to update the app?

**Comment by si458** [comment]
@nrlquaker the is a new version of v3.30 now...

**Comment by nrlquaker** [comment]
Sorry for the wait. Updated to v3.30. Get it from [Releases](https://github.com/nrlquaker/winbox-mac/releases/tag/v3.30.0) or wait for this [PR](https://github.com/Homebrew/homebrew-cask/pull/111309) to be merge if you use `brew`.

**Comment by si458** [comment]
@nrlquaker brilliant thank you! works a treat! 👍
