### ISSUE TITLE
Can you make disable retina for non-retina macs?

### ISSUE THREAD

**Issue by 1o1o1** [nrlquaker/winbox-mac#84]
I allways have to disable retina mode in wine.inf for my macbook air 2015 with new version winbox-mac

; Retina mode                                                                                                                                         
#HKCU,Control Panel\Desktop,"LogPixels",0x10003,0x000000C0                                                                                            
#HKCU,Software\Wine\Mac Driver,"RetinaMode",2,"Y"  

and to fix normal size font in user.reg 
"LogPixels"=dword:00000060

can you make something with it?  autodetect non-retina macs?  :)

**Comment by ntinti** [comment]
Thank you 1o1o1 - I also have to buy a magnifying glass for that ...

**Comment by Gcenx** [comment]
The primary binary is a bash script see
https://github.com/nrlquaker/winbox-mac/blob/eb99d41dbbbf787fe4ae7911930dd80894ee0ce0/Winbox-mac.app/Contents/MacOS/winbox-mac#L1-L19

So if someone wants to add something to check for a Retina display then modify the bundled wine/created prefix and open a PR that would help a lot.

I’m not aware of any third-party wine GUI that’s does what your asking.

**Comment by belykhk** [comment]
Something like this could do the trick for retina display check:

`if [[ $(system_profiler SPDisplaysDataType | grep -i 'retina') ]]; then echo "Retina display found"; else echo "No retina display found"; fi`

Problem is — if you have multiple displays and one of them is retina-capable and another is not — this oneliner will output that your display is retina-capable

**Comment by nrlquaker** [comment]
Latest non retina mac is pretty much old. More than 5 years old. I don't have intention to waste time for its support. But if someone has working solution please open a PR.

**Comment by dobegor** [comment]
@nrlquaker I've stumbled upon this issue since my winbox doesn't work correctly on non-hidpi (2560x1440 27") external monitor - some UI controls have "wrong coordinates" - i.e. you click in one place, but the click registers itself in a different one. But it seems that it'd be near impossible to dynamically adjust this setting given the fact that user can move the window from one monitor to another.

**Comment by nrlquaker** [comment]
@dobegor yes, its impossible to dynamically adjust retina mode. You can create bug at [WINE HQ](https://bugs.winehq.org) for issue with click registration.
