### ISSUE TITLE
error program notification in macos bigsur

### ISSUE THREAD

**Issue by moehar** [nrlquaker/winbox-mac#87]
i have erro like this when run winbox for mac os

<img width="402" alt="Screen Shot 2021-11-11 at 22 31 21" src="https://user-images.githubusercontent.com/67137185/141325214-26833205-f4fe-40a1-83f3-6ce61e576461.png">

when click show details

Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00000003af6d5568).
Register dump:
 rip:00000003af6d5568 rsp:000000000031ee48 rbp:0000000000000000 eflags:00000246 (   - --  I  Z- -P- )
 rax:0000000000000000 rbx:0000000000000000 rcx:000000000000002e rdx:000000000000002e
 rsi:0000000000000000 rdi:000000000031f3d0  r8:000000000000160f  r9:0000000000000000 r10:0000000068100000
 r11:0000000068116240 r12:000000000031f5b0 r13:0000000000000001 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000000031ee48:  00000001400063a9 0000000000000000
0x000000000031ee58:  0000000000000000 0000000000000000
0x000000000031ee68:  0000000000002c00 0000000000000000
0x000000000031ee78:  0000000000020006 0000000000000000
0x000000000031ee88:  000000000031f5b0 0000000000000000
0x000000000031ee98:  0000000000000000 0000000000000000
0x000000000031eea8:  000000000031f3a0 0000000140009010
0x000000000031eeb8:  000000000031f190 000000007b630fc0
0x000000000031eec8:  000000000031ef80 000000000031ef30
0x000000000031eed8:  0000000000013200 000000007bc0dde0
0x000000000031eee8:  000000000031ef28 000000007bc2cc00
0x000000000031eef8:  0000000000000001 0000000000000000
Backtrace:
=>0 0x00000003af6d5568 (0x0000000000000000)
0x00000003af6d5568: movzbl	(%rax),%edx
Modules:
Module	Address					Debug info	Name (16 modules)
ELF	            2000-            6000	Deferred        <wine-loader>
PE	        68089000-        6808e000	Deferred        libwine.1.0.dylib
ELF	        68200000-        68287000	Deferred        ntdll.so
ELF	        68372000-        6838c000	Deferred        ucrtbase.so
ELF	        6d300000-        6d33c000	Deferred        ws2_32<elf>
  \-PE	        6d310000-        6d339000	\               ws2_32
PE	        7b000000-        7b0d5000	Deferred        kernelbase
PE	        7b600000-        7b7ca000	Deferred        kernel32
PE	        7bc00000-        7bc14000	Deferred        ntdll
ELF	        7d400000-        7d404000	Deferred        <wine-loader>
PE	       140000000-       140020000	Deferred        wineboot
PE	       330260000-       33026b000	Deferred        advapi32
PE	       3af670000-       3af68e000	Deferred        ucrtbase
PE	    7fff20430000-    7fff20460000	Deferred        libsystem_kernel.dylib
PE	    7fff20460000-    7fff2046c000	Deferred        libsystem_pthread.dylib
PE	    7fff204a8000-    7fff204b4000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio (all id:s are in hex)
00000020 ntdll.dll
	00000024    0
00000028 (D) C:\windows\system32\wineboot.exe
	0000002c    0 <==
0000003c explorer.exe
	00000040    0
	00000044    0
	00000048    0
System information:
    Wine build: wine-6.2
    Platform: x86_64
    Version: Windows 7
    Host system: Darwin
    Host version: 20.6.0

**Comment by nrlquaker** [comment]
Please fill it the template and provide steps to reproduce.

**Comment by moehar** [comment]
Sorry @nrlquaker, i don't understand what you mean about fill it the template, can you describe step-by-step, or more explain please

**Comment by nrlquaker** [comment]
When creating a bug there is a template.
Here it is:

```
**Checklist**

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [ ] I made sure this is not the original Winbox issue.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.14.5]
 - macOS language [e.g. English, Russian, Chinese]
 - Winbox-mac version [e.g. 3.18]
 - Winbox version [e.g. 3.18]

**Additional context**
Add any other context about the problem here.

```

**Comment by nrlquaker** [comment]
Not following [Reporting bugs](https://github.com/nrlquaker/winbox-mac#reporting-bugs). Closing.
