### ISSUE TITLE
Russian lang 

### ISSUE THREAD

**Issue by bazzelio** [nrlquaker/winbox-mac#88]
If I have Russian language description or commit I see "Áüþòè-áðåéê" and other font error. Can you help with this trouble 
<img width="105" alt="Снимок экрана 2021-11-16 в 23 26 44" src="https://user-images.githubusercontent.com/40030194/142060438-e90593ce-f979-4193-90e2-3f3ae11c2f03.png">
?

**Comment by nrlquaker** [comment]
Check #86
