### ISSUE TITLE
Long loading after Refresh

### ISSUE THREAD

**Issue by Thomas-Austria** [nrlquaker/winbox-mac#89]
**Checklist**

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [x] I made sure this is not the original Winbox issue.

**Describe the bug**
After Opening Winbox and hit the refresh button winbox is loading for 1-2min to resume 

**To Reproduce**
1. Click on 'refresh'
2. See loading 1-2min

**Expected behavior**
After Refreshing -> Show me the devices 

**Desktop (please complete the following information):**
 - macOS version: Monterey 12.0.1
 - macOS language German
 - Winbox-mac version 3.31.0
 - Winbox version 3.31.0

**Comment by nrlquaker** [comment]
@Thomas-Austria do you mean refresh button in the neighbours tab?

**Comment by Thomas-Austria** [comment]
Yes

**Comment by nrlquaker** [comment]
Please check #68 and #26. Seems like a firewall or interface configuration issue.
