### ISSUE TITLE
3.19 doesn't remember the status bar 

### ISSUE THREAD

**Issue by xh116** [nrlquaker/winbox-mac#9]
Thanks for your work moving winbox to Macos.
I just found the status bar(Uptime/Memory/Cpu/...) not remeber and I must add it everytime when openning it.
which 3.18 did good.

**Comment by nrlquaker** [comment]
@xh116 please fill in template.

**Comment by xh116** [comment]
**Describe the bug**
 winbox status bar will not show after system restart. 

**To Reproduce**
Steps to reproduce the behavior:
1. open winbox
2. right click to add uptime/cpu/memory'
3, status bar will disappear after system restart. 

**Expected behavior**
 status bar will not show after system restart. 

**Screenshots**
 
1,firstly add <img width="753" alt="QQ20190723-042718@2x" src="https://user-images.githubusercontent.com/37950502/61662992-2ee7e500-ad02-11e9-992e-11b4235be127.png">
2, after restart system 
<img width="752" alt="QQ20190723-043018@2x" src="https://user-images.githubusercontent.com/37950502/61663176-9aca4d80-ad02-11e9-9c5b-21a90f5dd061.png">


**Desktop (please complete the following information):**
 - macOS version: 10.14.5
 - Winbox-mac version 3.19
 

**Additional context**
winbox-mac 3.18 was good.

**Comment by xh116** [comment]
it seems my own system problem.  please delete it.
