### ISSUE TITLE
Upgrade to latest Winbox 

### ISSUE THREAD

**Issue by cmos486** [nrlquaker/winbox-mac#90]
With the latest versions of RouterOS, a more updated Winbox is required, it is appreciated to have the latest version if possible, or documentation on how to do it.

Thanks a lot!

**Comment by nrlquaker** [comment]
[mikrotik.com](https://mikrotik.com) is down for me atm. Will check later.

**Comment by nrlquaker** [comment]
`3.31` is the latest version [here](https://mikrotik.com/download).
