### ISSUE TITLE
Winbox version 3.31.0 error on Mac v 12.0

### ISSUE THREAD

**Issue by muchlisre** [nrlquaker/winbox-mac#91]
Winbox-mac not not running on MacOs Monterey version 12.0 beta.
Winbox version 3.31.0 of Cask nrlquaker-winbox

![mikrotik error](https://user-images.githubusercontent.com/35568119/147646567-14b14fd9-053a-43ab-bfed-ef267a0e093a.png)

`Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00000000004014c0).
Register dump:
 rip:00000000004014c0 rsp:000000010053fe38 rbp:0000000000000000 eflags:00000202 (   - --  I   - - - )
 rax:000000007bc7f050 rbx:0000000000000000 rcx:00007ffd01daf000 rdx:00000000004014c0
 rsi:0000000000000000 rdi:0000000000000000  r8:00007ffd01daf000  r9:000000007bc72820 r10:0000000000000000
 r11:0000000000000000 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000010053fe38:  000000007b62c779 0000000000000000
0x000000010053fe48:  0000000000000000 0000000000000000
0x000000010053fe58:  0000000000000000 0000000000000000
0x000000010053fe68:  000000007bc58b43 0000000000000000
0x000000010053fe78:  0000000000000000 0000000000000000
0x000000010053fe88:  0000000000000000 00000000004014c0
0x000000010053fe98:  00007ffd01daf000 ffffffffffffffff
0x000000010053fea8:  000000007bc62640 000000007bc286c0
0x000000010053feb8:  0000000000000000 000000010053fea0
0x000000010053fec8:  0000000000000000 000000010053fe70
0x000000010053fed8:  0000000000000000 0000000000000000
0x000000010053fee8:  0000000000000000 0000000000000000
Backtrace:
=>0 0x00000000004014c0 (0x0000000000000000)
0x00000000004014c0: lodsl	(%rsi)
Modules:
Module	Address					Debug info	Name (22 modules)
PE	         2610000-         261b000	Deferred        winspool
PE	         2ba0000-         2ba6000	Deferred        winemac
PE	         2f20000-         37f7000	Deferred        shell32
PE	        7b000000-        7b0d5000	Deferred        kernelbase
PE	        7b600000-        7b812000	Deferred        kernel32
PE	        7bc00000-        7bc98000	Deferred        ntdll
PE	       100110000-       10033f000	Deferred        winbox64
PE	       1c8db0000-       1c8e3d000	Deferred        msvcrt
PE	       21a7e0000-       21a854000	Deferred        setupapi
PE	       231ae0000-       231b62000	Deferred        rpcrt4
PE	       24f470000-       24f48f000	Deferred        mpr
PE	       2d4d40000-       2d4d56000	Deferred        bcrypt
PE	       2e3540000-       2e3591000	Deferred        shlwapi
PE	       2f1fa0000-       2f1fad000	Deferred        version
PE	       2f7230000-       2f725d000	Deferred        uxtheme
PE	       3126f0000-       312709000	Deferred        shcore
PE	       327020000-       327072000	Deferred        combase
PE	       32a700000-       32a729000	Deferred        sechost
PE	       330260000-       33029f000	Deferred        advapi32
PE	       3af670000-       3af728000	Deferred        ucrtbase
PE	       3afd00000-       3afd19000	Deferred        imm32
PE	       3be590000-       3be5fa000	Deferred        dbghelp
Threads:
process  tid      prio (all id:s are in hex)
00000020 (D) Z:\Applications\Winbox-mac.app\Contents\Resources\winbox64.exe
	00000024    0 <==
	00000118    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000050    0
	00000068    0
	00000080    0
	000000ac    0
	000000f0    0
	000000f4    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
00000060 plugplay.exe
	00000064    0
	0000006c    0
	00000070    0
	00000074    0
	00000090    0
	00000094    0
00000078 winedevice.exe
	0000007c    0
	00000084    0
	00000088    0
	0000008c    0
	00000098    0
	000000a4    0
	000000a8    0
	000000b0    0
	000000bc    0
	000000c0    0
	000000c4    0
	000000c8    0
	000000cc    0
	000000d0    0
0000009c svchost.exe
	000000a0    0
	000000b4    0
	000000b8    0
000000d4 explorer.exe
	000000d8    0
	000000dc    0
	000000e0    0
000000e8 rpcss.exe
	000000ec    0
	000000f8    0
	000000fc    0
	00000100    0
	00000104    0
	00000108    0
	0000010c    0
System information:
    Wine build: wine-6.2
    Platform: x86_64
    Version: Windows 7
    Host system: Darwin
    Host version: 21.0.0
`

**Comment by nrlquaker** [comment]
Not following [Reporting bugs](https://github.com/nrlquaker/winbox-mac#reporting-bugs). Closing.
