### ISSUE TITLE
v3.34 connecting to device -> app crashed

### ISSUE THREAD

**Issue by hunter-nl** [nrlquaker/winbox-mac#93]
**Describe the bug**
After upgrading to v3.34 (from v3.32) The main screen opens. When I select one of my mikrotik devices to open a session, inbox-mac crashed.

**To Reproduce**
1. Start winmox-mac
2. main screen opens
3. Select one of the devices
4. Click on Connect button
5. App crashed

**Expected behavior**
Should not crash

**Desktop (please complete the following information):**
 - macOS version: 12.2
 - macOS language English
 - Winbox-mac version 3.34
 - Winbox version 3.34

**Comment by nrlquaker** [comment]
Please provide log. Just launch app from terminal:
`/Applications/Winbox-mac.app/Contents/MacOS/winbox-mac`

**Comment by hunter-nl** [comment]
I did a workaround. Installed 3.32 version and an internal winbox upgrade to 3.35.  Then it is working fine.

**Comment by nrlquaker** [comment]
From 3.35 changelog:
>fixed crash when connecting in new window (introduced in v3.33).

Maybe that's and issue.
