### ISSUE TITLE
McAfee malware detection

### ISSUE THREAD

**Issue by omeha2** [nrlquaker/winbox-mac#96]
**Checklist**

- [*] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [*] I made sure this is not the original Winbox issue.

**Describe the bug**
After installing winbox-mac. McAfee detects malware inside 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/6492169/159457266-e5292532-4a64-46d3-83d8-a5ca9d3675ae.png">

Latest version of winbox.
Latest version of macafee(10.7.8)

**Comment by nrlquaker** [comment]
Its false positive. Check https://github.com/nrlquaker/winbox-mac/issues/52#issuecomment-651579791
