### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gary-schiltz** [nrlquaker/winbox-mac#97]
I don't see a way to contact the developer, so I'm asking here.

Is this in any way related to Joshaven Potter's implementation (https://joshaven.com/resources/tools/winbox-for-mac/)?

**Comment by nrlquaker** [comment]
No. Last time I've checked his version is 1 to 1 copy of my app. Except icon and name. More info [here](https://github.com/Homebrew/homebrew-cask/pull/80038).

**Comment by gary-schiltz** [comment]
Thanks
