### ISSUE TITLE
No neighbor scanning with Monterey beta

### ISSUE THREAD

**Issue by andersah** [nrlquaker/winbox-mac#98]
Running macOS Monterey 12.4-beta (21F5048e) latest as of 2022-04-10.

After upgrading from previous beta no Mac address scanning in Winbox-mac.app Connection window available. Neighbor field empty even after pushing Refresh. By manually filling in Mac-address the inbox window opens. (using IP address also ok).

Also tested running winbox64.exe fetched from mikrotik with wine-stable and wine-staging (7.5) but in this case only connection by IP address works. No Mac connection, no neighbor scanning. (terminal output listed below)

My conclusion is that a change in macOS restricts binding to ports for wine.

aa@miniMac ~ % /opt/homebrew/bin/wine64 /Users/aa/applications/winbox64.exe
0024:fixme:esync:do_esync eventfd not supported on this platform.
002c:fixme:esync:do_esync eventfd not supported on this platform.
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0034:fixme:esync:do_esync eventfd not supported on this platform.
003c:fixme:esync:do_esync eventfd not supported on this platform.
0048:fixme:esync:do_esync eventfd not supported on this platform.
0068:fixme:esync:do_esync eventfd not supported on this platform.
008c:fixme:esync:do_esync eventfd not supported on this platform.
00a4:fixme:esync:do_esync eventfd not supported on this platform.
00bc:fixme:esync:do_esync eventfd not supported on this platform.
00d0:fixme:esync:do_esync eventfd not supported on this platform.
00f8:fixme:esync:do_esync eventfd not supported on this platform.
0100:fixme:esync:do_esync eventfd not supported on this platform.
creating Window Class routeros_null
creating Window Class routeros_connect
DPI=96
EMS=13
ERROR: bad bmp format id=2329
biPlanes=1, biBitCount=1, biCompression=0
ERROR: bad bmp format id=3329
biPlanes=1, biBitCount=1, biCompression=0
creating Window Class routeros_dbl_canvas
00bc:fixme:imm:ImeSetActiveContext (0x270400, 0): stub
00bc:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000270400): stub
0100:fixme:imm:ImeSetActiveContext (0x56c50, 1): stub
0100:fixme:imm:ImmReleaseContext (0000000000020062, 0000000000056C50): stub
rescaleDPI starting-dpi=96, zoom=1 result=120
DPI CHANGED to 120
rescale font 96 to 120
EMS=16
 discovery started
rescaning
bind: 10048
loadConfig C:\users\aa\AppData\Roaming\Mikrotik\Winbox\Addresses.cdb
rescaning
bind: 10048
rescaning
bind: 10048
rescaning
bind: 10048

**Comment by nrlquaker** [comment]
beta releases of macOS are not supported. Lets wait for the stable release.

**Comment by dchang0** [comment]
I confirm that this behavior is happening for the stable release of MacOS Monterey. My version is Monterey 12.7.2.

**Comment by belthesar** [comment]
I can confirm that this works normally with Winbox-mac, so I would encourage you to look into Winbox and Mikrotik neighbor discovery troubleshooting steps. Specifically, making sure that Neighbor discovery / LLDP is enabled in RouterOS on the network segment that you're connected to, and that there isn't any firewall or broadcast discovery issues in between you and your device. If you've ruled out all of those other issues, please feel free to update this issue and we can reopen it to see if there's an issue with the wrapper.
