### ISSUE TITLE
Chinese garbled（中文乱码）

### ISSUE THREAD

**Issue by coolchenK** [nrlquaker/winbox-mac#99]
**Checklist**

- [Y] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/nrlquaker/winbox-mac#reporting-bugs).
- [Y] I made sure this is not the original Winbox issue.

**Describe the bug**
Chinese garbled
中文乱码

**Screenshots**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/13838753/171787171-c483324a-8692-48e4-b3d2-c604de95aada.png">

**Desktop (please complete the following information):**
 - macOS version: [12.4 (21F79)]
 - macOS language [Chinese]
 - Winbox-mac version [3.35]
 - Winbox version [3.35]

**Comment by nrlquaker** [comment]
Please check #86
